const gwJSON = {
  "output": {
    "results": [
      {
        "brand": "Motorola",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Moto Z2 Play",
        "productId": "dev7920215",
        "originalPrice": null,
        "price": "17.00",
        "fullRetailPrice": "408.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/MotoZ2Play_MRKT_LunarGrayDv?$device-lg$",
        "offerImage": null,
        "offerDescription": "Now only $10/mo. No trade-in required.\r<a href=\"/digital/device/deviceDetails/?deviceProdId=dev7920215&contractTerm=99&deviceSkuId=sku2480355\">View Details</a>",
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/MotoZ2Play_MRKT_LunarGrayDv?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev7920215&contractTerm=99&deviceSkuId=sku2480355",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Apple",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "iPhone&reg; SE",
        "productId": "dev6000008",
        "originalPrice": null,
        "price": "14.58",
        "fullRetailPrice": "349.99",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iPhoneSE_SpGry?$device-lg$",
        "offerImage": null,
        "offerDescription": "$200 off any iPad w/ purchase.<a href=\"/digital/device/deviceDetails/?deviceProdId=dev6000008&contractTerm=99&deviceSkuId=sku2350125\">View Details</a>",
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iPhoneSE_SpGry?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6000008&contractTerm=99&deviceSkuId=sku2350125",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Samsung",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Galaxy S8",
        "productId": "dev7480001",
        "originalPrice": null,
        "price": "31.50",
        "fullRetailPrice": "756.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Black?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Black?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev7480001&contractTerm=99&deviceSkuId=sku2360002",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Samsung",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Galaxy S8+",
        "productId": "dev7480002",
        "originalPrice": null,
        "price": "35.00",
        "fullRetailPrice": "840.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Plus_Black?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Plus_Black?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev7480002&contractTerm=99&deviceSkuId=sku2360005",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "LG",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "G6&trade;",
        "productId": "dev7320059",
        "originalPrice": null,
        "price": "28.00",
        "fullRetailPrice": "672.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_G6_Silver?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/LG_G6_Silver?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev7320059&contractTerm=99&deviceSkuId=sku2320123",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Google",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Pixel, Phone by Google",
        "productId": "dev6720118",
        "originalPrice": "27.08",
        "price": "15.00",
        "fullRetailPrice": "649.99",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Sailfish_Slate?$device-lg$",
        "offerImage": null,
        "offerDescription": "Now $15/mo. with unlimited plan.\r<a href=\"/digital/device/deviceDetails/?deviceProdId=dev6720118&contractTerm=99&deviceSkuId=sku2170529\">View Details</a>",
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Sailfish_Slate?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6720118&contractTerm=99&deviceSkuId=sku2170529",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Google",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Pixel XL, Phone by Google",
        "productId": "dev6720119",
        "originalPrice": "32.08",
        "price": "20.00",
        "fullRetailPrice": "769.99",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver?$device-lg$",
        "offerImage": null,
        "offerDescription": "Now $20/mo with unlimited plan.\r<a href=\"/digital/device/deviceDetails/?deviceProdId=dev6720119&contractTerm=99&deviceSkuId=sku2170533\">View Details</a>",
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6720119&contractTerm=99&deviceSkuId=sku2170533",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Apple",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "iPhone&reg; 7",
        "productId": "dev6640012",
        "originalPrice": null,
        "price": "27.08",
        "fullRetailPrice": "649.99",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-red?$device-lg$",
        "offerImage": null,
        "offerDescription": "$200 off any iPad w/ purchase.<a href=\"/digital/device/deviceDetails/?deviceProdId=dev6640012&contractTerm=99&deviceSkuId=sku2350190\">View Details</a>",
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-red?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6640012&contractTerm=99&deviceSkuId=sku2350190",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Apple",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "iPhone&reg; 7 Plus",
        "productId": "dev6640013",
        "originalPrice": null,
        "price": "32.08",
        "fullRetailPrice": "769.99",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-red?$device-lg$",
        "offerImage": null,
        "offerDescription": "$200 off any iPad w/ purchase.<a href=\"/digital/device/deviceDetails/?deviceProdId=dev6640013&contractTerm=99&deviceSkuId=sku2350182\">View Details</a>",
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-red?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6640013&contractTerm=99&deviceSkuId=sku2350182",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Motorola",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Moto Z Droid",
        "productId": "dev6360190",
        "originalPrice": null,
        "price": "26.00",
        "fullRetailPrice": "624.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Java_White_Gold?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Java_White_Gold?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6360190&contractTerm=99&deviceSkuId=sku2080196",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Motorola",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Moto Z Force Droid",
        "productId": "dev6360191",
        "originalPrice": "30.00",
        "price": "20.00",
        "fullRetailPrice": "480.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_JavaM_Black?$device-lg$",
        "offerImage": null,
        "offerDescription": "Online exclusive. Now only $20/mo.",
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_JavaM_Black?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6360191&contractTerm=99&deviceSkuId=sku2080197",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Apple",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "iPhone&reg; 6s",
        "productId": "dev5160002",
        "originalPrice": null,
        "price": "22.91",
        "fullRetailPrice": "549.99",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-spgry-front?$device-lg$",
        "offerImage": null,
        "offerDescription": "$200 off any iPad w/ purchase.<a href=\"/digital/device/deviceDetails/?deviceProdId=dev5160002&contractTerm=99&deviceSkuId=sku2160047\">View Details</a>",
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-spgry-front?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev5160002&contractTerm=99&deviceSkuId=sku2160047",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Samsung",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Galaxy S7",
        "productId": "dev5800066",
        "originalPrice": null,
        "price": "24.00",
        "fullRetailPrice": "576.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Hero_Black?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Hero_Black?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev5800066&contractTerm=99&deviceSkuId=sku1900310",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Apple",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "iPhone&reg; 6s Plus",
        "productId": "dev5160003",
        "originalPrice": null,
        "price": "27.08",
        "fullRetailPrice": "649.99",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-plus-spgry-front?$device-lg$",
        "offerImage": null,
        "offerDescription": "$200 off any iPad w/ purchase.<a href=\"/digital/device/deviceDetails/?deviceProdId=dev5160003&contractTerm=99&deviceSkuId=sku2160035\">View Details</a>",
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-plus-spgry-front?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev5160003&contractTerm=99&deviceSkuId=sku2160035",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "LG",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "K20 V",
        "productId": "dev7400003",
        "originalPrice": null,
        "price": "7.00",
        "fullRetailPrice": "168.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_K20V?$device-lg$",
        "offerImage": null,
        "offerDescription": "Get this phone free. No trade-in required.<a href=\"/digital/device/deviceDetails/?deviceProdId=dev7400003&contractTerm=99&deviceSkuId=sku2340115\">View Details</a>",
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/LG_K20V?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev7400003&contractTerm=99&deviceSkuId=sku2340115",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Samsung",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Galaxy J7 V",
        "productId": "dev7400030",
        "originalPrice": null,
        "price": "10.00",
        "fullRetailPrice": "240.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Sam_J7_V_Silver?$device-lg$",
        "offerImage": null,
        "offerDescription": "Now only $5/mo. No trade-in required.<a href=\"/digital/device/deviceDetails/?deviceProdId=dev7400030&contractTerm=99&deviceSkuId=sku2340203\">View Details</a>",
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Sam_J7_V_Silver?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev7400030&contractTerm=99&deviceSkuId=sku2340203",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Samsung",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Galaxy J3 Eclipse",
        "productId": "dev7920002",
        "originalPrice": null,
        "price": "7.00",
        "fullRetailPrice": "168.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/samsung-galaxy-j3-eclipse-black?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/samsung-galaxy-j3-eclipse-black?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev7920002&contractTerm=99&deviceSkuId=sku2480004",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Kyocera",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "DuraForce PRO with Sapphire Shield",
        "productId": "dev6760021",
        "originalPrice": null,
        "price": "17.00",
        "fullRetailPrice": "408.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Kyocera_DuraForce_Pro?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Kyocera_DuraForce_Pro?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6760021&contractTerm=99&deviceSkuId=sku2260136",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "LG",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Stylo 2 V",
        "productId": "dev6760013",
        "originalPrice": null,
        "price": "10.00",
        "fullRetailPrice": "240.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_Stylo_2V?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/LG_Stylo_2V?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6760013&contractTerm=99&deviceSkuId=sku2180004",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Microsoft",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Lumia 735",
        "productId": "dev4800004",
        "originalPrice": null,
        "price": "5.00",
        "fullRetailPrice": "120.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Nokia_Lumia_735?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Nokia_Lumia_735?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev4800004&contractTerm=99&deviceSkuId=sku1650105",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "HTC",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Desire&reg; 530",
        "productId": "dev6440049",
        "originalPrice": null,
        "price": "6.00",
        "fullRetailPrice": "144.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/HTC_Desire_530_Blue?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/HTC_Desire_530_Blue?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6440049&contractTerm=99&deviceSkuId=sku2100180",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "LG",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "V20",
        "productId": "dev6800082",
        "originalPrice": null,
        "price": "24.00",
        "fullRetailPrice": "576.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_V20_Titanium?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/LG_V20_Titanium?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6800082&contractTerm=99&deviceSkuId=sku2190286",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Apple",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "iPhone&reg; 6 (Certified Pre-Owned)",
        "productId": "dev4840002",
        "originalPrice": null,
        "price": "14.99",
        "fullRetailPrice": "359.99",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone-6-spacegray?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone-6-spacegray?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev4840002&contractTerm=99&deviceSkuId=sku1210804",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Apple",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "iPhone&reg; 6s (Certified Pre-Owned)",
        "productId": "dev7320062",
        "originalPrice": null,
        "price": "17.91",
        "fullRetailPrice": "429.99",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-spgry-front?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-spgry-front?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev7320062&contractTerm=99&deviceSkuId=sku2310387",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Apple",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "iPhone&reg; 6s Plus (Certified Pre-Owned)",
        "productId": "dev7680032",
        "originalPrice": null,
        "price": "22.08",
        "fullRetailPrice": "529.99",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-plus-rsgld-front?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-plus-rsgld-front?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev7680032&contractTerm=99&deviceSkuId=sku2400293",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Samsung",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Galaxy S&reg;6 edge (Certified Pre-Owned)",
        "productId": "dev7680027",
        "originalPrice": null,
        "price": "20.33",
        "fullRetailPrice": "488.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S6_Edge_White?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S6_Edge_White?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev7680027&contractTerm=99&deviceSkuId=sku2400200",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Motorola",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "Moto Z Play Droid",
        "productId": "dev6560041",
        "originalPrice": null,
        "price": "17.00",
        "fullRetailPrice": "408.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Z_Play_Droid_Edition_White?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Z_Play_Droid_Edition_White?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6560041&contractTerm=99&deviceSkuId=sku2130141",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "HTC",
        "priceText": "24 months, 0% APR",
        "priceDetail": "/mo",
        "displayName": "10&trade;",
        "productId": "dev6080072",
        "originalPrice": null,
        "price": "27.00",
        "fullRetailPrice": "648.00",
        "fullRetailPriceText": "retail",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/HTC_10?$device-lg$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/HTC_10?$device-lg$",
        "pdpRedirectUrl": "/digital/device/deviceDetails/?deviceProdId=dev6080072&contractTerm=99&deviceSkuId=sku1980150",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      }
    ],
    "standaloneAccessories": false,
    "deviceDisplayName": null,
    "priceOptions": [
      {
        "displayName": "Monthly Payment",
        "url": null,
        "description": "Pay in 24 monthly installments, interest-free.",
        "selected": true,
        "contractTerm": "99"
      },
      {
        "displayName": "Retail Price",
        "url": null,
        "description": "Total price will be due today.",
        "selected": false,
        "contractTerm": "0"
      }
    ],
    "filters": [
      {
        "filterOptions": [
          {
            "displayName": "All",
            "url": "/digital/smartphones/",
            "selected": true
          },
          {
            "displayName": "Apple",
            "url": "/digital/smartphones/?flow=EUP&selectedMTN=&selectionQueryString=N%3D4294824674",
            "selected": false
          },
          {
            "displayName": "Samsung",
            "url": "/digital/smartphones/?flow=EUP&selectedMTN=&selectionQueryString=N%3D4294825737",
            "selected": false
          },
          {
            "displayName": "Android",
            "url": "/digital/smartphones/?flow=EUP&selectedMTN=&selectionQueryString=N%3D4294820610",
            "selected": false
          },
          {
            "displayName": "Motorola",
            "url": "/digital/smartphones/?flow=EUP&selectedMTN=&selectionQueryString=N%3D4294825432",
            "selected": false
          }
        ],
        "filterName": "Brand"
      }
    ],
    "mtnDetails": null,
    "deviceProductId": null,
    "gridWallUrl": "/digital/smartphones/",
    "title": "Smartphones"
  },
  "ErrorMap": null,
  "statusMessage": "Service completed Successfully.",
  "statusCode": "00"
};
export default gwJSON;
