const accessoryPDP = {
  "statusCode": "00",
  "output": {
    "brand": "Fitbit",
    "displayName": "Charge 2 Heart Rate and Fitness Wristband",
    "accId": "acc6640086",
    "displayImageURL": "https://ss7.vzw.com/is/image/VerizonWireless/fitbit-charge-2-heart-rate-fitness-wristband-black-large-fb407sbkl-iset?$acc-med$",
    "displayImageLargeURL": "https://ss7.vzw.com/is/image/VerizonWireless/fitbit-charge-2-heart-rate-fitness-wristband-black-large-fb407sbkl-iset?$acc-lg$",
    "outOfStock": false,
    "description": "Make the most of your workouts and overall physical fitness with the Fitbit Charge 2  heart rate and fitness wristband.<br /><br />  The Fitbit Charge 2 is packed with revolutionary features like PurePulse&trade; heart rate monitoring*, all-day activity tracking, auto-exercise recognition, connected GPS, guided breathing sessions and a personalized  cardio fitness score. It's also water-resistant, so no need to worry if you get caught in the rain.  <br /><br />  <strong>Make every beat count with PurePulse&trade; heart rate monitoring.</strong><br/> With continuous, automatic, wrist-based heart rate tracking,* Fitbit Charge 2 does so much more than just measure your pulse. It provides simplified heart rate zones to help you gauge your exercise. It monitors your calorie burn with better accuracy. It provides tools for you to analyze all-day and resting heart rate trends so you can see how your fitness levels improve. And it does all this without an uncomfortable chest strap.<br /><br />  <strong>Automatic exercise recognition and multi-sport tracking.</strong><br/> SmartTrack&trade; technology automatically recognizes select exercises and records them in the Fitbit app. And the multi-sport tracking feature effortlessly reports runs, biking, cardio and more with real-time stats. It's all part of taking it to the next level.<br /><br />  <strong>Your fitness routine doesn't end with your workout.</strong><br/> Wear the fitness wristband all day for continuous activity tracking. Charge 2 tracks your steps, distance walked, calories burned, floors climbed and active minutes. Review your stats at the end of each day for greater motivation.<br /><br />  <strong>Connected GPS helps maximizes your run.</strong><br/> The Fitbit Charge 2 GPS function works with your compatible nearby smartphone to map your running route and show real-time stats like pace, distance and speed.<br /><br />  <strong>Stay connected to smartphone calls, texts and more.</strong><br/> Keep in touch with what s important. See call, text and calendar notifications on your tracker's display when your phone is nearby.<br /><br />  <strong>Guided breathing sessions.</strong><br/> Don't forget to take a time out. By tracking your real-time heart rate, Charge 2's two- or five-minute sessions give you personalized prompts that help guide you through a relaxing breathing exercise.<br /><br />  <strong>Automatically track your sleep patterns.</strong><br/> And, when your day is done, use Charge 2's sleep tracking feature to make the most of your downtime. Monitor how long and how well you sleep. When it's time to wake, do so gently with the tracker's silent vibrating alarm.<br /><br />  <strong>Long life battery.</strong><br/> Track activity and sleep all day and all night. The long life battery lasts for up to five days before requiring a charge.  <br /><br />  <strong>Show your style with interchangeable bands.</strong><br/> Make your tracker your own with an assortment of interchangeable leather and sport accessory bands (sold separately).<br /><br />  <strong>Use the app to see the big picture.</strong><br/> Put it all together using the Fitbit app. View easy-to-read charts and graphs to visualize your progress.  Record your workouts, share your stats and encourage (or taunt) and compete with friends. Monitor your status on the leaderboard, and even use it to log your calorie intake and meals. Log food fast with a barcode scanner, calorie estimator, meal shortcuts and expanded food database.<br /><br /> <strong>What's in the box</strong><br/> One Charge 2 tracker, Charge 2 bands and a charging cable.<br /><br />",
    "specification": "<ul class=\"details-list\"><li>Large fits wrists 6.7 – 8.1 inches (170 - 206 mm)</li><li>Small fits wrists 5.5 - 6.7 inches (140 - 170 mm)¿</li>",
    "shortDescription": "Make the most of your workouts and overall physical fitness with the Fitbit Charge 2  heart rate and fitness wristband.<br /><br />  The Fitbit Charge 2 is packed with revolutionary features like Pure",
    "promotionDetail": "",
    "skuDetails": [
      {
        "skuId": "sku2120086",
        "displayName": "Charge 2 Heart Rate and Fitness Wristband - Black (Large)",
        "retailPrice": "149.99",
        "discountedPrice": null,
        "promotionDetail": "SALE 0% OFF",
        "shippingDateLabel": null,
        "inventoryStatus": 1000,
        "sorSkuId": "FB407SBKL",
        "preSelected": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/fitbit-charge-2-heart-rate-fitness-wristband-black-large-fb407sbkl-iset?$acc-lg$",
        "size": "Large",
        "sizeDisplayName": "L",
        "colorStyle": "#000000",
        "commerceItemId": null,
        "colorName": "Black"
      },
      {
        "skuId": "sku2120141",
        "displayName": "Charge 2 Heart Rate and Fitness Wristband - Black (Small)",
        "retailPrice": "149.99",
        "discountedPrice": null,
        "promotionDetail": "SALE 0% OFF",
        "shippingDateLabel": null,
        "inventoryStatus": 1000,
        "sorSkuId": "FB407SBKS",
        "preSelected": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/fitbit-charge-2-heart-rate-fitness-wristband-black-small-fb407sbks-iset?$acc-lg$",
        "size": "Small",
        "sizeDisplayName": "S",
        "colorStyle": "#000000",
        "commerceItemId": null,
        "colorName": "Black"
      },
      {
        "skuId": "sku2120143",
        "displayName": "Charge 2 Heart Rate and Fitness Wristband - Teal",
        "retailPrice": "149.99",
        "discountedPrice": null,
        "promotionDetail": "SALE 0% OFF",
        "shippingDateLabel": null,
        "inventoryStatus": 1000,
        "sorSkuId": "FB407STEL",
        "preSelected": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/fitbit-charge-2-heart-rate-fitness-wristband-teal-large-fb407stel-iset?$acc-lg$",
        "size": "Large",
        "sizeDisplayName": "L",
        "colorStyle": "#008080",
        "commerceItemId": null,
        "colorName": "Teal"
      },
      {
        "skuId": "sku2120005",
        "displayName": "Charge 2 Heart Rate and Fitness Wristband - Teal",
        "retailPrice": "149.99",
        "discountedPrice": null,
        "promotionDetail": "SALE 0% OFF",
        "shippingDateLabel": null,
        "inventoryStatus": 1000,
        "sorSkuId": "FB407STES",
        "preSelected": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/fitbit-charge-2-heart-rate-fitness-wristband-teal-small-fb407stes-iset?$acc-lg$",
        "size": "Small",
        "sizeDisplayName": "S",
        "colorStyle": "#008080",
        "commerceItemId": null,
        "colorName": "Teal"
      },
      {
        "skuId": "sku2120007",
        "displayName": "Charge 2 Heart Rate and Fitness Wristband - Plum",
        "retailPrice": "149.99",
        "discountedPrice": null,
        "promotionDetail": "SALE 0% OFF",
        "shippingDateLabel": null,
        "inventoryStatus": 1000,
        "sorSkuId": "FB407SPML",
        "preSelected": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/fitbit-charge-2-heart-rate-fitness-wristband-plum-large-fb407spml-iset?$acc-lg$",
        "size": "Large",
        "sizeDisplayName": "L",
        "colorStyle": "#7F7EAD",
        "commerceItemId": null,
        "colorName": "Plum"
      },
      {
        "skuId": "sku2120096",
        "displayName": "Charge 2 Heart Rate and Fitness Wristband - Plum",
        "retailPrice": "149.99",
        "discountedPrice": null,
        "promotionDetail": "SALE 0% OFF",
        "shippingDateLabel": null,
        "inventoryStatus": 1000,
        "sorSkuId": "FB407SPMS",
        "preSelected": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/fitbit-charge-2-heart-rate-fitness-wristband-plum-small-fb407spms-iset?$acc-lg$",
        "size": "Small",
        "sizeDisplayName": "S",
        "colorStyle": "#7F7EAD",
        "commerceItemId": null,
        "colorName": "Plum"
      },
      {
        "skuId": "sku2120084",
        "displayName": "Charge 2 Heart Rate and Fitness Wristband - Blue",
        "retailPrice": "149.99",
        "discountedPrice": null,
        "promotionDetail": "SALE 0% OFF",
        "shippingDateLabel": null,
        "inventoryStatus": 1000,
        "sorSkuId": "FB407SBUL",
        "preSelected": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/fitbit-charge-2-heart-rate-fitness-wristband-blue-large-fb407sbul-iset?$acc-lg$",
        "size": "Large",
        "sizeDisplayName": "L",
        "colorStyle": "#003399",
        "commerceItemId": null,
        "colorName": "Blue"
      },
      {
        "skuId": "sku2120130",
        "displayName": "Charge 2 Heart Rate and Fitness Wristband - Blue",
        "retailPrice": "149.99",
        "discountedPrice": null,
        "promotionDetail": "SALE 0% OFF",
        "shippingDateLabel": null,
        "inventoryStatus": 1000,
        "sorSkuId": "FB407SBUS",
        "preSelected": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/fitbit-charge-2-heart-rate-fitness-wristband-blue-small-fb407sbus-iset?$acc-lg$",
        "size": "Small",
        "sizeDisplayName": "S",
        "colorStyle": "#003399",
        "commerceItemId": null,
        "colorName": "Blue"
      }
    ],
    "goToSuccessUrl": null,
    "addToCartURL": "/digital/cart/addOrRemoveAccessory"
  },
  "errorMap": null,
  "statusMessage": "Service completed Successfully."
};

export default accessoryPDP;
