export const ASYNC_FETCH = 'ASYNC_FETCH';
export const ASYNC_FETCH_SUCCESS = 'ASYNC_FETCH_SUCCESS';
export const ASYNC_FETCH_FAILURE = 'ASYNC_FETCH_FAILURE';
export const ASYNC_FETCH_INVALIDATE = 'ASYNC_FETCH_INVALIDATE';
export const FETCH_DEVICE_IMAGE = 'FETCH_DEVICE_IMAGE';
export const FETCH_DEVICE_IMAGE_SUCCESS = 'FETCH_DEVICE_IMAGE_SUCCESS';
export const FETCH_ACCESSORIES_BUNDLE_SUCCESS = 'FETCH_ACCESSORIES_BUNDLE_SUCCESS';

