const gridwallJson = {
  "output": {
    "results": [
      {
        "brand": "Power Bright",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Energizer Cup Inverter",
        "productId": "acc2280001",
        "originalPrice": "39.99",
        "price": "29.99",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/energizer-cup-inverter-charger-engcupinv-iset?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/energizer-cup-inverter-charger-engcupinv-iset?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc2280001&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Motorola",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Power Pack Slim 5100 - DROID Ballistic Nylon",
        "productId": "acc3160084",
        "originalPrice": "79.98",
        "price": "79.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-power-pack-slim-5100-droid-ballistic-nylon-iset-drdunipwr7?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-power-pack-slim-5100-droid-ballistic-nylon-iset-drdunipwr7?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc3160084&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Apple",
        "priceText": null,
        "priceDetail": null,
        "displayName": "5W USB Power Adapter",
        "productId": "acc40447",
        "originalPrice": "19.99",
        "price": "19.99",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone5_usb_power_adapter?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone5_usb_power_adapter?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40447&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Apple",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Charger - 12W USB Power Adapter",
        "productId": "acc40364",
        "originalPrice": "19.97",
        "price": "19.97",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_12w_usb_power_adapter_md836lla?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/apple_12w_usb_power_adapter_md836lla?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40364&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Mophie",
        "priceText": null,
        "priceDetail": null,
        "displayName": "powerstation&trade; (4000mAh)",
        "productId": "acc40351",
        "originalPrice": "69.98",
        "price": "69.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/mophie-powerstation-pink-iset-mophps4kpnk?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/mophie-powerstation-pink-iset-mophps4kpnk?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40351&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Motorola",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Power Pack Slim 2000",
        "productId": "acc43531",
        "originalPrice": "39.98",
        "price": "39.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-power-pack-slim-2000-DRDUNIPWR2-vertical?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-power-pack-slim-2000-DRDUNIPWR2-vertical?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc43531&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Apple",
        "priceText": null,
        "priceDetail": null,
        "displayName": "iPhone 4/4s USB (3 ft Cable)",
        "productId": "acc40382",
        "originalPrice": "19.99",
        "price": "19.99",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone4_usb_3ft_cable?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone4_usb_3ft_cable?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40382&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Motorola",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Motorola Power Pack Slim 4000",
        "productId": "acc43231",
        "originalPrice": "79.98",
        "price": "79.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-power-pack-slim-2000-DRDUNIPWR2-vertical?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-power-pack-slim-2000-DRDUNIPWR2-vertical?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc43231&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Samsin",
        "priceText": null,
        "priceDetail": null,
        "displayName": "3.5mm Adapter - Converts Any 3.5mm connector to 2.5mm (Female 3.5 to male 2.5)",
        "productId": "acc40397",
        "originalPrice": "4.99",
        "price": "4.99",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/adapter_sha35?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/adapter_sha35?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40397&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Verizon",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Rapid Wall Charger with 6 ft. Cable ",
        "productId": "acc40426",
        "originalPrice": "29.99",
        "price": "29.99",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_frog_wall_charger_30pin_angle_apl21tvl_f?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/apple_frog_wall_charger_30pin_angle_apl21tvl_f?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40426&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Motorola",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Power Pack Slim 5100 - Dark Canvas",
        "productId": "acc3160086",
        "originalPrice": "79.98",
        "price": "79.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-power-pack-slim-5100-dark-canvas-iset-micunipwr8?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-power-pack-slim-5100-dark-canvas-iset-micunipwr8?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc3160086&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Beats",
        "priceText": null,
        "priceDetail": null,
        "displayName": "RemoteTalk Audio Cable",
        "productId": "acc4480009",
        "originalPrice": "29.99",
        "price": "29.99",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/beats-audio-replacement-cable-remote-talk-red-iset-mhdv2g-a?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/beats-audio-replacement-cable-remote-talk-red-iset-mhdv2g-a?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc4480009&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Sony",
        "priceText": null,
        "priceDetail": null,
        "displayName": "10000 mAh Portable Power Supply",
        "productId": "acc2240057",
        "originalPrice": "79.99",
        "price": "79.99",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/sony-usb-portable-charger-10000mah-iset-scpf10lsv?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/sony-usb-portable-charger-10000mah-iset-scpf10lsv?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc2240057&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Mophie",
        "priceText": null,
        "priceDetail": null,
        "displayName": "powerstation mini",
        "productId": "acc2080011",
        "originalPrice": "49.98",
        "price": "49.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/mophie-powerstation-mini-blu-iset-mophpsminiblu?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/mophie-powerstation-mini-blu-iset-mophpsminiblu?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc2080011&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Verizon",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Vehicle Charger For iPod, iPhone and iPad",
        "productId": "acc40465",
        "originalPrice": "29.99",
        "price": "29.99",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_frog_vpc_30pin_angle_apl21vpc_f?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/apple_frog_vpc_30pin_angle_apl21vpc_f?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40465&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Samsung",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Galaxy Portable Battery Pack, 9000 mAh",
        "productId": "acc40362",
        "originalPrice": "79.98",
        "price": "79.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/sam_galaxy_portable_battery_9000_mAh_samunibat9k?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/sam_galaxy_portable_battery_9000_mAh_samunibat9k?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40362&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Mophie",
        "priceText": null,
        "priceDetail": null,
        "displayName": "iPhone 4/4s juice pack plus",
        "productId": "acc40363",
        "originalPrice": "79.98",
        "price": "79.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_mophie_juice_pack_2000_black?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_mophie_juice_pack_2000_black?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40363&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Samsin",
        "priceText": null,
        "priceDetail": null,
        "displayName": "2.5mm Adapter - Converts Any 2.5mm connector to 3.5mm (Female 2.5 to male 3.5)",
        "productId": "acc40398",
        "originalPrice": "2.98",
        "price": "2.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/adapter_sha25?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/adapter_sha25?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40398&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Belkin",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Belkin Swivel Wall Charger - 10W Stand Alone",
        "productId": "acc40429",
        "originalPrice": "14.98",
        "price": "14.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/belkin-swivel-wall-charger?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/belkin-swivel-wall-charger?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40429&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Monster",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Monster Mobile PowerCard",
        "productId": "acc1080010",
        "originalPrice": "34.98",
        "price": "34.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/monster-mobile-powercard-slate-black-133330?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/monster-mobile-powercard-slate-black-133330?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc1080010&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Belkin",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Swivel Charger 2.1 AMP",
        "productId": "acc40443",
        "originalPrice": "8.98",
        "price": "8.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/belkin_swivel_wall_charger?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/belkin_swivel_wall_charger?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40443&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Everwin",
        "priceText": null,
        "priceDetail": null,
        "displayName": "iPhone 4/4s/iPad USB Cable (6 ft)",
        "productId": "acc40377",
        "originalPrice": "14.98",
        "price": "14.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone4_6ft_usb_cable?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone4_6ft_usb_cable?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40377&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Motorola",
        "priceText": null,
        "priceDetail": null,
        "displayName": "Power Pack Micro",
        "productId": "acc3160082",
        "originalPrice": "39.98",
        "price": "39.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-power-pack-micro-iset-drdunipwr5?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-power-pack-micro-iset-drdunipwr5?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc3160082&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      },
      {
        "brand": "Mophie",
        "priceText": null,
        "priceDetail": null,
        "displayName": "powerstation PRO",
        "productId": "acc40453",
        "originalPrice": "49.98",
        "price": "49.98",
        "fullRetailPrice": null,
        "fullRetailPriceText": null,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/mophie_juice_pack_powerstation_6000mah_moophpspro?$acc-med$",
        "offerImage": null,
        "offerDescription": null,
        "url": "https://ss7.vzw.com/is/image/VerizonWireless/mophie_juice_pack_powerstation_6000mah_moophpspro?$acc-med$",
        "pdpRedirectUrl": "/digital/accessoryDetails/?accProdId=acc40453&contractTerm=0&deviceSkuId=null",
        "promoCardStatusFlag": null,
        "offerDescriptionUrl": null
      }
    ],
    "standaloneAccessories": true,
    "deviceDisplayName": "iPhone&reg; 4s",
    "priceOptions": [
      {
        "displayName": null,
        "url": null,
        "description": "Total price will be due today.",
        "selected": true,
        "contractTerm": "0"
      }
    ],
    "filters": [
      {
        "filterOptions": [
          {
            "displayName": "All",
            "url": "/digital/standaloneAccessory/batteriesandchargers/",
            "selected": true
          },
          {
            "displayName": "Apple",
            "url": "",
            "selected": false
          },
          {
            "displayName": "Beats",
            "url": "",
            "selected": false
          },
          {
            "displayName": "Belkin",
            "url": "",
            "selected": false
          },
          {
            "displayName": "EverWin",
            "url": "",
            "selected": false
          },
          {
            "displayName": "Monster",
            "url": "",
            "selected": false
          },
          {
            "displayName": "mophie",
            "url": "",
            "selected": false
          },
          {
            "displayName": "Motorola",
            "url": "",
            "selected": false
          },
          {
            "displayName": "Power Bright",
            "url": "",
            "selected": false
          },
          {
            "displayName": "Samsin",
            "url": "",
            "selected": false
          },
          {
            "displayName": "Samsung",
            "url": "",
            "selected": false
          }
        ],
        "filterName": "Brand"
      }
    ],
    "mtnDetails": [
      {
        "upgradeEligbile": true,
        "displayMtn": "301.785.7876",
        "mtn": "3017857876",
        "encryptedMTN": "424uj+jSrRQNAq0hbkE33g==",
        "upgradeMessage": null,
        "nickname": "JACK REYES",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_4s_white?$device-lg$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "iPhone&reg; 4s",
        "deviceName": "Apple&reg; iPhone&reg; 4S White 16GB",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev440044",
        "alwaysEligibleForUpgrade": false,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "301.785.7873",
        "mtn": "3017857873",
        "encryptedMTN": "424uj+jSrRQqZXoHhch+kA==",
        "upgradeMessage": null,
        "nickname": "JACK REYES",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_4s_white?$device-lg$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "iPhone&reg; 4s",
        "deviceName": "Apple&reg; iPhone&reg; 4S White 16GB",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev440044",
        "alwaysEligibleForUpgrade": false,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "301.518.5453",
        "mtn": "3015185453",
        "encryptedMTN": "dsod4AWLki4jpIcvb1X5KA==",
        "upgradeMessage": null,
        "nickname": "JOSEPH REYES",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_4s_black?$device-lg$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "iPhone&reg; 4s",
        "deviceName": "Apple&reg; iPhone&reg; 4S Black 16GB",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev440044",
        "alwaysEligibleForUpgrade": false,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "301.518.5452",
        "mtn": "3015185452",
        "encryptedMTN": "dsod4AWLki76tlqaqaJ0yg==",
        "upgradeMessage": null,
        "nickname": "ETHAN REYES",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_4s_black?$device-lg$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "iPhone&reg; 4s",
        "deviceName": "Apple&reg; iPhone&reg; 4S Black 16GB",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev440044",
        "alwaysEligibleForUpgrade": false,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      }
    ],
    "deviceProductId": "dev440044",
    "gridWallUrl": "/digital/standaloneAccessory/batteriesandchargers/",
    "title": "Smartphones"
  },
  "ErrorMap": null,
  "statusMessage": "Service completed Successfully.",
  "statusCode": "00"
};

export default gridwallJson;
