const cqJson =  {
  "html": {
    "OD_CART_PROTECTION_INFO_TITLE": "Five things you need to know about Equipment Protection",
    "OD_CART_PROTECTION_INFO_CONTENT": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
  },
  "label": {
    "DT_OD_CART_MAIN_TITLE":"It's time to review</br> your cart.",
    "OD_CART_SAVE_CART_CTA" :"Save cart",
    "OD_NS_NEW_SERVICE":"New service",
    "OD_DUE_TODAY_OFF_SALE": "% off sale",
    "OD_CART_RETAIL_PRICE_LBL":"Retail price",
    "OD_CART_TRADE_IN_URL": "/digital/tradein/prompt?gotoCart=true",
    "OD_CART_ZIP_CODE_SAVE_CTA": "Save",
    "OD_CART_SHIPPING_DATE_TITLE": "Shipping date",
    "OD_CART_SHIPPING_DATE_CONTENT": "Our shipping dates are just estimates, but we'll be sure to email you when your order is on the way.",
    "OD_CART_SHIPBY_ITEMAVAIL_TITLE": "Item availability",
    "OD_CART_SHIPBY_ITEMAVAIL_CONTENT": "This item is currently out of stock, but if you place your order we'll ship it as soon as we have more.",
    "OD_CART_SAVED_CART_ITEMS": "Saved items retrieved successfully. Cart restored.",
    "OD_CART_REMOVE_ITEM_TITLE": "Are you sure you want to remove this item from your cart?",
    "OD_CART_PAYMENT_TITLE": "Payment",
    "OD_CART_PAYMENT_CONTENT": "Don't worry.you won't be charged until your order ships.",
    "OD_CART_FOOTER_TEXT": "Want to start over?",
    "OD_CART_EST_SHIPDATE_TITLE": "Estimated",
    "OD_CART_EMPTY_CART_TITLE": "Your cart is lonely",
    "OD_CART_DUE_TODAY_DOWN_PAYMENT": "Down Payment",
    "OD_CART_DEVICE_PROTECTION_TITLE": "Device Protection Details",
    "OD_CART_CHECKOUT_CTA": "Check out",
    "OD_CART_ADD_ANOTHER_PROMO_TEXT": "Add another Promo code",
    "OD_CART_BACK_CTA": "Back",
    "OD_CART_MAIN_EDIT_CTA": "Edit",
    "OD_CART__MAIN_REMOVE_CTA": "Remove",
    "OD_CART_FULL_RETAIL_PRICE_TEXT": "Full Retail Device Price",
    "OD_CART_DUE_MONTHLY_PRICE_TEXT": "Device payment",
    "OD_CART_PRICE_SUB_TITLE": "For 24 months.0% APR.Retail Price: $",
    "OD_CART_BIC_TEXT": "You'll see a $/mo promo credit within 2-3 billing cycles.",
    "OD_CART_TWO_YEAR_PRICE_TEXT": "Device price with 2-year contract",
    "OD_CART_TRADE_IN_CREDIT_MSG": "Trade-in credit: $",
    "OD_CART_TRADE_IN_DEVICE_HEADER_MSG": "You'll see an estimated $ credit with 1-2 bill cycles.",
    "OD_CART_TRADE_IN_CREDIT_MSG_BIC": "Trade-in credit for this device:",
    "OD_CART_TRADE_IN_DEVICE_HEADER_MSG_BIC": "Your $/mo credit will start in 2-3 bills.",
    "OD_CART_TRADE_IN_DEVICE_FOOTER": "This is just an estimate until we get your phone and can check it out.",
    "OD_CART_LAC_TITLE": "line access",
    "OD_CART_SHOP_MORE": "/digital/shoplanding/",
    "OD_CART_TRADEIN_CTA": "Got it",
    "OD_CART_INITIATE_CHECKOUT": "/digital/checkout/initiateCheckout",
    "OD_CART_TRADE_IN_TITLE": "Trade-in Credit for this device",
    "OD_CART_ADD_PROMO_TEXT": "Add a Promo Code",
    "OD_CART_TMPMD_HEADER_TITLE": "Good news, this device is already covered",
    "OD_CART_TMPMD_DETAILS_TEXT": "Total Mobile Protection Multi-device Covers all the devices in your account, You can change your protection plan within 30 days of purchase.",
    "OD_CART_TPMD_TITLE": "Total Mobile Protection Multi-device",
    "OD_CART_TRADEIN_NOTIFICATION": "Your trade-in credit has been added.",
    "OD_CART_MAIN_CART_SUB_TITLE": "Enjoy free 2-day shipping.",
    "OD_CART_DUE_MONTHLY_TITLE": "Due Monthly",
    "OD_CART_DUE_TODAY_TITLE": "Due today",
    "OD_CART_DUE_TODAY_ACTIVATION_FEE": "Activation Fee",
    "OD_CART_DUE_TODAY_UPGRADE_FEE": "Upgrade Fee",
    "OD_CART_DUE_TODAY_REMAINING_BALANCE": "Remaining balance on current device",
    "OD_CART_DUE_TODAY_EARLY_UPGRADE_BALANCE": "Early upgrade balance",
    "OD_CART_DUE_TODAY_ADDITIONAL_CHARGES": "Additional Charges",
    "DT_OD_CART_TAX_TITLE": "Taxes and Government fees",
    "OD_CART_DUE_TODAY_PAST_DUE_BALANCE": "Past due balance from bill",
    "OD_CART_EMPTY_CART_TITLE_TEXT": "Your cart is lonely",
    "OD_CART_EMPTY_CART_SUBTITLE": "Take it on a shopping spree",
    "OD_CART_EMPTY_CART_SHOP_CTA": "Shop",
    "OD_CART_MIR_TITLE": "Mail-in Rebate",
    "OD_DT_CART_PROMO_CODE_TITLE": "Have a promo code?",
    "OD_CART_PROMO_CODE": "Promo code",
    "OD_CART_PROMO_CODE_APPLY_CTA": "Apply",
    "OD_CART_ZIP_CODE_TITLE": "Please enter a new ZIP code",
    "OD_CART_SAVE_CTA": "Save",
    "OD_CART_EMPTY_YOUR_CART_TITLE": "Emtpy your cart",
    "OD_CART_EMPTY_YOUR_CART_SUBTITLE": "This will remove all the cart items",
    "DT_OD_CART_EMPTY_CART_CTA": "Clear cart",
    "OD_CART_EMPTY_CANCEL_CTA": "Cancel",
    "OD_CART_ADD_ANOTHER_PROMO_TITLE": "Add another promo code",
    "OD_CART_NO_ITEMS_IN_TITLE": "There are no items in your cart",
    "OD_CART_HEADER_TITLE": "Time to review your cart.",
    "DT_OD_CART_SHOPMORE_BTN": "Continue shopping",
    "OD_CART_CHECKOUT_TITLE": "Check out",
    "OD_CART_WANT_TO_START_OVER_TITLE": "Want to start over?",
    "OD_CART_WAIVED_UPGRADE_FEE_TITLE": "Waived Upgrade Fee",
    "OD_CART_WAIVED_ACTIVATION_FEE_TITLE": "Waived Activation Fee",
    "OD_CART_TELL_ME_MORE_TITLE": "Tell me more",
    "OD_CART_OFFER_DETAILS_TITLE": "Offer Details",
    "OD_CART_LONG_TEXT_TITLE": "long block of text",
    "OD_CART_TRADE_IN_DPP_MSG": "Once you upgrade, we'll send a prepaid shipping box so you can mail your trade-in.",
    "OD_CART_TRADE_IN_DPP_MSG_BIC": "You 'll get $ applied as $ monthly credit for 24 months starting in 2-3 bill cycles.",
    "OD_CART_PROTECTIONPAGE_TITLE": "Which protection plan would you like?",
    "OD_CART_PROTECTION_CANADD_INFO": "You can add Total Mobile protection Multi-Device on your website within 30 days of purchase",
    "OD_CART_PROTECTION_CANCHANGE_INFO": "You can change your mind whithin 30 days of activating your device",
    "OD_CART_MOREINFO_PROTECTION": "For more information see",
    "OD_CART_DPP_DETAIL_TITLE": "device protection details",
    "OD_CART_HEADER_SUBTEXT": "Enjoy free 2 day shipping",
    "OD_CART_CURRENT_PROTECTION": "Current Protection",
    "OD_CART_PROTECTION_CHANGE": "Change",
    "OD_CART_ESTD_TRADEIN_TITLE": "Estimated Trade-in credit",
    "OD_CART_WAIVED_TITLE": "Waived",
    "OD_CART_SOME_ITEMS_FROM_SAVED_CART": "We have retrieved some of the items you had previously added to your cart.",
    "OD_CART_ALL_ITEMS_FROM_SAVED_CART": "Here are the items you had previously added to your cart.",
    "OD_CART_TRADE_IN_ADDED_MSG": "Your trade-in credit has been added.",
    "OD_CART_UPGRADING": "Upgrading",
    "OD_CART_NEW_SERVICE": "New Service"
  },
  "error": {
    "OD_CART_PROMO_CODE_NOT_VALID": "Not a valid promo code",
    "OD_CART_ZIP_CODE_NOT_VALID": "Not a Valid zipcode",
    "OD_CART_POBO_NOTIFICATION": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "OD_CART_OFFER_MISS_NOTIFICATION": "Since you removed that device, you're not taking advantage of the offer."
  }
};
export default cqJson;
