const cqJson = {
  "html": {
    "OD_SECURITY_DEPOSIT_TITLE": "We need a deposit of $%price% before you can upgrade.",
    "OD_DOWN_PAYMENT_TITLE": "Your down payment has decresaed to $%price%"
  },
  "label": {
    "OD_NS_NEW_SERVICE":"New service",
    "OD_CHECKOUT_EPP_READ_AGREEMENT_TEXT": "I have read and agree to the ",
    "OD_CHECKOUT_SERVICE_ADDRESS_TEXT": "Service Address",
    "OD_CHECKOUT_EPP_TERMS_AND_CONDITIONS_LINK": "Employee Phone Program Terms and Conditions",
    "OD_CHECKOUT_EPP_TERMS_AND_CONDITIONS_REVIEW_HEADING_TEXT": "Review the Employee Phone Program Terms and Conditions",
    "OD_CHECKOUT_MAIN_SCREEN_TITLE_TEXT": "Just confirm the details and you're good to go.",
    "OD_CHECKOUT_MAIN_SCREEN_BUTTON_TEXT": " Place Order",
    "OD_CHECKOUT_MAIN_SCREEN_CART_TEXT": "Edit your Cart",
    "OD_CHECKOUT_DELIVERY_METHOD_TITLE_TEXT": "How would to like to get your new device?",
    "OD_CHECKOUT_DELIVERY_METHOD_BUTTON_TEXT": "Next",
    "OD_CHECKOUT_DUE_TODAY_DESCRIPTION_TEXT": "due today",
    "OD_CHECKOUT_DUE_TODAY_TEXT": "Due Today",
    "OD_CHECKOUT_DELIVERY_ADDRESS_TITLE_TEXT": "Here is where we will ship the device.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_TITLE_DESCRIPTION_TEXT": "We'll need a signature, and we're unable to ship to PO boxes.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_BUSINESS_ADDRESS_LABEL_TEXT": "This is a business address",
    "OD_CHECKOUT_DELIVERY_ADDRESS_BUTTON_TEXT": "Confirm",
    "OD_CHECKOUT_PAYMENT_METHOD_TITLE_TEXT": "How would you like to pay?",
    "OD_CHECKOUT_PAYMENT_METHOD_TITLE_DESCRIPTION_TEXT": "due today",
    "OD_CHECKOUT_PAYMENT_METHOD_BUTTON_TEXT": "Next",
    "OD_CHECKOUT_PAYMENT_METHOD_EDIT_PAYMENT_METHOD_TEXT": "Add or edit new payment methods",
    "OD_CHECKOUT_PAYMENT_METHOD_EDIT_PAYMENT_METHOD_TITLE_TEXT": "Fill out your card info.",
    "OD_CHECKOUT_PAYMENT_METHOD_EDIT_PAYMENT_METHOD_BUTTON_TEXT": "Continue",
    "OD_CHECKOUT_PAYMENT_METHOD_EDIT_PAYMENT_METHOD_CANCEL_TEXT": "Cancel",
    "OD_CHECKOUT_MAIN_SCREEN_VZW_TEXT": "I have read and agree to the ",
    "OD_CHECKOUT_TRADE_IN_ADDRESS_TEXT": "Trade In Address",
    "OD_CHECKOUT_MAIN_SCREEN_VZW_LINK_TEXT": "Verizon Wireless Customer Agreement.",
    "OD_CHECKOUT_MAIN_SCREEN_TRADE_IN_TEXT": "I have read and agree to the ",
    "OD_CHECKOUT_MAIN_SCREEN_TRADE_IN_LINK_TEXT": "Trade-in Agreement",
    "DT_OD_CHECKOUT_MAIN_SCREEN_DEVICE_PAYMENT_AGREEMENT_TEXT": "I have read and agree to the <a href='#/devicePaymentAgreement' className='color_black border_black onlyBottomBorder'>Device Payment Agreement</a>",
    "OD_SECURITY_DEPOSIT_TITLE": "We need a deposit of $%price% before you can upgrade.",
    "OD_SECURITY_DEPOSIT_TITLE_DESCRIPTION": "Due to the nature of your account history, we need a security deposit, which will be returned after 1 year. Your deposit will be added to your order.",
    "OD_DOWN_PAYMENT_TITLE": "Your down payment has decreased to",
    "OD_DOWN_PAYMENT_TITLE_DESCRIPTION": "Great news, your account history is so good we're lowering to upfront costs. We do have to bump up the monthly costs to $21 a month.",
    "OD_DOWN_PAYMENT_BUTTON_CTA": "View Cart",
    "OD_CHECKOUT_PAYMENT_METHOD_DESCRIPTION_TEXT": "Your billing ZIP Code has to be the same as the account ZIP Code.",
    "OD_CHECKOUT_CUSTOMER_AGREEMENT_TEXT": "Review the My Verizon Wireless Customer Agreement",
    "OD_CHECKOUT_ESTIMATED_TRADE_IN_TITLE_1_TEXT": "You'll see an estimated",
    "OD_CHECKOUT_ESTIMATED_TRADE_IN_TEXT": "Estimated trade-in credit",
    "OD_CHECKOUT_ESTIMATED_TRADE_IN_TITLE_2_TEXT": "credit within 1-2 bills.",
    "OD_CHECKOUT_ESTIMATED_TRADE_IN_DESCRIPTION_TEXT": "Once you upgrade, we'll send a prepaid shipping box so you can mail your trade-in.",
    "OD_CHECKOUT_ESTIMATED_TRADE_IN_BUTTON_TEXT": "Got it",
    "OD_CHECKOUT_FIND_STORES_ZIPCODE_TEXT": "Zip Code",
    "OD_CHECKOUT_STORE_DISTANCE_UNIT_TEXT": "mi",
    "OD_CHECKOUT_MISSING_CVC_CTA_TEXT": "Next",
    "OD_CHECKOUT_SERVICE_ADDRESS_CTA_TEXT": "Confirm",
    "OD_CHECKOUT_DELIVERY_METHOD_ISPU_DESCRIPTION_TEXT": "Check availability.",
    "OD_CHECKOUT_DELIVERY_METHOD_ISPU_LABEL_TEXT": "In-Store Pickup",
    "OD_CHECKOUT_ESTIMATED_TRADE_IN_DEVICE_CREDIT_TEXT": "Trade-in credit for this device.",
    "OD_CHECKOUT_ISPU_SEND_OPT_IN_TEXT": "Send me a text message when my order is ready.",
    "OD_CHECKOUT_ISPU_CONTACT_INFO_TITLE_TEXT": "Please provide your contact information.",
    "OD_CHECKOUT_ISPU_CONTACT_INFO_DESCRIPTION_TEXT": "We will send you an email when your order is ready.",
    "OD_CHECKOUT_STORE_DETAILS_DESCRIPTION_TEXT": "When picking up the order, you'll need to bring your photo ID and the credit card used to make this purchase.",
    "OD_CHECKOUT_STORE_DETAILS_PICK_UP_LOCATION_TEXT": "Select a new pickup location.",
    "OD_CHECKOUT_STORE_DETAILS_PICK_UP_HERE_TEXT": "Pick Up here",
    "OD_CHECKOUT_STORE_NOT_AVAILABLE_TEXT": "Not available at this store.",
    "OD_CHECKOUT_MISSING_CVC_TITLE_TEXT": "Enter your CVC",
    "OD_CHECKOUT_ISPU_NO_SEARCH_RESULTS_TITLE_TEXT": "No results",
    "OD_CHECKOUT_ISPU_NO_SEARCH_RESULTS_DESCRIPTION_TEXT": "Please try searching another location or select free 2-day shipping.",
    "OD_CHECKOUT_ISPU_FREE_SHIPPING_TEXT": "Get free 2 day shipping",
    "OD_CHECKOUT_TRADE_IN_AGREEMENT_TITLE_TEXT": "Review the Trade-in Agreement",
    "OD_CHECKOUT_PAYMENT_METHOD_BTA_TEXT": "BTA",
    "OD_CHECKOUT_BILL_TO_ACCOUNT_TEXT": "Bill to account",
    "OD_CHECKOUT_BACK_TEXT": "Back",
    "OD_CHECKOUT_USE_PAYMENT_METHOD_TEXT": "Use this payment method.",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_TEXT": "Add new payment methods",
    "OD_CHECKOUT_PAYMENT_METHOD_BILL_INCREASE_TEXT": "Your next bill will increase by",
    "OD_CHECKOUT_DELIVERY_METHOD_VERIFICATION_PROMPT": "Before you can edit your shipipng address, we need to authorize your account by sending you an authorization code.",
    "OD_CHECKOUT_ESTIMATED_TRADE_IN_ACCEPT_TEXT": "Accept",
    "OD_CHECKOUT_VIEW_CART_TEXT": "View Cart",
    "OD_CHECKOUT_ISPU_LIST_STORES_TEXT": "List Results",
    "OD_CHECKOUT_ISPU_CONFIRM_CONTACT_INFO_BTN_TEXT": "Confirm",
    "OD_CHECKOUT_ISPU_ORDER_READY_TEXT": "Orders are usually ready in about an hour.",
    "OD_CHECKOUT_ISPU_SEE_ALL_RESULTS_TEXT": "See All Results",
    "OD_CHECKOUT_ADD_PAYMENT_CONFIRM_CTA_TEXT": "Confirm",
    "OD_CHECKOUT_SHIPPING_ADDRESS_TEXT": "Shipping Address",
    "OD_CHECKOUT_DELIVERY_METHOD_TEXT": "Delivery Method",
    "OD_CHECKOUT_PAYMENT_TEXT": "Payment",
    "OD_CHECKOUT_DUE_MONTHLY_TEXT": "Due Monthly",
    "OD_CHECKOUT_DELIVERY_ADDRESS_COMPANY_NAME_TEXT": "Company Name",
    "OD_CHECKOUT_DELIVERY_ADDRESS_FIRST_NAME_TEXT": "First name",
    "OD_CHECKOUT_DELIVERY_ADDRESS_LAST_NAME_TEXT": "Last name",
    "OD_CHECKOUT_DELIVERY_ADDRESS_SHIPPING_ADDRESS_PRIMARY_TEXT": "Shipping address",
    "OD_CHECKOUT_DELIVERY_ADDRESS_SHIPPING_ADDRESS_SECONDARY_TEXT": "Shipping address 2 optional",
    "OD_CHECKOUT_DELIVERY_ADDRESS_CITY_TEXT": "City",
    "OD_CHECKOUT_DELIVERY_ADDRESS_STATE_TEXT": "State",
    "OD_CHECKOUT_DELIVERY_ADDRESS_ZIPCODE_TEXT": "Zip Code",
    "OD_CHECKOUT_DELIVERY_ADDRESS_EMAIL_TEXT": "Email address",
    "OD_CHECKOUT_DELIVERY_ADDRESS_PHONE_NUMBER_TEXT": "Telephone number",
    "OD_CHECKOUT_DELIVERY_ADDRESS_NEED_AUTHORIZATION_CODE_TEXT": "Before you can edit your shipipng address, we need to authorize your account by sending you an authorization code.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_SECURE_PIN_INELIGIBLE_TEXT": "You can't edit your address info right now. You can call us at 800.922.0204.",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_ZIPCODE_TEXT": "Card ZIP Code",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_CARD_NUMBER_TEXT": "Credit or Debit Card Number",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_EXPIRATION_MONTH_TEXT": "MM",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_EXPIRATION_YEAR_TEXT": "YYYY",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_CVC_TEXT": "CVC",
    "OD_CHECKOUT_FORM_FIELD_REQUIRED_TEXT": "Required",
    "OD_CHECKOUT_ISPU_FIND_STORES_TEXT": "Find Stores",
    "OD_CHECKOUT_ISPU_CONTACT_INFO_EMAIL_TEXT": "Email",
    "OD_CHECKOUT_ISPU_CONTACT_INFO_PHONE_NUMBER_TEXT": "Mobile Number",
    "OD_CHECKOUT_MISSING_CVC_CREDIT_CARD_VERIFICATION_TEXT": "CVC",
    "OD_CHECKOUT_INFO_NOT_FOUND_TEXT": "Not found",
    "OD_CHECKOUT_SERVICE_ADDRESS_PRIMARY_TEXT": "Service address",
    "OD_CHECKOUT_SERVICE_ADDRESS_SECONDARY_TEXT": "Service address 2 optional",
    "OD_CHECKOUT_SERVICE_CITY_TEXT": "City",
    "OD_CHECKOUT_SERVICE_STATE_TEXT": "State",
    "OD_CHECKOUT_SERVICE_ZIPCODE_TEXT": "Zip Code",
    "OD_CHECKOUT_IN_STORE_PICKUP_TEXT": "In-Store Pickup",
    "OD_CHECKOUT_IN_STORE_DESCRIPTION_TEXT": "Fast, in-store pickup. Stop by a store and get it today.",
    "OD_SECURE_PIN_INVALID_AUTH_CODE_TEXT": "This code isn't valid.",
    "OD_SECURE_PIN_ENTER_CODE_INFO_TEXT": "Now enter the code we just sent you.",
    "OD_SECURE_PIN_SEND_NEW_CODE_INFO_TEXT": "If you don't get the code after a few minutes, have us send a new one.",
    "OD_SECURE_PIN_SEND_NEW_CODE_BUTTON_TEXT": "Send a new code",
    "OD_SECURE_PIN_DONE_BUTTON_TEXT": "Done",
    "OD_SECURE_PIN_VERIFICATION_OPTIONS_UNAVAILABLE_TEXT": "Verification code texts are free. Why are some options unavailable?",
    "OD_SECURE_PIN_VERIFICATION_CODE_FREE_TEXT": "Verification code texts are free.",
    "OD_SECURE_PIN_LEARN_MORE_TEXT": "Learn More.",
    "OD_SECURE_PIN_SEND_VERIFICATION_CODE_BUTTON_TEXT": "Send",
    "OD_SECURE_PIN_GET_VERIFICATION_CODE_PROMPT_TEXT": "How would you like to get your verification code?",
    "OD_SECURE_PIN_SEND_VERIFICATION_CODE_PROMPT_TEXT": "Got it. Which device should we text the code to?",
    "OD_SECURE_PIN_TEXT_ME_TEXT": "Text me",
    "OD_SECURE_PIN_TEXT_TO_DIFFERENT_NUMBER_TEXT": "Text a different number",
    "OD_SECURE_PIN_CHOOSE_LINE_TEXT": "Choose a line from your account",
    "OD_CHECKOUT_TRADE_IN_ADDRESS_TITLE_TEXT": "Is this the right address?",
    "OD_CHECKOUT_TRADE_IN_ADDRESS_TITLE_DESCRIPTION_TEXT": "For the device you're trading in, we'll be sending you a pre-paid package. We're unable to ship to PO boxes.",
    "OD_CHECKOUT_SERVICE_ADDRESS_TITLE_TEXT": "Tell us where this device will be used.",
    "OD_CHECKOUT_SERVICE_ADDRESS_DESCRIPTION_TEXT": "This is used to calculate certain taxes and fees for your new"
  },
  "error": {
    "OD_CHECKOUT_ADDRESS_UPDATE_FAILURE_TEXT": "We cannot validate the address. Plesase verify and correct your address.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_INVALID_COMPANY_NAME_ERROR": "Please enter a valid company name.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_INVALID_FIRST_NAME_ERROR": "Please enter a valid first name.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_INVALID_LAST_NAME_ERROR": "Please enter a valid last name.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_INVALID_SHIPPING_ADDRESS_PRIMARY_ERROR": "Please Enter a valid shippingAddress.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_INVALID_SHIPPING_ADDRESS_SECONDARY_ERROR": "Please Enter a valid shippingAddress.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_INVALID_STATE_ERROR": "Please enter a state.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_INVALID_CITY_ERROR": "Please enter a city name.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_INVALID_ZIPCODE_ERROR": "Please enter a 5-digit zipcode.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_INVALID_EMAIL_ERROR": "Please enter a valid email address.",
    "OD_CHECKOUT_DELIVERY_ADDRESS_INVALID_PHONE_NUMBER_ERROR": "Please enter a valid 10 digit phone number.",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_INVALID_CARD_ERROR": "Not a valid card, please re-enter.",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_INVALID_EXPIRATION_MONTH_ERROR": "Please Enter a valid expiration date",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_INVALID_EXPIRATION_YEAR_ERROR": "Please Enter a valid expiration date",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_INVALID_CVC_ERROR": "Please enter a valid Credit Card Verification Number",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_INVALID_ZIPCODE_ERROR": "Please enter your 5-digit zip code",
    "OD_CHECKOUT_ISPU_CONTACT_INFO_INVALID_EMAIL_ERROR": "EMAIL format is incorrect",
    "OD_CHECKOUT_ISPU_CONTACT_INFO_INVALID_PHONE_NUMBER_ERROR": "Phone format is incorrect",
    "OD_CHECKOUT_MISSING_CVC_INVALID_CVC_ERROR": "Please enter a valid Credit Card Verification Number",
    "OD_CHECKOUT_SERVICE_INVALID_ADDRESS_ERROR": "Please enter a valid service address.",
    "OD_CHECKOUT_SERVICE_INVALID_CITY_ERROR": "Please enter a city.",
    "OD_CHECKOUT_SERVICE_INVALID_ZIPCODE_ERROR": "Please enter a 5-digit zipcode.",
    "OD_CHECKOUT_ADD_NEW_PAYMENT_METHOD_ZIPCODE_NOT_SAME_AS_BILLING_ERROR": "Please enter your billing zip code.",
    "OD_CHECKOUT_PAYMENT_METHOD_INVALID_PAYMENT_METHOD_ERROR": "Please use a different payment method for in-store pickup."
  }
};

export default cqJson;
