const deviceJSON = {
  "lines": [{
    "lineNumber": 1,
    "inelligibleForUpgradeNS": false,
    "commItemTrunkMtn": "",
    "commItemBranchMtn": "",
    "commItemFromCart": "false",
    "configItemId": "",
    "phones": {
      "sku2690595": {
        "id": "sku2690595",
        "colorName": "Just Black",
        "skuDisplayName": "PIXEL 2 XL JUST BLACK 64GB",
        "colorCode": "#000000",
        "isSkuChannelRestricted": false,
        "reasonCode": "",
        "capacity": "64GB",
        "storageOptionText": "",
        "earlyTerminationText": "",
        "price": [{
          "ae2DDownPrice": [],
          "planTitle": "For 24 Months with device payments; 0% APR  Retail Price $$849.99",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 99,
          "bicContractPrice": 35.41,
          "bicOfferApplied": true,
          "bicDiscountedContractPrice": 22.91,
          "bicAdditionalContractText": "24 months, 0% APR; Retail price: $549.99 was $849.99",
          "planDetail": "/mo.",
          "mailInRebateIndicator": false,
          "rebateAmountVal": 0,
          "bagxOfferedIndicator": false,
          "badgeDisplayNameVal": "Save $300. No trade-in required.",
          "badgeToolTip": "You are paying full price for the phone over 24 months, and you will see the $300 promo applied to your account as a small credit each month starting in 1-2 billing cycles. This ends when the balance is fully paid, or if you cancel or transfer your line. There is no trade-in required.",
          "badgeIconImageName": "",
          "promoType": "BIC",
          "discountAmount": 0,
          "planFullPrice": "$35.41",
          "planPrice": "$35.41"
        }, {
          "ae2DDownPrice": [],
          "planTitle": "Retail Price",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 0,
          "bicContractPrice": 0,
          "bicOfferApplied": false,
          "bicDiscountedContractPrice": 0,
          "bicAdditionalContractText": "",
          "planDetail": "Low commitment No Hassle.",
          "mailInRebateIndicator": false,
          "rebateAmountVal": 0,
          "bagxOfferedIndicator": false,
          "badgeDisplayNameVal": "",
          "badgeToolTip": "",
          "badgeIconImageName": "",
          "promoType": "",
          "discountAmount": 0,
          "planFullPrice": "$849.99",
          "planPrice": "$849.99"
        }],
        "fullPrice": [{
          "planTitle": "Monthly Device Payment",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 99,
          "planDetail": "/mo.",
          "planPrice": "$35.41"
        }, {
          "planTitle": "Retail Price",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 0,
          "planDetail": "Low commitment No Hassle.",
          "planPrice": "$849.99"
        }],
        "waveFirstMonthPay": "",
        "addToCartQty": "0",
        "compatibleWithPlan": "false",
        "ATCST": "submitIconicDevice",
        "ATCClass": "redButton buttonIndent",
        "MAST": "false",
        "CIL": "0",
        "IRURL": "https://preorder.verizonwireless.com/iconic/",
        "BAGX": "false",
        "OOS": true,
        "inventoryStatus": 1000,
        "inventoryAvailabilityDate": "",
        "freeShipping": "freeShippingHTML",
        "bagxGetPhone": "",
        "badges": ["lteBadge", "onlineExclusiveBadge", "globalReadyBadge"],
        "pricingBreakOut": "NA",
        "spinset": "",
        "imageset": "",
        "video": "",
        "isCPODevice": "",
        "associatedDeviceId": "",
        "storePickupEligible": true,
        "availableAtSelectedStore": "",
        "storeSelected": "",
        "pdpMarketingBanner": "https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Blk?fmt=jpg&amp;bgc=f6f6f6",
        "maxQuantity": "5",
        "isTabletOnlyAvailable": "false"
      },
      "sku2690601": {
        "id": "sku2690601",
        "colorName": "Black and White",
        "skuDisplayName": "PIXEL 2 XL BLACK AND WHITE 64GB",
        "colorCode": "#F5F5F5",
        "isSkuChannelRestricted": false,
        "reasonCode": "",
        "capacity": "64GB",
        "storageOptionText": "",
        "earlyTerminationText": "",
        "price": [{
          "ae2DDownPrice": [],
          "planTitle": "For 24 Months with device payments; 0% APR  Retail Price $$849.99",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 99,
          "bicContractPrice": 35.41,
          "bicOfferApplied": true,
          "bicDiscountedContractPrice": 22.91,
          "bicAdditionalContractText": "24 months, 0% APR; Retail price: $549.99 was $849.99",
          "planDetail": "/mo.",
          "mailInRebateIndicator": false,
          "rebateAmountVal": 0,
          "bagxOfferedIndicator": false,
          "badgeDisplayNameVal": "Save $300. No trade-in required.",
          "badgeToolTip": "You are paying full price for the phone over 24 months, and you will see the $300 promo applied to your account as a small credit each month starting in 1-2 billing cycles. This ends when the balance is fully paid, or if you cancel or transfer your line. There is no trade-in required.",
          "badgeIconImageName": "",
          "promoType": "BIC",
          "discountAmount": 0,
          "planFullPrice": "$35.41",
          "planPrice": "$35.41"
        }, {
          "ae2DDownPrice": [],
          "planTitle": "Retail Price",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 0,
          "bicContractPrice": 0,
          "bicOfferApplied": false,
          "bicDiscountedContractPrice": 0,
          "bicAdditionalContractText": "",
          "planDetail": "Low commitment No Hassle.",
          "mailInRebateIndicator": false,
          "rebateAmountVal": 0,
          "bagxOfferedIndicator": false,
          "badgeDisplayNameVal": "",
          "badgeToolTip": "",
          "badgeIconImageName": "",
          "promoType": "",
          "discountAmount": 0,
          "planFullPrice": "$849.99",
          "planPrice": "$849.99"
        }],
        "fullPrice": [{
          "planTitle": "Monthly Device Payment",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 99,
          "planDetail": "/mo.",
          "planPrice": "$35.41"
        }, {
          "planTitle": "Retail Price",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 0,
          "planDetail": "Low commitment No Hassle.",
          "planPrice": "$849.99"
        }],
        "waveFirstMonthPay": "",
        "addToCartQty": "0",
        "compatibleWithPlan": "false",
        "ATCST": "submitIconicDevice",
        "ATCClass": "redButton buttonIndent",
        "MAST": "false",
        "CIL": "0",
        "IRURL": "https://preorder.verizonwireless.com/iconic/",
        "BAGX": "false",
        "OOS": true,
        "inventoryStatus": 1000,
        "inventoryAvailabilityDate": "",
        "freeShipping": "freeShippingHTML",
        "bagxGetPhone": "",
        "badges": ["lteBadge", "onlineExclusiveBadge", "globalReadyBadge"],
        "pricingBreakOut": "NA",
        "spinset": "",
        "imageset": "",
        "video": "",
        "isCPODevice": "",
        "associatedDeviceId": "",
        "storePickupEligible": true,
        "availableAtSelectedStore": "",
        "storeSelected": "",
        "pdpMarketingBanner": "https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Wht?fmt=jpg&amp;bgc=f6f6f6",
        "maxQuantity": "5",
        "isTabletOnlyAvailable": "false"
      },
      "sku2690592": {
        "id": "sku2690592",
        "colorName": "Just Black",
        "skuDisplayName": "PIXEL 2 XL JUST BLACK 128GB",
        "colorCode": "#000000",
        "isSkuChannelRestricted": false,
        "reasonCode": "",
        "capacity": "128GB",
        "storageOptionText": "",
        "earlyTerminationText": "",
        "price": [{
          "ae2DDownPrice": [],
          "planTitle": "For 24 Months with device payments; 0% APR  Retail Price $$949.99",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 99,
          "bicContractPrice": 39.58,
          "bicOfferApplied": true,
          "bicDiscountedContractPrice": 27.08,
          "bicAdditionalContractText": "24 months, 0% APR; Retail price: $649.99 was $949.99",
          "planDetail": "/mo.",
          "mailInRebateIndicator": false,
          "rebateAmountVal": 0,
          "bagxOfferedIndicator": false,
          "badgeDisplayNameVal": "Save $300. No trade-in required.",
          "badgeToolTip": "You are paying full price for the phone over 24 months, and you will see the $300 promo applied to your account as a small credit each month starting in 1-2 billing cycles. This ends when the balance is fully paid, or if you cancel or transfer your line. There is no trade-in required.",
          "badgeIconImageName": "",
          "promoType": "BIC",
          "discountAmount": 0,
          "planFullPrice": "$39.58",
          "planPrice": "$39.58"
        }, {
          "ae2DDownPrice": [],
          "planTitle": "Retail Price",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 0,
          "bicContractPrice": 0,
          "bicOfferApplied": false,
          "bicDiscountedContractPrice": 0,
          "bicAdditionalContractText": "",
          "planDetail": "Low commitment No Hassle.",
          "mailInRebateIndicator": false,
          "rebateAmountVal": 0,
          "bagxOfferedIndicator": false,
          "badgeDisplayNameVal": "",
          "badgeToolTip": "",
          "badgeIconImageName": "",
          "promoType": "",
          "discountAmount": 0,
          "planFullPrice": "$949.99",
          "planPrice": "$949.99"
        }],
        "fullPrice": [{
          "planTitle": "Monthly Device Payment",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 99,
          "planDetail": "/mo.",
          "planPrice": "$39.58"
        }, {
          "planTitle": "Retail Price",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 0,
          "planDetail": "Low commitment No Hassle.",
          "planPrice": "$949.99"
        }],
        "waveFirstMonthPay": "",
        "addToCartQty": "0",
        "compatibleWithPlan": "false",
        "ATCST": "submitIconicDevice",
        "ATCClass": "redButton buttonIndent",
        "MAST": "false",
        "CIL": "0",
        "IRURL": "https://preorder.verizonwireless.com/iconic/",
        "BAGX": "false",
        "OOS": true,
        "inventoryStatus": 1000,
        "inventoryAvailabilityDate": "",
        "freeShipping": "freeShippingHTML",
        "bagxGetPhone": "",
        "badges": ["lteBadge", "onlineExclusiveBadge", "globalReadyBadge"],
        "pricingBreakOut": "NA",
        "spinset": "",
        "imageset": "",
        "video": "",
        "isCPODevice": "",
        "associatedDeviceId": "",
        "storePickupEligible": true,
        "availableAtSelectedStore": "",
        "storeSelected": "",
        "pdpMarketingBanner": "https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Blk?fmt=jpg&amp;bgc=f6f6f6",
        "maxQuantity": "5",
        "isTabletOnlyAvailable": "false"
      },
      "sku2690598": {
        "id": "sku2690598",
        "colorName": "Black and White",
        "skuDisplayName": "PIXEL 2 XL BLACK AND WHITE 128GB",
        "colorCode": "#F5F5F5",
        "isSkuChannelRestricted": false,
        "reasonCode": "",
        "capacity": "128GB",
        "storageOptionText": "",
        "earlyTerminationText": "",
        "price": [{
          "ae2DDownPrice": [],
          "planTitle": "For 24 Months with device payments; 0% APR  Retail Price $$949.99",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 99,
          "bicContractPrice": 39.58,
          "bicOfferApplied": true,
          "bicDiscountedContractPrice": 27.08,
          "bicAdditionalContractText": "24 months, 0% APR; Retail price: $649.99 was $949.99",
          "planDetail": "/mo.",
          "mailInRebateIndicator": false,
          "rebateAmountVal": 0,
          "bagxOfferedIndicator": false,
          "badgeDisplayNameVal": "Save $300. No trade-in required.",
          "badgeToolTip": "You are paying full price for the phone over 24 months, and you will see the $300 promo applied to your account as a small credit each month starting in 1-2 billing cycles. This ends when the balance is fully paid, or if you cancel or transfer your line. There is no trade-in required.",
          "badgeIconImageName": "",
          "promoType": "BIC",
          "discountAmount": 0,
          "planFullPrice": "$39.58",
          "planPrice": "$39.58"
        }, {
          "ae2DDownPrice": [],
          "planTitle": "Retail Price",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 0,
          "bicContractPrice": 0,
          "bicOfferApplied": false,
          "bicDiscountedContractPrice": 0,
          "bicAdditionalContractText": "",
          "planDetail": "Low commitment No Hassle.",
          "mailInRebateIndicator": false,
          "rebateAmountVal": 0,
          "bagxOfferedIndicator": false,
          "badgeDisplayNameVal": "",
          "badgeToolTip": "",
          "badgeIconImageName": "",
          "promoType": "",
          "discountAmount": 0,
          "planFullPrice": "$949.99",
          "planPrice": "$949.99"
        }],
        "fullPrice": [{
          "planTitle": "Monthly Device Payment",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 99,
          "planDetail": "/mo.",
          "planPrice": "$39.58"
        }, {
          "planTitle": "Retail Price",
          "applicableUpgradeFee": 0,
          "applicableActivationFee": 0,
          "planName": 0,
          "planDetail": "Low commitment No Hassle.",
          "planPrice": "$949.99"
        }],
        "waveFirstMonthPay": "",
        "addToCartQty": "0",
        "compatibleWithPlan": "false",
        "ATCST": "submitIconicDevice",
        "ATCClass": "redButton buttonIndent",
        "MAST": "false",
        "CIL": "0",
        "IRURL": "https://preorder.verizonwireless.com/iconic/",
        "BAGX": "false",
        "OOS": true,
        "inventoryStatus": 1000,
        "inventoryAvailabilityDate": "",
        "freeShipping": "freeShippingHTML",
        "bagxGetPhone": "",
        "badges": ["lteBadge", "onlineExclusiveBadge", "globalReadyBadge"],
        "pricingBreakOut": "NA",
        "spinset": "",
        "imageset": "",
        "video": "",
        "isCPODevice": "",
        "associatedDeviceId": "",
        "storePickupEligible": true,
        "availableAtSelectedStore": "",
        "storeSelected": "",
        "pdpMarketingBanner": "https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Wht?fmt=jpg&amp;bgc=f6f6f6",
        "maxQuantity": "5",
        "isTabletOnlyAvailable": "false"
      }
    },
    "options": {
      "colorName": "",
      "colorCode": "",
      "capacity": "128GB",
      "sku": "$",
      "isCPODevice": "false",
      "contractTerm": "24",
      "bundle": "false"
    },
    "info": {
      "defaultPhoneId": "",
      "phoneId": "",
      "ATCST": "submitIconicDevice",
      "MAST": "false",
      "CIL": "0",
      "IRURL": "https://preorder.verizonwireless.com/iconic/",
      "BAGX": "false",
      "bagxGetPhone": "",
      "compatibleWithPlan": "false",
      "waveFirstMonthPay": "0.0",
      "virtualBundleSelected": "false",
      "isCapacityAvail": ""
    },
    "promos": {},
    "motoMakerConfig": {
      "motoMakerDevice": false,
      "partnerId": "",
      "productId": "",
      "motomakerToken": "",
      "designRefresh": false,
      "displayTotalPrice": false,
      "enableMotomakerSwitch": false,
      "designSaved": false,
      "motorolaWid": "",
      "selectedOptions": "",
      "motorolaJSServerURL": ""
    }
  }],
  "lineShareMtns": [{
    "trunkMtn": "2014520680",
    "mldTrunkMtn": "",
    "deviceName": "IPHONE 7 ROSE GOLD 32GB",
    "hostFromCart": false,
    "volteEnabled": true,
    "appleVolteEnabled": true,
    "numberShareMaxLimitReached": false,
    "branchMtnCount": 0,
    "connectedBranchMtnCount": 0,
    "humBranchMtnCount": 0,
    "branchMtns": []
  }, {
    "trunkMtn": "9733628511",
    "mldTrunkMtn": "",
    "deviceName": "IPHONE X SILVER 64GB VZ",
    "hostFromCart": false,
    "volteEnabled": true,
    "appleVolteEnabled": true,
    "numberShareMaxLimitReached": false,
    "branchMtnCount": 0,
    "connectedBranchMtnCount": 0,
    "humBranchMtnCount": 0,
    "branchMtns": []
  }]
};


export default deviceJSON;
