const cartJSON = {
  "statusCode": "00",
  "output": {
    "orderId": "SDC657a156c4c169d5115f8a399d18e826d{ss1}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "accGuestCheckoutEnabled": true,
    "dueTodayPOBOHeader": null,
    "items": null,
    "accessories": [{
      "scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/popsocket-rose-gold-metallic-diamond-ps-101636-iset?$acc-med$",
      "name": "PopSockets - Rose Gold Metallic Diamond",
      "quantity": 1,
      "commerceItemId": "SDC657a156c4c169d5115f8a399d18e826d{ss1}_accessory_1",
      "color": "Rose Gold",
      "size": null,
      "inventoryStatus": "1000",
      "inventoryAvailableDate": null,
      "prodId": "acc8760188",
      "skuId": "sku2690343",
      "sorId": "PS-101636",
      "hasEcpdDiscount": false,
      "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/popsocket-rose-gold-metallic-diamond-ps-101636-iset?$acc-med$",
      "hasBogoDiscount": false,
      "price": 14.99,
      "wasPrice": 14.99,
      "discounted": false,
      "discountPercentage": 0.0,
      "discountPrice": 0.0,
      "editAccessoryUrl": "/od/cust/auth/accessoryDetails/?accProdId=acc8760188&action=edit&accCommerceId=SDC657a156c4c169d5115f8a399d18e826d{ss1}_accessory_1&contractTerm=0&deviceSkuId=null#/chooseColor/skuId=sku2690343",
      "hideEditLink": false,
      "standaloneAccessory": true
    }],
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "0.00",
      "cityStateString": null,
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "14.99",
    "totalDueMonthly": "0.00",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": null,
    "tradeInPromoDetails": null,
    "promotionList": null,
    "cartMessages": {
      "cartReadyforCheckout": true,
      "message": "",
      "code": ""
    },
    "cartItemCount": 1,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": null,
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": true,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": null,
    "mainCartNextDayShippingMessage": null,
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": null,
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "lonelyCartSubMessage": null,
    "checkoutButtonURL": "/od/cust/auth/checkout/initiateCheckout",
    "tradeInUrl": null,
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/od/cust/auth/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "0.00",
    "itemOnJaxPlan": false,
    "anyLineFreeSPO": null,
    "paypalEnabled": true,
    "paypalApi": "/od/cust/auth/checkout/paypal/cmpilookup?triggerFrom=PAYMENT",
    "aalUrl": "/od/cust/auth/shop?flow=AAL",
    "eupUrl": "/od/cust/auth/shop?flow=EUP",
    "rawSubTotalDueToday": "14.99",
    "overallDueMonthly": "0.00",
    "additionalCharges": [],
    "accessoryGWURL": null,
    "accessoryPDPURL": null,
    "removeTradeInURL": null,
    "masterpassEnabled": false,
    "targetter": {
      "freeShippingText": "Free Shipping or In-Store Pickup",
      "freeShippingDesc": "Free shipping \n Free 2-day shipping when you order online M-F by 8PM EST, Sat by 2PM EST (excluding holidays), will deliver in two business days within the U.S. only (excluding AK & HI). 2-day orders placed after 2PM EST on Sat will deliver by Wednesday. Overnight shipping to destinations within the U.S. (excluding AK & HI) is generally available for orders placed M-F until 11PM EST, excluding holidays. Orders that contain a pre-order or backorder will ship via 2-day shipping on or prior to the committed date. Subject to credit authorization, verification and inventory availability.",
      "nextDayText": "Want it tomorrow? Order by 11PM ET w/Next Day Shipping. Pre-order devices excl'd",
      "nextDayDesc": "Depending on inventory availability for destinations within the US (excluding AK, HI) for orders placed M-F (excluding holidays). Next Day Shipping is not available for devices in pre-order status. Pre-order devices will ship as inventory becomes available",
      "contentText": "Keep your content.",
      "contentDesc": "Don't worry, we've got you covered. We'll make sure all of your pictures, contacts and content transfer from one phone to the other without issue.",
      "returnPolicyText": "14 day return policy",
      "returnPolicyDesc": "You may return or exchange wireless devices and accessories purchased from Verizon Wireless within 14 days of purchase. A restocking fee of $35 applies to any return or exchange of a wireless device (excluding Hawaii)."
    },
    "overallDiscountedAmount": "0.00",
    "ecpdDueTodayDiscountedAmount": "0.00",
    "ecpdDueMonthlySavings": "0.00",
    "devicesURL": null,
    "cartURL": "/od/cust/auth/cart/getCartDetails?format=json",
    "byodUrl": "/od/cust/auth/shop?flow=NSO",
    "masterpassConfigInfo": {
      "checkoutId": "900f7d9b6a974cee9e0cad74fe8c1c20",
      "allowedCardTypes": ["master", "amex", "diners", "discover", "jcb",
        "maestro", "visa"
      ],
      "shippingLocationProfile": "US",
      "amount": "14.99",
      "cartId": "SDC657a156c4c169d5115f8a399d18e826d{ss1}",
      "currency": "USD",
      "suppress3Ds": false,
      "callbackUrl": "http://wga0022alditdvb.uswin.ad.vzwcorp.com/od/cust/auth/checkout/masterpass/paymentData"
    },
    "accessoryShopURL": "/accessories",
    "bicOfferMessage": null,
    "cartMFCompatible": true,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": "",
      "cartIncompleteMessage": null,
      "orderId": "SDC657a156c4c169d5115f8a399d18e826d{ss1}"
    },
    "cartEdited": false,
    "iconicFlow": false,
    "plans": null,
    "removePromoCodeURL": "/od/cust/cart/removePromoCode",
    "applyPromoCodeURL": "/od/cust/cart/applyPromoCode",
    "clearCartURL": "/od/cust/cart/clearCart",
    "addOrUpdateDeviceURL": "/od/cust/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/od/cust/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/od/cust/cart/changeZipCode/",
    "addOrUpdateFeatureURL": "/od/cust/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/od/cust/checkout/initiateCheckout",
    "guestCheckoutSignInURL": "/od/cust/checkout/sign_in",
    "accountMember": false,
    "tmpMdOpted": false,
    "tmpMd": null,
    "frontEndPersonalization": null,
    "allowAAL": true,
    "allowEUP": true,
    "authenticated": false,
    "splitShipment": false
  },
  "errorMap": null,
  "statusMessage": ""
};

export default cartJSON;
