const gwJSON = {
		"output": {
			"results": [{
				"brand": "Apple",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "iPhone&reg; SE",
				"productId": "dev6000008",
				"originalPrice": null,
				"price": "16.66",
				"fullRetailPrice": "399.99",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iPhoneSE_Gld?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iPhoneSE_Gld?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6000008&contractTerm=99&deviceSkuId=sku1960018"
			}, {
				"brand": "Samsung",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Galaxy S8",
				"productId": "dev7480001",
				"originalPrice": null,
				"price": "31.50",
				"fullRetailPrice": "756.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Silver?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Silver?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev7480001&contractTerm=99&deviceSkuId=sku2360001"
			}, {
				"brand": "Samsung",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Galaxy S8+",
				"productId": "dev7480002",
				"originalPrice": null,
				"price": "35.00",
				"fullRetailPrice": "840.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Plus_Black?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Plus_Black?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev7480002&contractTerm=99&deviceSkuId=sku2360005"
			}, {
				"brand": "Google",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Pixel, Phone by Google",
				"productId": "dev6720118",
				"originalPrice": null,
				"price": "27.08",
				"fullRetailPrice": "649.99",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Sailfish_Blue?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Sailfish_Blue?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6720118&contractTerm=99&deviceSkuId=sku2170525"
			}, {
				"brand": "Google",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Pixel XL, Phone by Google",
				"productId": "dev6720119",
				"originalPrice": null,
				"price": "32.08",
				"fullRetailPrice": "769.99",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver?$device-lg$",
				"offerImage": null,
				"offerDescription": "Buy one, get one 50% off.",
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6720119&contractTerm=99&deviceSkuId=sku2170532"
			}, {
				"brand": "Apple",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "iPhone&reg; 7",
				"productId": "dev6640012",
				"originalPrice": null,
				"price": "27.08",
				"fullRetailPrice": "649.99",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-svr?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-svr?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6640012&contractTerm=99&deviceSkuId=sku2150055"
			}, {
				"brand": "Apple",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "iPhone&reg; 7 Plus",
				"productId": "dev6640013",
				"originalPrice": null,
				"price": "32.08",
				"fullRetailPrice": "769.99",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-red?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-red?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6640013&contractTerm=99&deviceSkuId=sku2350185"
			}, {
				"brand": "Apple",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "iPhone&reg; 6s Plus",
				"productId": "dev5160003",
				"originalPrice": null,
				"price": "27.08",
				"fullRetailPrice": "649.99",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-plus-rsgld-front?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-plus-rsgld-front?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev5160003&contractTerm=99&deviceSkuId=sku1740060"
			}, {
				"brand": "Apple",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "iPhone&reg; 6s",
				"productId": "dev5160002",
				"originalPrice": null,
				"price": "22.91",
				"fullRetailPrice": "549.99",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-spgry-front?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-spgry-front?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev5160002&contractTerm=99&deviceSkuId=sku1740042"
			}, {
				"brand": "Motorola",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "DROID TURBO 2",
				"productId": "dev5440238",
				"originalPrice": null,
				"price": "22.00",
				"fullRetailPrice": "528.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Droid_Bounce_Black_Without?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Droid_Bounce_Black_Without?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev5440238&contractTerm=99&deviceSkuId=sku1810218"
			}, {
				"brand": "Microsoft",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Lumia 735",
				"productId": "dev4800004",
				"originalPrice": null,
				"price": "5.00",
				"fullRetailPrice": "120.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Nokia_Lumia_735?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Nokia_Lumia_735?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev4800004&contractTerm=99&deviceSkuId=sku1650105"
			}, {
				"brand": "Samsung",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Galaxy S7",
				"productId": "dev5800066",
				"originalPrice": null,
				"price": "24.00",
				"fullRetailPrice": "576.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Hero_Black?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Hero_Black?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev5800066&contractTerm=99&deviceSkuId=sku1900310"
			}, {
				"brand": "LG",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "V20",
				"productId": "dev6800082",
				"originalPrice": null,
				"price": "24.00",
				"fullRetailPrice": "576.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_V20_Titanium?$device-lg$",
				"offerImage": null,
				"offerDescription": "Buy one, get one 50% off.",
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/LG_V20_Titanium?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6800082&contractTerm=99&deviceSkuId=sku2190286"
			}, {
				"brand": "LG",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "K4 LTE",
				"productId": "dev5960008",
				"originalPrice": null,
				"price": "0.00",
				"fullRetailPrice": "0.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_K4?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/LG_K4?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev5960008&contractTerm=99&deviceSkuId=sku1940053"
			}, {
				"brand": "Motorola",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Moto Z Force Droid",
				"productId": "dev6360191",
				"originalPrice": null,
				"price": "30.00",
				"fullRetailPrice": "720.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_JavaM_Black?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_JavaM_Black?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6360191&contractTerm=99&deviceSkuId=sku2080197"
			}, {
				"brand": "LG",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "G5",
				"productId": "dev5840005",
				"originalPrice": null,
				"price": "20.00",
				"fullRetailPrice": "480.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_G5_Titanium?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/LG_G5_Titanium?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev5840005&contractTerm=99&deviceSkuId=sku1910025"
			}, {
				"brand": "Motorola",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Moto Z Droid",
				"productId": "dev6360190",
				"originalPrice": null,
				"price": "26.00",
				"fullRetailPrice": "624.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Java_White_Gold?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Java_White_Gold?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6360190&contractTerm=99&deviceSkuId=sku2080196"
			}, {
				"brand": "HTC",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "10&trade;",
				"productId": "dev6080072",
				"originalPrice": null,
				"price": "27.00",
				"fullRetailPrice": "648.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/HTC_10?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/HTC_10?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6080072&contractTerm=99&deviceSkuId=sku1980150"
			}, {
				"brand": "Samsung",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Galaxy J3 V",
				"productId": "dev6360181",
				"originalPrice": null,
				"price": "7.00",
				"fullRetailPrice": "168.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_J3_Postpaid?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_J3_Postpaid?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6360181&contractTerm=99&deviceSkuId=sku2080170"
			}, {
				"brand": "HTC",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Desire&reg; 530",
				"productId": "dev6440049",
				"originalPrice": null,
				"price": "6.00",
				"fullRetailPrice": "144.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/HTC_Desire_530_Blue?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/HTC_Desire_530_Blue?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6440049&contractTerm=99&deviceSkuId=sku2100180"
			}, {
				"brand": "Samsung",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Galaxy S&reg; 5 (Certified Pre-Owned)",
				"productId": "dev3240055",
				"originalPrice": null,
				"price": "12.00",
				"fullRetailPrice": "288.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S5_Black?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S5_Black?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev3240055&contractTerm=99&deviceSkuId=sku1860260"
			}, {
				"brand": "Samsung",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Galaxy S&reg; 4 (Certified Pre-Owned)",
				"productId": "dev3080113",
				"originalPrice": null,
				"price": "10.00",
				"fullRetailPrice": "240.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/SamsungGalaxyS4_themill?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/SamsungGalaxyS4_themill?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev3080113&contractTerm=99&deviceSkuId=sku1860261"
			}, {
				"brand": "Samsung",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Galaxy J7 V",
				"productId": "dev7400030",
				"originalPrice": null,
				"price": "10.00",
				"fullRetailPrice": "0.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Sam_J7_V_Silver?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Sam_J7_V_Silver?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev7400030&contractTerm=99&deviceSkuId=sku2340203"
			}, {
				"brand": "Apple",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "iPhone&reg; 6s (Certified Pre-Owned)",
				"productId": "dev7320062",
				"originalPrice": null,
				"price": "17.91",
				"fullRetailPrice": "0.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-gld-front?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-gld-front?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev7320062&contractTerm=99&deviceSkuId=sku2310390"
			}, {
				"brand": "LG",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "G6&trade;",
				"productId": "dev7320059",
				"originalPrice": null,
				"price": "28.00",
				"fullRetailPrice": "0.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_G6_Black?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/LG_G6_Black?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev7320059&contractTerm=99&deviceSkuId=sku2320124"
			}, {
				"brand": "Samsung",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Galaxy S&reg; 5",
				"productId": "dev2080010",
				"originalPrice": null,
				"price": "0.00",
				"fullRetailPrice": "0.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S5_Black?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S5_Black?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev2080010&contractTerm=99&deviceSkuId=sku900083"
			}, {
				"brand": "LG",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Stylo 2 V",
				"productId": "dev6760013",
				"originalPrice": null,
				"price": "0.00",
				"fullRetailPrice": "0.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_Stylo_2V?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/LG_Stylo_2V?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6760013&contractTerm=99&deviceSkuId=sku2180004"
			}, {
				"brand": "Samsung",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Galaxy S7 edge",
				"productId": "dev5800067",
				"originalPrice": null,
				"price": "29.00",
				"fullRetailPrice": "0.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_S7_Edge_CoralBlue?$device-lg$",
				"offerImage": null,
				"offerDescription": "Buy one, get one 50% off.",
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_S7_Edge_CoralBlue?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev5800067&contractTerm=99&deviceSkuId=sku2230093"
			}, {
				"brand": "Motorola",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "Moto Z Play Droid",
				"productId": "dev6560041",
				"originalPrice": null,
				"price": "0.00",
				"fullRetailPrice": "0.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Z_Play_Droid_Edition_Black?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Z_Play_Droid_Edition_Black?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6560041&contractTerm=99&deviceSkuId=sku2130138"
			}, {
				"brand": "Kyocera",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "DuraForce PRO with Sapphire Shield. This is a test to have 70 characters in display name",
				"productId": "dev6760021",
				"originalPrice": null,
				"price": "17.00",
				"fullRetailPrice": "0.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Kyocera_DuraForce_Pro?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/Kyocera_DuraForce_Pro?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev6760021&contractTerm=99&deviceSkuId=sku2260136"
			}, {
				"brand": "LG",
				"priceText": "24 months, 0% APR",
				"priceDetail": "/mo",
				"displayName": "K20 V",
				"productId": "dev7400003",
				"originalPrice": null,
				"price": "7.00",
				"fullRetailPrice": "0.00",
				"fullRetailPriceText": "retail",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_K20V?$device-lg$",
				"offerImage": null,
				"offerDescription": null,
				"url": "https://ss7.vzw.com/is/image/VerizonWireless/LG_K20V?$device-lg$",
				"pdpRedirectUrl": "/digital/device/deviceOptions/?deviceProdId=dev7400003&contractTerm=99&deviceSkuId=sku2340115"
			}],
			"priceOptions": [{
				"displayName": "Monthly Payment",
				"url": null,
				"description": "Pay in 24 monthly installments, interest-free.",
				"selected": true,
				"contractTerm": "99"
			}, {
				"displayName": "Retail Price",
				"url": null,
				"description": "Total price will be due today.",
				"selected": false,
				"contractTerm": "0"
			}],
			"filters": [{
				"filterOptions": [{
					"displayName": "All",
					"url": "/digital/smartphones/",
					"selected": true
				}, {
					"displayName": "Apple",
					"url": "/digital/smartphones/?flow=EUP&selectedMTN=&selectionQueryString=N%3D4294824674",
					"selected": false
				}, {
					"displayName": "Samsung",
					"url": "/digital/smartphones/?flow=EUP&selectedMTN=&selectionQueryString=N%3D4294825737",
					"selected": false
				}, {
					"displayName": "Android",
					"url": "/digital/smartphones/?flow=EUP&selectedMTN=&selectionQueryString=N%3D4294820610",
					"selected": false
				}, {
					"displayName": "Motorola",
					"url": "/digital/smartphones/?flow=EUP&selectedMTN=&selectionQueryString=N%3D4294825432",
					"selected": false
				}],
				"filterName": "Brand"
			}],
			"gridWallUrl": "/digital/smartphones/",
			"title": "Smartphones"
		},
		"ErrorMap": null,
		"statusMessage": "Service completed Successfully.",
		"statusCode": "00"
	};
export default gwJSON;
