const cqJSON= {
  "html": {
  "OD_DT_MDN_EARLY_TWO_YEAR_AGREEMENT_INFO": "<div class=&quot;pad24 textAlignCenter color_666&quot;>",
    "OD_DT_MDN_DPP_QUALIFICATIONS_DESCRIPTION": "&lt;li class=&quot;margin24 noSideMargin&quot;&gt; The device can be turned on and off.&lt;/li&gt; &lt;li class=&quot;margin24 noSideMargin&quot;&gt; The screen is free of cracks and functionning correctly. &lt;/li&gt; &lt;li class=&quot;margin24 noSideMargin&quot;&gt; The phone and connecting ports are free of visible corrosion and water damage. &lt;/li&gt; &lt;li class=&quot;margin24 noSideMargin&quot;&gt; The battery is free of physical damage (examples of physical damage include: Too hot to touch, swelling, or rupture of phone casing). &lt;/li&gt; &lt;li class=&quot;margin24 noSideMargin&quot;&gt; The phone and charging port are free of cracks, dents and not missing pieces/chunks. &lt;/li&gt; &lt;li class=&quot;margin24 noSideMargin&quot;&gt; The activation lock is turned off (Example: Find My iPhone). &lt;/li&gt;",
    "OD_DT_MDN_DPP_APPRAISAL_DESCRIPTION": "&lt;p class=&quot;margin12 &quot;&gt; After you complete your order, we'll send you a prepaid shipping box that you can use to mail us your old device after receiving your new device upgrade.&lt;/p&gt;&lt;p class=&quot;margin12&quot;&gt;Please note that if the device does not arrive in the condition described,  a charge will be added to your next bill.&lt;/p&gt;"
},
  "label": {
  "OD_DT_MDN_FIND_MY_DEVICE_CTA": "Next",
    "OD_DT_MDN_FIND_MY_DEVICE_DESCRIPTION": "Instructions to turn off Find My iPhone will be in the return shipping box. If you don't turn it off, you won't be able to activate your new device.",
    "OD_DT_MDN_FIND_MY_DEVICE_TITLE": "You need to turn off Find My iPhone on your old device.",
    "OD_DT_MDN_INELIGIBLE_YES_CTA": "Yes",
    "OD_DT_MDN_INELIGIBLE_NO_CTA": "No",
    "OD_DT_MDN_END_DATE_LABEL": "End Date",
    "OD_DT_MDN_NO_INTENT_MAIN_TITLE": "Would you like to upgrade or add a new device?",
    "OD_DT_MDN_EUP_INTENT_MAIN_TITLE": "Would you like to upgrade another line?",
    "OD_DT_MDN_AAL_INTENT_MAIN_TITLE": "Would you like to add another line?",
    "OD_DT_MDN_UPGRADE_CTA": "Upgrade",
    "OD_DT_MDN_DPP_AGREEMENT_UPGRADE_READY": "Upgrade Ready",
    "OD_DT_MDN_DPP_AGREEMENT_UPGRADE_CTA": "Upgrade Now",
    "OD_DT_MDN_DPP_AGREEMENT_VIEW_AGREEMENT": "View device payment agreement",
    "OD_DT_MDN_DPP_APPRAISAL_TITLE": "Tell us about your device.",
    "OD_DT_MDN_DPP_APPRAISAL_SUBTITLE": "Please confirm the following to continue:",
    "OD_DT_MDN_DPP_QUALIFICATIONS_TITLE": "Requirements for trade-in.",
    "OD_DT_MDN_DPP_APPRAISAL_NEXT_CTA": "Next",
    "OD_DT_MDN_DPP_QUALIFICATIONS_SUBTITLE": "A device is considered to be in good working condition if  it meets these qualification:",
    "OD_DT_MDN_DPP_APPRAISAL_QUALIFICATIONS_TEXT": "The device is in",
    "OD_DT_MDN_DPP_APPRAISAL_QUALIFICATIONS_LINK_TEXT": "good working condition.",
    "OD_DT_MDN_ADDED_TO_THE_CART_TEXT": "Line is already added to the cart.",
    "OD_DT_MDN_ACCT_LINE_LIMIT_CONTENT_HEADER": "You have reached the maximum number of devices for your account.",
    "OD_DT_MDN_ACCT_LINE_LIMIT_CONTENT": "Consider upgrading current device or creating an additional Verizon account.",
    "OD_DT_MDN_ACCT_LINE_LIMIT_VIEW_DEVICES_BUTTON_TEXT": "View devices",
    "OD_DT_MDN_CART_LINE_LIMIT_CONTENT_HEADER": "You've hit the maximum number of devices for this transaction.",
    "OD_DT_MDN_CART_LINE_LIMIT_CONTENT": "If you still want to add this device, you can empty your cart, replace a device in your cart or finish this purchase as a separate transaction.",
    "OD_DT_MDN_CART_LINE_LIMIT_VIEW_CART_BUTTON_TEXT": "View cart",
    "OD_DT_MDN_2_YEAR_LBL": "2-year contract",
    "OD_DT_MDN_UPGRADE_EARLY_BTN": "Upgrade Early",
    "OD_DT_MDN_END_DATE_LBL": "End Date",
    "OD_DT_MDN_PAYMENT_AGREEMENT_INFO": "Check out your full two year payment agreement online at MyVerizon.com",
    "OD_DT_MDN_UPGRADE_BTN": "Upgrade",
    "OD_DT_MDN_TURN_OFF_IPHONE_DESC": "Instructions to turn off Find My iPhone will be in the return shipping box. If you don't turn it off, you won't be able to activate your new device.",
    "OD_DT_MDN_TURN_OFF_IPHONE_TITLE": "You need to turn off 'Find My iPhone' on your old device.",
    "OD_DT_MDN_TURN_OFF_IPHONE_IMG": "images/find_my_phone_tmp.png",
    "OD_DT_MDN_NO_BTN": "No",
    "OD_DT_MDN_YES_BTN": "Yes",
    "OD_DT_MDN_NEW_DEVICE_LBL": "New Device",
    "OD_DT_MDN_ADD_BTN": "Add",
    "OD_DT_MDN_ACCT_LINE_LIMIT_TITLE": "You have reached the maximum number of devices for your account.",
    "OD_DT_MDN_ACCT_LINE_LIMIT_URL": "/digital/mtnDetail",
    "OD_DT_MDN_ACCT_LINE_LIMIT_LINK_TXT": "View Devices",
    "OD_DT_MDN_MIXED_CART_TITLE": "Sorry, you have to finish adding a line first",
    "OD_DT_MDN_MIXED_CART_CONTENT": "Please complete adding a line to your account before you upgrade this device. You can also empty your cart and try again.",
    "OD_DT_MDN_MIXED_CART_LINK_TXT": "/digital/cart/getCartDetails",
    "OD_DT_MDN_MIXED_CART_LINK": "View cart",
    "OD_DT_MDN_CART_DEVICE_LIMIT_TITLE": "You've hit the maximum number of devices for this transaction.",
    "OD_DT_MDN_CART_DEVICE_LIMIT_CONTENT": "If you still want to add this device, you can empty your cart, replace a device in your cart or finish this purchase as a separate transaction.",
    "OD_DT_MDN_CART_DEVICE_LIMIT_TXT": "/digital/cart/getCartDetails",
    "OD_DT_MDN_CART_DEVICE_LIMIT_LINK": "View cart"
},
  "error": {}
}

export default cqJSON;
