const mdnJSON  = 
/* {
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "mtnDetailsList": [
      {
        "upgradeEligbile": true,
        "displayMtn": "719.649.8369",
        "mtn": "7196498369",
        "encryptedMTN": "IZWJ24duvQXvavIl6wS/rA==",
        "upgradeMessage": null,
        "nickname": "CINDY IPAD",
        "imageUrl": "https://mobile.vzw.com/hybridClient/is/image/VerizonWireless/apple-ipadair2-spacegrey?$device-med$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Tablet",
        "familyType": "Tablet Internet Home",
        "familyTypeRestricted": true,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "3544230638850516",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "iPad&reg; Air 2",
        "deviceName": "Apple&reg; iPad&reg; Air 2 Space Gray 16GB",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "showTransferUpgrade": true,
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev3360006",
        "refundStatus": null,
        "alwaysEligibleForUpgrade": false,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "719.661.4246",
        "mtn": "7196614246",
        "encryptedMTN": "40vMNfgzbeTrs6TCbE8vvg==",
        "upgradeMessage": null,
        "nickname": "TONY RUSSELL",
        "imageUrl": null,
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Other Devices",
        "familyType": "Phone",
        "familyTypeRestricted": true,
        "contractTermMisMatch": false,
        "brand": null,
        "deviceId": "355077080508475",
        "twoYearContract": {
          "title": "Get a new device before your contract ends.",
          "subTitle": "Getting a New Device",
          "endDate": "11/29/2017",
          "daysPercentage": "86.57534246575342",
          "description": "If you upgrade today, you can choose to make monthly payments for your new device or get it at the full retail price. If you pay monthly, we'll need 15.00% of the retail price as down payment.",
          "contractTermText": "2-year contract",
          "mtnSummarPageSubText": null,
          "daysRemainingText": "98 days remaining",
          "mtnSummaryPageSubTitle": "Getting a New Device",
          "mtnSummaryPageTitle": "Get a new device before your contract ends."
        },
        "annualUpgrade": false,
        "displayDeviceName": "ECom Postpaid Service Product",
        "deviceName": "ECom Service SKU",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge"
        ],
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev4800002",
        "refundStatus": null,
        "alwaysEligibleForUpgrade": false,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "719.203.0226",
        "mtn": "7192030226",
        "encryptedMTN": "xo7qEpi9ved/LzCeGMYNVg==",
        "upgradeMessage": null,
        "nickname": "PITA RUSSELL",
        "imageUrl": "https://mobile.vzw.com/hybridClient/is/image/VerizonWireless/Motorola_Droid_Mini_White?$device-med$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": {
          "title": "Want to upgrade early?",
          "subtitle": "You have $312.40 remaining on your payment agreement",
          "paidToDate": "Paid to date:$437.59",
          "totalPrice": "$749.99 total price",
          "returnOptionTitle": "Return your device",
          "returnOptionDescription": "If your device is working properly, send it in after you upgrade and you're all set.",
          "keepOptionTitle": "Keep your device and pay $312.40",
          "keepOptionDescription": "Pay off your remaining balance and keep your old device.",
          "edgeUpRequiredPercentage": 50,
          "paidAmountPercentage": "58.0",
          "upgradeSummary": null,
          "deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
          "deviceAgreementLink": null,
          "remainingAmountText": "$312.40 remaining",
          "pendingInstallmentText": "9 of 24 payments completed",
          "subtitleDescriptionText": "If you'd like to upgrade today,just pay the remaining balance of $312.40"
        },
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Motorola",
        "deviceId": "9900045347847000",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "DROID Mini",
        "deviceName": "DROID Mini by Motorola in White",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "showTransferUpgrade": true,
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev1040074",
        "refundStatus": null,
        "alwaysEligibleForUpgrade": false,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "719.388.3735",
        "mtn": "7193883735",
        "encryptedMTN": "vto0Taao6RoyhF66JS/z+g==",
        "upgradeMessage": null,
        "nickname": "MIKEY DIAZ",
        "imageUrl": "https://mobile.vzw.com/hybridClient/is/image/VerizonWireless/Motorola_Droid_Bounce_Leather_Black_Without?$device-med$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": {
          "title": "Here's how you can upgrade today.",
          "subtitle": "You have a balance of $299.00",
          "paidToDate": "Paid to date:$253.00",
          "totalPrice": "$552.00 total price",
          "returnOptionTitle": null,
          "returnOptionDescription": null,
          "keepOptionTitle": null,
          "keepOptionDescription": "To upgrade this device, it must be paid off in full. If you would like to upgrade today, just pay off the remaining balance of $299.00",
          "edgeUpRequiredPercentage": 100,
          "paidAmountPercentage": "46.0",
          "upgradeSummary": null,
          "deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
          "deviceAgreementLink": null,
          "remainingAmountText": "$299.00 remaining",
          "pendingInstallmentText": "12 of 24 payments completed",
          "subtitleDescriptionText": null
        },
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Motorola",
        "deviceId": "990005742877530",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "DROID TURBO 2",
        "deviceName": "DROID TURBO 2 32GB in Black-Pebble Leather",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "showTransferUpgrade": true,
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev5440238",
        "refundStatus": null,
        "alwaysEligibleForUpgrade": false,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "719.749.8226",
        "mtn": "7197498226",
        "encryptedMTN": "WpV9+sSum/d/LzCeGMYNVg==",
        "upgradeMessage": null,
        "nickname": "ADAM RUSSELL",
        "imageUrl": "https://mobile.vzw.com/hybridClient/is/image/VerizonWireless/Samsung_Hero_Black?$device-med$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": {
          "title": "Here's how you can upgrade today.",
          "subtitle": "You have a balance of $449.92",
          "paidToDate": "Paid to date:$225.08",
          "totalPrice": "$675.00 total price",
          "returnOptionTitle": null,
          "returnOptionDescription": null,
          "keepOptionTitle": null,
          "keepOptionDescription": "To upgrade this device, it must be paid off in full. If you would like to upgrade today, just pay off the remaining balance of $449.92",
          "edgeUpRequiredPercentage": 100,
          "paidAmountPercentage": "33.0",
          "upgradeSummary": null,
          "deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
          "deviceAgreementLink": null,
          "remainingAmountText": "$449.92 remaining",
          "pendingInstallmentText": "15 of 24 payments completed",
          "subtitleDescriptionText": null
        },
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Samsung",
        "deviceId": "359775075718209",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Galaxy S7",
        "deviceName": "Samsung Galaxy S7 32GB in Black Onyx",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "showTransferUpgrade": true,
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev5800066",
        "refundStatus": null,
        "alwaysEligibleForUpgrade": false,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "719.661.0669",
        "mtn": "7196610669",
        "encryptedMTN": "bPWdE2ZttZnvavIl6wS/rA==",
        "upgradeMessage": null,
        "nickname": "CINDY RUSSELL",
        "imageUrl": "https://mobile.vzw.com/hybridClient/is/image/VerizonWireless/iphone7-plus-front-rsgld?$device-med$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": {
          "title": "Want to upgrade early?",
          "subtitle": "You have $653.28 remaining on your payment agreement",
          "paidToDate": "Paid to date:$326.72",
          "totalPrice": "$980.00 total price",
          "returnOptionTitle": "Return your device and pay $163.28",
          "returnOptionDescription": "If your device is working properly, send it in after you upgrade and you're all set.",
          "keepOptionTitle": "Keep your device and pay $653.28",
          "keepOptionDescription": "Pay off your remaining balance and keep your old device.",
          "edgeUpRequiredPercentage": 50,
          "paidAmountPercentage": "33.0",
          "upgradeSummary": null,
          "deviceAgreementText": "Upgrade Program Terms and Conditions.",
          "deviceAgreementLink": "https://www.verizonwireless.com/support/upgrade-program-legal/",
          "remainingAmountText": "$653.28 remaining",
          "pendingInstallmentText": "15 of 24 payments completed",
          "subtitleDescriptionText": "If you'd like to upgrade today,just pay the remaining balance of $653.28"
        },
        "annualUpgradeMessage": {
          "subTitle": "You may still upgrade to this device, but you will no longer have the benefits of the annual upgrade program.",
          "acceptButtonText": "Accept",
          "title": "Your new device is not eligible for annual upgrade.",
          "cancelButtonText": "Cancel"
        },
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "353818082185570",
        "twoYearContract": null,
        "annualUpgrade": true,
        "displayDeviceName": "iPhone&reg; 7 Plus",
        "deviceName": "Apple&reg; iPhone&reg; 7 Plus 256GB in Rose Gold",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev6640013",
        "refundStatus": null,
        "alwaysEligibleForUpgrade": false,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "719.651.6910",
        "mtn": "7196516910",
        "encryptedMTN": "UfCGAaDt9NivXiy3IGKQAw==",
        "upgradeMessage": null,
        "nickname": "STEVE LOVE",
        "imageUrl": "https://mobile.vzw.com/hybridClient/is/image/VerizonWireless/iphone7-plus-front-jetblk?$device-med$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": {
          "title": "Want to upgrade early?",
          "subtitle": "You have $653.28 remaining on your payment agreement",
          "paidToDate": "Paid to date:$326.72",
          "totalPrice": "$980.00 total price",
          "returnOptionTitle": "Return your device and pay $163.28",
          "returnOptionDescription": "If your device is working properly, send it in after you upgrade and you're all set.",
          "keepOptionTitle": "Keep your device and pay $653.28",
          "keepOptionDescription": "Pay off your remaining balance and keep your old device.",
          "edgeUpRequiredPercentage": 50,
          "paidAmountPercentage": "33.0",
          "upgradeSummary": null,
          "deviceAgreementText": "Upgrade Program Terms and Conditions.",
          "deviceAgreementLink": "https://www.verizonwireless.com/support/upgrade-program-legal/",
          "remainingAmountText": "$653.28 remaining",
          "pendingInstallmentText": "15 of 24 payments completed",
          "subtitleDescriptionText": "If you'd like to upgrade today,just pay the remaining balance of $653.28"
        },
        "annualUpgradeMessage": {
          "subTitle": "You may still upgrade to this device, but you will no longer have the benefits of the annual upgrade program.",
          "acceptButtonText": "Accept",
          "title": "Your new device is not eligible for annual upgrade.",
          "cancelButtonText": "Cancel"
        },
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "359171078039680",
        "twoYearContract": null,
        "annualUpgrade": true,
        "displayDeviceName": "iPhone&reg; 7 Plus",
        "deviceName": "Apple&reg; iPhone&reg; 7 Plus 256GB in Jet Black",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev6640013",
        "refundStatus": null,
        "alwaysEligibleForUpgrade": false,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "719.600.9546",
        "mtn": "7196009546",
        "encryptedMTN": "HVdqbuvlYWbrs6TCbE8vvg==",
        "upgradeMessage": null,
        "nickname": "STEVE IPAD IPAD",
        "imageUrl": "https://mobile.vzw.com/hybridClient/is/image/VerizonWireless/apple_ipadmini_retina_spacegray?$device-med$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Tablet",
        "familyType": "Tablet Internet Home",
        "familyTypeRestricted": true,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "358850058245650",
        "twoYearContract": {
          "title": "Get a new device before your contract ends.",
          "subTitle": "Getting a New Device",
          "endDate": "12/08/2018",
          "daysPercentage": "35.342465753424655",
          "description": "If you upgrade today, you can choose to make monthly payments for your new device or get it at the full retail price. If you pay monthly, we'll need 30.00% of the retail price as down payment.",
          "contractTermText": "2-year contract",
          "mtnSummarPageSubText": null,
          "daysRemainingText": "472 days remaining",
          "mtnSummaryPageSubTitle": "Getting a New Device",
          "mtnSummaryPageTitle": "Get a new device before your contract ends."
        },
        "annualUpgrade": false,
        "displayDeviceName": "iPad&reg; mini 2",
        "deviceName": "Apple&reg; iPad&reg; mini 2 32GB in Space Gray",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge"
        ],
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev1080028",
        "refundStatus": null,
        "alwaysEligibleForUpgrade": true,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "719.600.9545",
        "mtn": "7196009545",
        "encryptedMTN": "HVdqbuvlYWZqaTXqOhDwqQ==",
        "upgradeMessage": null,
        "nickname": "CINDY IPAD IPAD",
        "imageUrl": "https://mobile.vzw.com/hybridClient/is/image/VerizonWireless/apple_ipadmini_retina_spacegray?$device-med$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Tablet",
        "familyType": "Tablet Internet Home",
        "familyTypeRestricted": true,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "358850058333840",
        "twoYearContract": {
          "title": "Get a new device before your contract ends.",
          "subTitle": "Getting a New Device",
          "endDate": "12/08/2018",
          "daysPercentage": "35.342465753424655",
          "description": "If you upgrade today, you can choose to make monthly payments for your new device or get it at the full retail price. If you pay monthly, we'll need 30.00% of the retail price as down payment.",
          "contractTermText": "2-year contract",
          "mtnSummarPageSubText": null,
          "daysRemainingText": "472 days remaining",
          "mtnSummaryPageSubTitle": "Getting a New Device",
          "mtnSummaryPageTitle": "Get a new device before your contract ends."
        },
        "annualUpgrade": false,
        "displayDeviceName": "iPad&reg; mini 2",
        "deviceName": "Apple&reg; iPad&reg; mini 2 32GB in Space Gray",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge"
        ],
        "mtnAddedToTheCart": false,
        "deviceProductId": "dev1080028",
        "refundStatus": null,
        "alwaysEligibleForUpgrade": true,
        "myOffersPromoText": null,
        "annualUpgradeWarning": false
      }
    ],
    "accountLevelInEligibleCode": null,
    "accountLevelInEligibleMessage": null,
    "selectedMTN": null,
    "aalRedirect": "/digital/shoplanding/?flow=AAL",
    "accountLevelInEligibleDetails": null,
    "cartRedirect": "/digital/cart/getCartDetails",
    "shopLandingRedirect": "/digital/shoplanding/",
    "mtnMainTitle": "Would you like to upgrade or add a new device?",
    "unlimitedPlan": "Y",
    "pastDueDetails": null,
    "aalAllowed": true,
    "aalboxEnable": true
  },
  "ajaxCallUrl": "/digital/shoplanding/"
} */

{
	"statusCode": "00",
	"errorMap": null,
	"output": {
		"mtnDetailsList": [{
			"upgradeEligbile": true,
			"displayMtn": "917.603.4821",
			"mtn": "9176034821",
			"encryptedMTN": "E+Ss+zXK+93wZE3gecGGsA==",
			"upgradeMessage": null,
			"nickname": "ETHAN               C HENDERSO-4821",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iPhone8Plus-SpGry?$device-thumb$",
			"inEligibleCode": null,
			"inEligibleDetails": null,
			"loanInfo": null,
			"annualUpgradeMessage": null,
			"deviceType": "Smartphone",
			"familyType": "Phone",
			"familyTypeRestricted": false,
			"contractTermMisMatch": false,
			"brand": "Apple",
			"deviceId": "356712083314518",
			"twoYearContract": null,
			"annualUpgrade": false,
			"displayDeviceName": "Apple&reg; iPhone&reg; 8 Plus 256GB in Space Gray",
			"deviceName": "IPHONE 8 PLUS SP GRY 256GB VZ",
			"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
			"mtnAddedToTheCart": false,
			"lineSharingIndicator": null,
			"buyoutRestrictedForEdge": false,
			"showTransferUpgrade": true,
			"transferUpgradeInProgress": false,
			"transferredFromMtn": null,
			"transferredToMtn": null,
			"tradeinPromoInfo": null,
			"alwaysEligibleForUpgrade": false,
			"sorDeviceType": "4GE",
			"daccCode": "01057",
			"deviceProdId": "dev8720045",
			"estimatedTradeInValue": "432.00",
			"annualUpgradeWarning": false
		}, {
			"upgradeEligbile": true,
			"displayMtn": "646.629.5076",
			"mtn": "6466295076",
			"encryptedMTN": "MtofGYc427ENAq0hbkE33g==",
			"upgradeMessage": null,
			"nickname": "ETHAN               C HENDERSO-5076",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone-6-spacegray?$device-thumb$",
			"inEligibleCode": null,
			"inEligibleDetails": null,
			"loanInfo": null,
			"annualUpgradeMessage": null,
			"deviceType": "Smartphone",
			"familyType": "Phone",
			"familyTypeRestricted": false,
			"contractTermMisMatch": false,
			"brand": "Apple",
      "deviceId": "359239066223091",
      "nextUpgradeDate": "02/14/2019",
      "contractEndsDate": "02/14/2019",
			"twoYearContract": {
				"title": "Get a new device before your contract ends.",
				"subTitle": "Getting a New Device",
				"endDate": "09/01/2018",
				"daysPercentage": "80.27397260273973",
				"description": "If you upgrade today, you can choose to make monthly payments for your new device or get it at the full retail price. If you pay monthly, we'll need 15.00% of the retail price as down payment.",
				"contractTermText": "2-year contract",
				"mtnSummarPageSubText": null,
				"daysRemainingText": "144 days remaining",
				"mtnSummaryPageSubTitle": "Getting a New Device",
				"mtnSummaryPageTitle": "Get a new device before your contract ends."
			},
			"annualUpgrade": false,
			"displayDeviceName": "Apple&reg; iPhone&reg; 6 64GB in Space Gray",
			"deviceName": "iPhone 6 64GB Space Gray",
			"eligibleUpgradeTypeList": ["Retail", "Edge"],
			"mtnAddedToTheCart": false,
			"lineSharingIndicator": "",
			"buyoutRestrictedForEdge": false,
			"showTransferUpgrade": false,
			"transferUpgradeInProgress": false,
			"transferredFromMtn": null,
			"transferredToMtn": null,
			"tradeinPromoInfo": null,
			"alwaysEligibleForUpgrade": true,
			"sorDeviceType": "4GE",
			"daccCode": "00774",
			"deviceProdId": "dev3240008",
			"estimatedTradeInValue": "95.00",
			"annualUpgradeWarning": false
    },
    {
			"upgradeEligbile": true,
			"displayMtn": "646.629.5076",
			"mtn": "6466295074",
			"encryptedMTN": "MtofGYc427ENAq0hbkE33g==",
			"upgradeMessage": null,
			"nickname": "ETHAN               C HENDERSO-5076",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone-6-spacegray?$device-thumb$",
			"inEligibleCode": null,
			"inEligibleDetails": null,
			"loanInfo": null,
			"annualUpgradeMessage": null,
			"deviceType": "Smartphone",
			"familyType": "Phone",
			"familyTypeRestricted": false,
			"contractTermMisMatch": false,
			"brand": "Apple",
      "deviceId": "359239066223091",
      "nextUpgradeDate": "02/14/2021",
      "contractEndsDate": "02/14/2021",
			"twoYearContract": {
				"title": "Get a new device before your contract ends.",
				"subTitle": "Getting a New Device",
				"endDate": "09/01/2018",
				"daysPercentage": "80.27397260273973",
				"description": "If you upgrade today, you can choose to make monthly payments for your new device or get it at the full retail price. If you pay monthly, we'll need 15.00% of the retail price as down payment.",
				"contractTermText": "2-year contract",
				"mtnSummarPageSubText": null,
				"daysRemainingText": "144 days remaining",
				"mtnSummaryPageSubTitle": "Getting a New Device",
				"mtnSummaryPageTitle": "Get a new device before your contract ends."
			},
			"annualUpgrade": false,
			"displayDeviceName": "Apple&reg; iPhone&reg; 6 64GB in Space Gray",
			"deviceName": "iPhone 6 64GB Space Gray",
			"eligibleUpgradeTypeList": ["Retail", "Edge"],
			"mtnAddedToTheCart": false,
			"lineSharingIndicator": "",
			"buyoutRestrictedForEdge": false,
			"showTransferUpgrade": false,
			"transferUpgradeInProgress": false,
			"transferredFromMtn": null,
			"transferredToMtn": null,
			"tradeinPromoInfo": null,
			"alwaysEligibleForUpgrade": true,
			"sorDeviceType": "4GE",
			"daccCode": "00774",
			"deviceProdId": "dev3240008",
			"estimatedTradeInValue": "95.00",
			"annualUpgradeWarning": false
		}],
		"accountLevelInEligibleCode": null,
		"accountLevelInEligibleMessage": null,
		"sharedCartDetailsInfo": null,
		"selectedMTN": "6466295076",
		"aalRedirect": null,
		"accountLevelInEligibleDetails": null,
		"cartRedirect": "/od/cust/auth/cart/getCartDetails",
		"shopLandingRedirect": "/od/cust/auth/shoplanding/",
		"mtnMainTitle": "Would you like to upgrade or add a new device?",
		"catergoryCode": null,
		"unlimitedPlan": "Y",
		"pastDueDetails": null,
		"submitAddALineUrl": "/od/cust/auth/submitaddaline",
		"transferGiverMTNs": ["9176034821"],
		"transferTakerMTNs": ["6466295076", "6466295074"],
		"transferUpgradeUrl": null,
		"customerType": "B2C",
		"edgeEligible": true,
		"ajaxCallUrl": "/od/cust/auth/submitSummary",
		"ajaxCallSelectedMTN": "/od/cust/auth/mtnDetail/json?flow=EUP&t=",
		"redirectURL": null,
		"sharedPlan": false,
		"submitByodRedirectUrl": "/od/cust/auth/byod/bring-your-own-device",
		"aalAllowed": true,
		"aalboxEnable": false,
		"byodAllowed": true,
		"sharedCartRetrieved": null
	},
	"cpcRequired": false
};

export default mdnJSON;
