window.confirmationJSON = {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "910079754901816",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to PREETHA.SIVAKUMAR@VERIZON.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 1,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "PREETHA.SIVAKUMAR@VERIZON.COM",
		"shipToAddresss": [{
			"shippingGroupId": null,
			"orderId": null,
			"shippingGroupType": null,
			"shippingType": null,
			"shippingMethod": "FREE 2 Day by 8pm",
			"shippingMethodId": "SHP002",
			"shippingGroupStatus": null,
			"depletionLocation": null,
			"deliveryDate": null,
			"deliveryTime": null,
			"fipsCode": "2900960176",
			"rawShippingPrice": 0.0,
			"discountAmount": 0.0,
			"taxAmount": 0.0,
			"taxDescription": null,
			"taxType": null,
			"priceAdjustmentId": null,
			"shippingCost": 0.0,
			"shippingSaving": 0.0,
			"signatureRequired": "N",
			"overnightShipPriorityFlag": 0,
			"storeInfoId": null,
			"sddSelectedWindowId": null,
			"shippingContactInfoId": null,
			"shippingContactInfo": {
				"id": null,
				"emailAddress": "PREETHA.SIVAKUMAR@VERIZON.COM",
				"phoneNumber": "7267752032",
				"lastName": "BOWER",
				"firstName": "RAVI",
				"zipCode": "65734",
				"orderId": null,
				"userId": null,
				"npaNxxNumber": null,
				"address1": "7483 STATE HIGHWAY 37 LOT 31",
				"address2": null,
				"city": "Purdy",
				"state": "MO",
				"addressVerified": true,
				"textAlertOptin": false,
				"newsLetterOptin": false,
				"paperFreeBillingIndicatorFlag": false,
				"middleName": null,
				"firmName": null,
				"businessName": null,
				"apartmentNum": "31",
				"addressDirection": "",
				"poBox": "",
				"streetNumber": "7483",
				"streetName": "STATE HIGHWAY 37",
				"streetType": "",
				"ruralRoute": null,
				"ruralDel": "",
				"zipCode4": null,
				"zipCode5": null,
				"faxNumber": null,
				"addressType": null,
				"country": "",
				"prefix": null,
				"suffix": null,
				"postbox": null,
				"companyname": null,
				"ruralrte": "",
				"county": null,
				"address3": null,
				"postalcode": "65734",
				"version": 0,
				"lastModifiedDate": null,
				"addressConfirmationStatus": null
			},
			"estimatedDeliveryDate": null,
			"taxDetails": [],
			"version": 0,
			"lastModifiedDate": null,
			"storeAddress": null,
			"sameDayDelivery": false,
			"sddTimeZone": null,
			"sddavailableDeliveryWindows": null
		}],
		"billToAddress": {
			"id": null,
			"emailAddress": "PREETHA.SIVAKUMAR@VERIZON.COM",
			"phoneNumber": "7267752032",
			"lastName": "BOWER",
			"firstName": "RAVI",
			"zipCode": "65734",
			"orderId": null,
			"userId": null,
			"npaNxxNumber": null,
			"address1": "7483 STATE HIGHWAY 37 LOT 31",
			"address2": null,
			"city": "Purdy",
			"state": "MO",
			"addressVerified": true,
			"textAlertOptin": false,
			"newsLetterOptin": false,
			"paperFreeBillingIndicatorFlag": false,
			"middleName": null,
			"firmName": null,
			"businessName": null,
			"apartmentNum": "31",
			"addressDirection": "",
			"poBox": "",
			"streetNumber": "7483",
			"streetName": "STATE HIGHWAY 37",
			"streetType": "",
			"ruralRoute": null,
			"ruralDel": "",
			"zipCode4": null,
			"zipCode5": null,
			"faxNumber": null,
			"addressType": null,
			"country": "",
			"prefix": null,
			"suffix": null,
			"postbox": null,
			"companyname": null,
			"ruralrte": "",
			"county": null,
			"address3": null,
			"postalcode": "65734",
			"version": 0,
			"lastModifiedDate": null,
			"addressConfirmationStatus": null
		},
		"deviceList": [{
			"id": "SDC49106b37a944408f4652b4abc046a366_device_1",
			"quantity": 1,
			"type": null,
			"skuId": "sku2150070",
			"productId": "dev6640013",
			"sorId": "MNR12LL/A",
			"itemAmount": 0.0,
			"itemAmountOriginal": null,
			"dueMonthly": 19.58,
			"dueMonthlyOriginal": 27.91,
			"itemDiscount": 200.0,
			"displayName": "iPhone&reg; 7 Plus",
			"skuDisplayName": "Apple&reg; iPhone&reg; 7 Plus 32GB in Black",
			"listPrice": 669.99,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
				"orderId": "SDC49106b37a944408f4652b4abc046a366",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": "edgeFullRetailPriceListId",
				"listPrice": 669.99,
				"offerName": null,
				"creationDate": 1522937560045,
				"lastModifiedDate": 1522937560045,
				"version": 1
			}],
			"orderId": "SDC49106b37a944408f4652b4abc046a366",
			"version": 2,
			"delete": false,
			"inventoryLevel": 1000,
			"taxDetails": [{
				"taxLineItemId": null,
				"lineItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
				"itemType": "device",
				"sorSkuId": "UPGRADEFEE30",
				"taxType": "taxes_fees",
				"taxAmount": 0.6,
				"taxDescription": "MO Local Sales Tax",
				"version": 0,
				"orderId": "SDC49106b37a944408f4652b4abc046a366",
				"createdDate": 1522937572526
			}, {
				"taxLineItemId": null,
				"lineItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
				"itemType": "device",
				"sorSkuId": "UPGRADEFEE30",
				"taxType": "taxes_fees",
				"taxAmount": 1.27,
				"taxDescription": "MO State Sales Tax",
				"version": 0,
				"orderId": "SDC49106b37a944408f4652b4abc046a366",
				"createdDate": 1522937572526
			}, {
				"taxLineItemId": null,
				"lineItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
				"itemType": "device",
				"sorSkuId": "UPGRADEFEE30",
				"taxType": "taxes_fees",
				"taxAmount": 0.45,
				"taxDescription": "MO Local Sales Tax",
				"version": 0,
				"orderId": "SDC49106b37a944408f4652b4abc046a366",
				"createdDate": 1522937572526
			}, {
				"taxLineItemId": null,
				"lineItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
				"itemType": "device",
				"sorSkuId": "MNR12LL/A",
				"taxType": "taxes_fees",
				"taxAmount": 9.4,
				"taxDescription": "MO Local Sales Tax",
				"version": 0,
				"orderId": "SDC49106b37a944408f4652b4abc046a366",
				"createdDate": 1522937572526
			}, {
				"taxLineItemId": null,
				"lineItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
				"itemType": "device",
				"sorSkuId": "MNR12LL/A",
				"taxType": "taxes_fees",
				"taxAmount": 7.05,
				"taxDescription": "MO Local Sales Tax",
				"version": 0,
				"orderId": "SDC49106b37a944408f4652b4abc046a366",
				"createdDate": 1522937572526
			}, {
				"taxLineItemId": null,
				"lineItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
				"itemType": "device",
				"sorSkuId": "MNR12LL/A",
				"taxType": "taxes_fees",
				"taxAmount": 19.85,
				"taxDescription": "MO State Sales Tax",
				"version": 0,
				"orderId": "SDC49106b37a944408f4652b4abc046a366",
				"createdDate": 1522937572526
			}],
			"itemTaxes": 38.62,
			"ispuEligibleFlag": true,
			"purchasePath": "EUP",
			"contractTerm": 99,
			"expectedShippingDate": null,
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-lg$",
			"color": "Black",
			"capacity": "32GB",
			"planLineItemId": "SDC49106b37a944408f4652b4abc046a366_plan_1",
			"edgeFullRetailPrce": 669.99,
			"edgeDeviceListPrice": 669.99,
			"edgeFirstMonthAmount": 19.65,
			"edgeMonthlyAmount": 19.58,
			"priceListId": "edgeFullRetailPriceListId",
			"itemDownPayment": 0.0,
			"bogoType": null,
			"barCodeDiscount": 200.0,
			"recycleStateInd": null,
			"year": "0",
			"make": "",
			"model": "",
			"email": "",
			"isHumOrder": "N",
			"npanxxCode": null,
			"mtnNumber": "4174893929",
			"upgradeFee": 30.0,
			"activationFee": 0.0,
			"cpe": false,
			"recycleCreditAllocatedAmount": 0.0,
			"installmentContractDetails": {
				"id": null,
				"installmentContractResp": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><POSServices xmlns=\"http://pos.odc.vzwcorp.com\"><ServiceHeader><userName>ESNTRN1</userName><password>*********</password><clientAppName>ATG-ECOM-MDOT</clientAppName><clientAppUserName>ECOM</clientAppUserName><serviceName>orderProcessing</serviceName><serviceAction>generateInstallmentContract</serviceAction><applicationResponseCode>99000</applicationResponseCode><applicationResponseClass>SUCCESS</applicationResponseClass><applicationResponseMessage>[ESQA1srv01:vipsvcs02:02]Transaction processed successfully.</applicationResponseMessage><applicationResponseDetails></applicationResponseDetails><timeStamp>2018-04-05T10:12:53.051-04:00</timeStamp><transactionId>121dde0a-f115-42a1-b458-c38fe4481616</transactionId><sessionID>POS1f4c4755-9fd0-4d0c-983e-dec25d65bcd2_ss1</sessionID><orderKeyInfo><clusterInfo>EAST</clusterInfo><location>M722801</location><creditApplicationNum>703971226</creditApplicationNum><orderNum>1001739</orderNum><billingSystem>VN</billingSystem><salesForceId>NPB2C</salesForceId><outletId>000101068</outletId></orderKeyInfo><clientOrderInfo><channelId>B2C</channelId><vendorId>VZWCOM-MOB-MDOT</vendorId><clientOrderType>EUPSLND</clientOrderType></clientOrderInfo><encryptionIndicator>T</encryptionIndicator><loggingId>2f5d156b2ce2562e</loggingId></ServiceHeader><ServiceBody><generateInstallmentContract><response><installmentContractDetail><locationCode>M722801</locationCode><creditApplicationNum>703971226</creditApplicationNum><orderNum>1001739</orderNum><installmentType>E</installmentType><installmentLoanNumber>2000736445</installmentLoanNumber><mobileNumber>4174893929</mobileNumber><itemCode>MNR12LL/A</itemCode><multiLineSeqNumber>1</multiLineSeqNumber><depletionType>F</depletionType><creditClass>B</creditClass><loanTerm>24</loanTerm><downPaymentAmount>0.00</downPaymentAmount><firstMonthPaymentAmount>19.65</firstMonthPaymentAmount><balanceLoanAmount>469.99</balanceLoanAmount><MIRAmount>0.00</MIRAmount><taxBasis>F</taxBasis><taxAmount>36.31</taxAmount><financeChargeAmount>0.00</financeChargeAmount><financeChargedTaxAmount>0.00</financeChargedTaxAmount><deviceTaxPrice>669.99</deviceTaxPrice><loanStatus>A</loanStatus><mtnEffectiveDate>Thu Apr 05 10:12:52 EDT 2018</mtnEffectiveDate><loanAmount>469.99</loanAmount><taxGroupID>0000</taxGroupID><taxItemID>000</taxItemID><productId>36222</productId><firstCollectedAmount>N</firstCollectedAmount><taxGeoAddressType>S</taxGeoAddressType><loanMonthlyPaymentAmount>19.58</loanMonthlyPaymentAmount><loanTaxCollectedAmount>36.31</loanTaxCollectedAmount><loanTaxableBaseAmount>469.99</loanTaxableBaseAmount><downPaymentTaxCollectedAmount>0.00</downPaymentTaxCollectedAmount><loanTotalFinancialChargeAmount>0.00</loanTotalFinancialChargeAmount><financeChargedCollectedAmount>0.00</financeChargedCollectedAmount><financeChargedTaxCollectedAmount>0</financeChargedTaxCollectedAmount><calculatedAPR>0</calculatedAPR><machineType>D</machineType><previousInstallmentLoanNumber>0</previousInstallmentLoanNumber><installmentPaymentSchedule><installmentPaymentScheduleCount>24</installmentPaymentScheduleCount><paymentDate>05/08/2018</paymentDate><paymentDate>06/08/2018</paymentDate><paymentDate>07/08/2018</paymentDate><paymentDate>08/08/2018</paymentDate><paymentDate>09/08/2018</paymentDate><paymentDate>10/08/2018</paymentDate><paymentDate>11/08/2018</paymentDate><paymentDate>12/08/2018</paymentDate><paymentDate>01/08/2019</paymentDate><paymentDate>02/08/2019</paymentDate><paymentDate>03/08/2019</paymentDate><paymentDate>04/08/2019</paymentDate><paymentDate>05/08/2019</paymentDate><paymentDate>06/08/2019</paymentDate><paymentDate>07/08/2019</paymentDate><paymentDate>08/08/2019</paymentDate><paymentDate>09/08/2019</paymentDate><paymentDate>10/08/2019</paymentDate><paymentDate>11/08/2019</paymentDate><paymentDate>12/08/2019</paymentDate><paymentDate>01/08/2020</paymentDate><paymentDate>02/08/2020</paymentDate><paymentDate>03/08/2020</paymentDate><paymentDate>04/08/2020</paymentDate></installmentPaymentSchedule><firstmonthPaymentCollected>N</firstmonthPaymentCollected><stateOverrideTaxBasisAmount>469.99</stateOverrideTaxBasisAmount><deviceTaxOnContract>36.31</deviceTaxOnContract><agreementPercentage>100.0</agreementPercentage><upgradeOptionCode>DP</upgradeOptionCode><upgradeDeviceCategoryText></upgradeDeviceCategoryText><taxOnContractForDisplay>36.31</taxOnContractForDisplay></installmentContractDetail><installmentContractDetailHTML>&lt;![CDATA[\n\t\t\t\t\t\t\t\t&lt;h3&gt;RETAIL INSTALLMENT SALE AGREEMENT / RETAIL INSTALLMENT OBLIGATION &amp;#8212; SUBJECT TO STATE REGULATION&lt;/h3&gt;\n\t\t\t\t\t\t\t\t&lt;div class=\"row\"&gt;\n\t\t\t\t\t\t\t\t\t&lt;span class=\"column50 bold\"&gt;SELLER (CREDITOR):&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t&lt;span class=\"column50\"&gt;Verizon Wireless Services, LLC (\"Verizon Wireless\")&lt;br/&gt;One Verizon Way, Basking Ridge, NJ 07920 (908) 559-7000&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t&lt;span class=\"column50 bold\"&gt;AGREEMENT #&lt;/span&gt; \n\t\t\t\t\t\t\t\t\t&lt;span class=\"column50\"&gt;2000736445&lt;/span&gt;\n\t\t    \t\t&lt;span class=\"column50 bold\"&gt;BUYER&amp;#39;S  NAME:&lt;/span&gt;\n\t\t\t\t\t\t\t    \t\t&lt;span class=\"column50 bold\"&gt;RAVI BOWER &amp;#44; the Verizon Wireless Account Owner, or if not the Buyer signing below his/her authorized Account Manager delegate(s):&amp;nbsp;BEN BOWER&lt;/span&gt;\n\t\t    \t\t\t\t\t\t\t\t\t\t\t&lt;span class=\"column50 bold\"&gt;BUYER&amp;#39;S PHONE NUMBER:&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t&lt;span class=\"column50\"&gt; 4174893929&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t&lt;span class=\"column50 bold\"&gt;BUYER&amp;#39;S ADDRESS:&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t&lt;span class=\"column50\"&gt;7483 STATE HIGHWAY 37 LOT 31  Purdy MO 65734&lt;/span&gt;    \n\t\t\t\t\t\t\t\t\t&lt;span class=\"column50 bold\"&gt;DESCRIPTION OF GOODS:&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span class=\"column50\"&gt;MNR12LL/A &amp;nbsp; (&lt;b&gt;&amp;#34;DEVICE&amp;#34;&lt;/b&gt;)&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span class=\"column50 bold\"&gt;TRANSACTION DATE:&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t&lt;span class=\"column50\"&gt;04/05/2018&lt;/span&gt; \n\t\t\t\t\t\t\t\t&lt;/div&gt;\n\t\t\t\t\t\t\t\t&lt;div class=\"row\"&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;YOU, meaning the Buyer named above, agree to pay US, the Seller/Creditor named above as Verizon Wireless, the Total Sale Price of the goods identified \n\t\t\t\t\t\t\t\t\t\tabove according to the Terms of this Retail Installment Sale Agreement/ Retail Installment Obligation (referred to below as &amp;#34;Agreement&amp;#34;).\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t&lt;/div&gt;\n\t\t\t\t\t\t\t\t&lt;div class=\"row\"&gt;\n\t\t\t\t\t\t\t\t\t&lt;h4&gt;ANNUAL PERCENTAGE RATE&lt;/h4&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;The cost of your credit as a yearly rate&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;0 %&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;h4&gt;FINANCE CHARGE&lt;/h4&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;The dollar amount the credit will cost you&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p class=\"bold\"&gt;$0.00&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;h4&gt;AMOUNT FINANCED&lt;/h4&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;The amount of credit provided to you or on your behalf&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;$469.99&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;h4&gt;TOTAL OF PAYMENTS&lt;/h4&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;The amount you will have paid after you have made all payments as scheduled&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;$469.99&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;h4&gt;TOTAL SALE PRICE&lt;/h4&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;The total cost of your purchase on credit including your down payment of $0.00&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;$469.99&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;h4&gt;Your payment schedule will be&lt;/h4&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;Number of Payments: 24   Payment 1: $19.65; Payment 2-24: $19.58;&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;Amount of Payments: $469.99&lt;/p&gt;\n\t\t\t\t\t\t\t\t&lt;/div&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t&lt;div class=\"row fine\"&gt;\n\t\t\t\t\t\t\t\t\t&lt;h4&gt;When Payments are Due :&lt;/h4&gt;\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t&lt;div class=\"column25 payments\"&gt;\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;Payments&lt;br /&gt;1 to 6&lt;/span&gt;\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t05/08/2018\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t06/08/2018\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t07/08/2018\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t08/08/2018\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t09/08/2018\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t10/08/2018\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/div&gt;\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t&lt;div class=\"column25 payments\"&gt;\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;Payments&lt;br /&gt;7 to 12&lt;/span&gt;\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t11/08/2018\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t12/08/2018\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t01/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t02/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t03/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t04/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/div&gt;\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t&lt;div class=\"column25 payments\"&gt;\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;Payments&lt;br /&gt;13 to 18&lt;/span&gt;\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t05/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t06/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t07/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t08/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t09/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t10/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/div&gt;\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t&lt;div class=\"column25 payments\"&gt;\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;Payments&lt;br /&gt;19 to 24&lt;/span&gt;\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t11/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t12/08/2019\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t01/08/2020\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t02/08/2020\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t03/08/2020\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t04/08/2020\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/div&gt;\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t&lt;/div&gt;\n\t\t\t\t\t\t\t\t&lt;div class=\"row\"&gt;\n\t\t\t\t\t\t\t\t\t&lt;p class=\"uppercase bold\"&gt;PAYMENTS RECEIVED 15 OR MORE DAYS AFTER YOUR DUE DATE MAY INCUR A LATE PAYMENT FEE OF UP TO 5% OR $5, WHICHEVER IS LESS.PLEASE SEE YOUR AGREEMENT TERMS FOR ANY ADDITIONAL INFORMATION ABOUT NONPAYMENT, DEFAULT, ANY \n\t\t\t\t\t\t\t\t\t\tREQUIRED PAYMENT IN FULL BEFORE THE SCHEDULED PAYMENT DATES, AND PREPAYMENT TERMS.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t&lt;/div&gt;\n\t\t\t\t\t\t\t\t&lt;div class=\"row fine\"&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;\n\t\t\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;AGREEMENT.&lt;/span&gt; THIS RETAIL INSTALLMENT SALES AGREEMENT (&lt;b&gt;&amp;ldquo;AGREEMENT&amp;rdquo;&lt;/b&gt;) REQUIRES THAT YOU AGREE TO AND\n\t\t\t\t\t\t\t\t\t\tMAINTAIN SERVICE WITH VERIZON WIRELESS UNDER YOUR CUSTOMER AGREEMENT. ALTHOUGH YOUR CUSTOMER AGREEMENT IS A SEPARATE\n\t\t\t\t\t\t\t\t\t\tDOCUMENT, EXCEPT AS PROHIBITED BY APPLICABLE LAW, THE WAIVERS AND LIMITATIONS OF LIABILITY, DISCLAIMER OF WARRANTIES,\n\t\t\t\t\t\t\t\t\t\tAND OTHER PROVISIONS OF YOUR CUSTOMER AGREEMENT ARE INCORPORATED BY THIS REFERENCE IN THIS AGREEMENT, AND SHALL SURVIVE\n\t\t\t\t\t\t\t\t\t\tTERMINATION OF YOUR CUSTOMER AGREEMENT. ADDITIONALLY, ANY DISPUTES UNDER THIS AGREEMENT SHALL BE RESOLVED IN ACCORDANCE\n\t\t\t\t\t\t\t\t\t\tWITH THE DISPUTE RESOLUTION PROVISIONS IN YOUR CUSTOMER AGREEMENT UNDER THE HEADING: &amp;ldquo;HOW DO I RESOLVE DISPUTES\n\t\t\t\t\t\t\t\t\t\tWITH VERIZON WIRELESS,&amp;rdquo; WHICH TERMS ARE INCORPORATED BY REFERENCE. SPECIFICALLY, YOU AND VERIZON WIRELESS BOTH AGREE\n\t\t\t\t\t\t\t\t\t\tTO RESOLVE ALL DISPUTES UNDER THIS AGREEMENT ONLY BY ARBITRATION OR SMALL CLAIMS COURT AND YOU WAIVE ANY RIGHT TO A JUDGE\n\t\t\t\t\t\t\t\t\t\tOR JURY IN ANY ARBITRATION.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;\n\t\t\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;PAYMENTS.&lt;/span&gt; Payment is due as stated on your bill. IF WE DO NOT RECEIVE PAYMENT WITHIN 15 DAYS OF THE DUE DATE, WE MAY CHARGE\n\t\t\t\t\t\t\t\t\t\tYOU A LATE PAYMENT FEE OF UP TO 5% OF THE UNPAID BALANCE OF YOUR BILL OR $5, WHICHEVER IS LESS, except where prohibited by\n\t\t\t\t\t\t\t\t\t\tlaw. Your specific payment schedule is provided above. Returned checks will be subject to a fee of up to $25, except where\n\t\t\t\t\t\t\t\t\t\tprohibited by law. Payments you make will be applied first to balances due under your Customer Agreement and then to balances\n\t\t\t\t\t\t\t\t\t\tdue under this Agreement. If you have more than one Retail Installment Sales Agreement on your account, payments will be \n\t\t\t\t\t\t\t\t\t\tapplied to the oldest one first, and then to more recent ones in order of age; if two Retail Installment Sales Agreements \n\t\t\t\t\t\t\t\t\t\tare entered into on the same day, the one added to our system first will be deemed older.Your payment \n\t\t\t\t\t\t\t\t\t\tschedule is determined by the date that you accept these terms and conditions, which allows us to apply charges to \n\t\t\t\t\t\t\t\t\t\tyour bill. If you order a Device that is not available for shipment at the time of order, we will provide you \n\t\t\t\t\t\t\t\t\t\twith a payment schedule based on our best estimate of when your Device will be shipped. Your first payment\n\t\t\t\t\t\t\t\t\t\twill not be due until the Device is shipped, at which point we will charge the credit card you provided at the time of your\n\t\t\t\t\t\t\t\t\t\tOrder or, if eligible apply the first payment to your bill. For any Device not available for shipment at the time of order,\n\t\t\t\t\t\t\t\t\t\tyou agree that we may update the estimated payment schedule when your Device is shipped, and we will provide the new payment\n\t\t\t\t\t\t\t\t\t\tschedule to you in writing. Additionally, if a delay in accepting this Agreement or activating your Device results in any\n\t\t\t\t\t\t\t\t\t\tcharges becoming due on a date(s) later than the payment schedule, we will provide you with an updated payment schedule on\n\t\t\t\t\t\t\t\t\t\tyour bill. If you do not activate your Device within 45 days of receipt, or if you cancel your Customer Agreement, you agree \n\t\t\t\t\t\t\t\t\t\tthat Verizon Wireless may charge, and you agree to pay, the entire remaining balance owed for your Device as soon as your next bill.\n\t\t\t\t\t\t\t\t\t\tIf your Device qualifies for an Early Upgrade offer, visit &lt;a href=\"#\" onclick=\"return false;\"&gt;verizonwireless.com/upgradeterms&lt;/a&gt; for further details, terms and conditions.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;\n\t\t\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;PREPAYMENT.&lt;/span&gt; You may pay the total amount due under this Agreement at any time before the final scheduled payment is due, \n\t\t\t\t\t\t\t\t\t\tand you will not have to pay a penalty.  If you pay more than the monthly  payment due any excess amount you pay will be credited to your account, \n\t\t\t\t\t\t\t\t\t\tand applied to any future charges pursuant to Section 2 above.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;\n\t\t\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;RISK OF LOSS: INSURANCE.&lt;/span&gt; You bear the entire risk of loss, theft or damage to the Device from any cause during \n\t\t\t\t\t\t\t\t\t\tthe term of this Agreement. Even if the Device is lost, stolen or damaged, you remain obligated for the total of the payments. We\n\t\t\t\t\t\t\t\t\t\trecommend that you obtain property insurance on the Device. You may obtain property insurance from others on goods purchased under this Agreement.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;\n\t\t\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;DEFAULT AND REMEDIES.&lt;/span&gt; You are in default under this Agreement if you fail to make any required payment when due or within\n\t\t\t\t\t\t\t\t\t\tfifteen (15) days of the due date; you cancel your Customer Agreement; we cancel your Customer Agreement for good cause; you\n\t\t\t\t\t\t\t\t\t\tbreach any covenant, representation or warranty hereunder, or default in the performance of any other obligation which is\n\t\t\t\t\t\t\t\t\t\tnot cured within ten (10) days after written notice to you; or we terminate your Service for breach\n\t\t\t\t\t\t\t\t\t\t(each a &amp;ldquo;Default&amp;rdquo;). To the extent permitted by applicable law, upon a Default we have the right to require you\n\t\t\t\t\t\t\t\t\t\tto pay immediately the entire remaining balance in full under this Agreement, and to pay us actual and reasonable costs of collection.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;\n\t\t\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;ASSIGNMENT.&lt;/span&gt; We may, without your consent, and without giving you notice, assign or transfer this Agreement or any payment or any\n\t\t\t\t\t\t\t\t\t\tother sums due or to become due hereunder. In such event our assignee will have, to the extent transferred or assigned to it, all our\n\t\t\t\t\t\t\t\t\t\trights, powers, privileges and remedies under the Agreement. You agree you will not assign this Agreement or any interest in it and will\n\t\t\t\t\t\t\t\t\t\tnot sell or offer to sell or transfer or enter into any lease with respect to the Device covered by this Agreement without our prior\n\t\t\t\t\t\t\t\t\t\twritten consent.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;\n\t\t\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;MILITARY LENDING ACT DISCLOSURE.&lt;/span&gt; If you are a member of the active military, or a spouse or dependent of the active military,\n\t\t\t\t\t\t\t\t\t\t the following apply (the federal government requires us to provide this notice to you even though we do not assess any of the fees referenced below):  \n\t\t\t\t\t\t\t\t\t\t Federal law provides important protections to members of the Armed Forces and their dependents relating to extensions of consumer credit. \n\t\t\t\t\t\t\t\t\t\t In general, the cost of consumer credit to a member of the Armed Forces and his or her dependent may not exceed an annual percentage rate of 36 percent. \n\t\t\t\t\t\t\t\t\t\t This rate must include, as applicable to the credit transaction or account: The costs associated with credit insurance premiums; \n\t\t\t\t\t\t\t\t\t\t fees for ancillary products sold in connection with the credit transaction; any application fee charged (other than certain application fees for specified credit \n\t\t\t\t\t\t\t\t\t\t transactions or accounts); and any participation fee charged (other than certain participation fees for a credit card account). \n\t\t\t\t\t\t\t\t\t\t Please refer to the Truth In Lending Act disclosures in your Agreement for information regarding your monthly payments. To hear this statement of rights under the \n\t\t\t\t\t\t\t\t\t\t Military Lending Act, please call 800-922-0204 and mention Military Lending Act.\n\t\t\t\t\t\t\t\t    &lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;\n\t\t\t\t\t\t\t\t\t\t&lt;span class=\"bold\"&gt;ELECTRONIC ACCESS TO AGREEMENT.&lt;/span&gt; By signing below, you acknowledge that you have access to Verizon Wireless&amp;#8217;\n\t\t\t\t\t\t\t\t\t\tWebsite at &lt;a href=\"http://www.verizonwireless.com\"&gt;www.verizonwireless.com&lt;/a&gt;, where a copy of this Agreement will be available to you.\n\t\t\t\t\t\t\t\t\t\tIf you want a paper copy of this Agreement, you may ask your sales representative to email or print a copy for you.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t&lt;/div&gt;\n\t\t\t\t\t\t\t\t\t\t\t&lt;div class=\"row\"&gt;\n\t\t\t\t\t\t\t\t&lt;h4&gt;BUYER&apos;S RIGHT TO CANCEL&lt;/h4&gt;\t\t\t\t\t\n\n\t\t\t\t\t\t    \t\t        &lt;p&gt;If you do not want the Device purchased under this Agreement, you may cancel by contacting Verizon Wireless \n\t\t\t\t\t\t\t\t\t\t\tby phone,online,or in person within 14 days of your acceptance. You must return your Device pursuant to Verizon Wireless&amp;#39; \n\t\t\t\t\t\t\t\t\t\t\tReturn Policy available at www.verizonwireless.com obtain a refund. If you do not return your Device within the return period, you will be charged for the entire\n\t\t\t\t\t\t\t\t\t\t\tremaining balance for your Device.&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t&lt;div class=\"row itemize\"&gt;\n\t\t\t\t\t\t\t\t\t&lt;h4&gt;ITEMIZATION OF AMOUNT FINANCED OF:&amp;nbsp; $469.99&lt;/h4&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;(A) CASH PRICE (excluding tax): &lt;span&gt;$469.99&lt;/span&gt;&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;(B) DOWN PAYMENT (if applicable): &lt;span&gt;$0.00&lt;/span&gt;&lt;/p&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t&lt;p&gt;(C) FINANCE CHARGE: &lt;span&gt;$0.00&lt;/span&gt;&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;(D) TAXES*: &lt;span&gt;$36.31&lt;/span&gt;&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;\n\t\t\t\t\t\t\t\t\t\t(E) AMOUNT FINANCED: \n\t\t\t\t\t\t\t\t\t\t&lt;span&gt;\n\t\t\t\t\t\t\t\t\t\t\t&lt;script&gt;if(&apos;469.99&apos;.indexOf(&apos;$&apos;) == -1) document.write(&apos;$&apos;);&lt;/script&gt;469.99\n\t\t\t\t\t\t\t\t\t\t&lt;/span&gt;\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;(the amount of credit provided to you on your behalf)&lt;/p&gt;\n\t\t    \t\t\t\t\t\t&lt;p&gt;* Not included in Amount Financed&lt;/p&gt;\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t&lt;/div&gt;\n\t\t\t\t\t\t\t\t&lt;div class=\"row fine bold\"&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;Do not sign this agreement before you read it or if it contains any blank spaces for\n\t\t\t\t\t\t\t\t\t\tinformation that is available at the time you sign this agreement.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;You are entitled to a completely filled-in copy of this agreement at the time you\n\t\t\t\t\t\t\t\t\t\tsign it. Keep it to protect your legal rights.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;Under the law, you have the right to pay off in advance the full amount due at any time.\n\t\t\t\t\t\t\t\t\t\tIf you desire to prepay the full amount due, the amount due will be furnished upon request.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;You have the right to redeem the property if repossessed for a default and, to require, under certain conditions, a resale of the property, if repossessed.&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;This contract is covered by state and federal laws, and you have the rights of a buyer under such laws.&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;ANY HOLDER OF THIS CONSUMER CREDIT CONTRACT IS SUBJECT TO ALL CLAIMS AND DEFENSES WHICH THE DEBTOR COULD\n\t\t\t\t\t\t\t\t\t\tASSERT AGAINST THE SELLER OF GOODS OR SERVICES OBTAINED UNDER THIS AGREEMENT OR WITH THE PROCEEDS HEREOF. RECOVERY\n\t\t\t\t\t\t\t\t\t\tHEREUNDER BY THE DEBTOR SHALL NOT EXCEED AMOUNTS PAID BY THE DEBTOR HEREUNDER.\n\t\t\t\t\t\t\t\t\t&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t&lt;p&gt;This is a retail installment sale agreement and not a lease. We have a limited return policy. Please ask for details.&lt;/p&gt;\n\t\t\t\t\t\t\t\t&lt;/div&gt;\n\t\t\t\t\t\t\t\t&lt;div class=\"row fine\"&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/div&gt;\n\t\t\t\t\t\t\t\t&lt;div class=\"row fine\"&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;p&gt;Version 06/27/2017&lt;/p&gt;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&lt;/div&gt;\n\t  \t\t\t\t\t    \t\t\t    \t]]&gt;</installmentContractDetailHTML></response></generateInstallmentContract></ServiceBody></POSServices>",
				"installmentContractDetails": {
					"locationCode": "M722801",
					"creditApplicationNum": 703971226,
					"orderNum": 1001739,
					"installmentType": "E",
					"installmentLoanNumber": "2000736445",
					"mobileNumber": "4174893929",
					"itemCode": "MNR12LL/A",
					"depletionType": "F",
					"creditClass": "B",
					"loanTerm": "24",
					"downPaymentAmount": "0.00",
					"firstMonthPaymentAmount": "19.65",
					"balanceLoanAmount": "469.99",
					"taxBasis": "F",
					"taxAmount": "36.31",
					"financeChargeAmount": "0.00",
					"financeChargedTaxAmount": "0.00",
					"deviceTaxPrice": "669.99",
					"loanStatus": "A",
					"mtnEffectiveDate": "Thu Apr 05 10:12:52 EDT 2018",
					"loanAmount": "469.99",
					"taxGroupID": "0000",
					"taxItemID": "000",
					"productId": "36222",
					"firstCollectedAmount": "N",
					"taxGeoAddressType": "S",
					"loanMonthlyPaymentAmount": "19.58",
					"loanTaxCollectedAmount": "36.31",
					"loanTaxableBaseAmount": "469.99",
					"downPaymentTaxCollectedAmount": "0.00",
					"loanTotalFinancialChargeAmount": "0.00",
					"financeChargedCollectedAmount": "0.00",
					"financeChargedTaxCollectedAmount": "0",
					"calculatedAPR": "0",
					"machineType": "D",
					"previousInstallmentLoanNumber": "0",
					"installmentPaymentSchedule": {
						"installmentPaymentScheduleCount": "24",
						"paymentDate": ["05/08/2018", "06/08/2018", "07/08/2018", "08/08/2018", "09/08/2018", "10/08/2018", "11/08/2018", "12/08/2018", "01/08/2019", "02/08/2019", "03/08/2019", "04/08/2019", "05/08/2019", "06/08/2019", "07/08/2019", "08/08/2019", "09/08/2019", "10/08/2019", "11/08/2019", "12/08/2019", "01/08/2020", "02/08/2020", "03/08/2020", "04/08/2020"]
					},
					"firstmonthPaymentCollected": "N",
					"stateOverrideTaxBasisAmount": "469.99",
					"deviceTaxOnContract": "36.31",
					"agreementPercentage": "100.0",
					"upgradeOptionCode": "DP",
					"upgradeDeviceCategoryText": "",
					"taxOnContractForDisplay": "36.31",
					"miramount": "0.00",
					"btaTaxWaiveIndicator": false
				}
			},
			"simId": null,
			"imei": "352066067937590",
			"idType": null,
			"monthlyCredit": 0.0,
			"visionFeatureList": null,
			"serviceAddress": {
				"id": null,
				"emailAddress": "PREETHA.SIVAKUMAR@VERIZON.COM",
				"phoneNumber": "7267752032",
				"lastName": "BOWER",
				"firstName": "RAVI",
				"zipCode": "65734",
				"orderId": null,
				"userId": null,
				"npaNxxNumber": null,
				"address1": "7483 STATE HIGHWAY 37 LOT 31",
				"address2": null,
				"city": "Purdy",
				"state": "MO",
				"addressVerified": true,
				"textAlertOptin": false,
				"newsLetterOptin": false,
				"paperFreeBillingIndicatorFlag": false,
				"middleName": null,
				"firmName": null,
				"businessName": null,
				"apartmentNum": "31",
				"addressDirection": "",
				"poBox": "",
				"streetNumber": "7483",
				"streetName": "STATE HIGHWAY 37",
				"streetType": "",
				"ruralRoute": null,
				"ruralDel": "",
				"zipCode4": null,
				"zipCode5": null,
				"faxNumber": null,
				"addressType": null,
				"country": "",
				"prefix": null,
				"suffix": null,
				"postbox": null,
				"companyname": null,
				"ruralrte": "",
				"county": null,
				"address3": null,
				"postalcode": "65734",
				"version": 0,
				"lastModifiedDate": null,
				"addressConfirmationStatus": null
			},
			"dacc": "00970",
			"simItem": {
				"id": "sim001",
				"quantity": 0,
				"type": "4006",
				"skuId": "sku401968",
				"productId": "sim760069",
				"sorId": "EMBD4GSIM-N",
				"itemAmount": 0.0,
				"itemAmountOriginal": null,
				"dueMonthly": 0.0,
				"dueMonthlyOriginal": null,
				"itemDiscount": 0.0,
				"displayName": "4G SIM Card",
				"skuDisplayName": null,
				"listPrice": 0.0,
				"rawTotalAmount": 0.0,
				"pricingDetails": null,
				"orderId": null,
				"version": 0,
				"delete": false,
				"inventoryLevel": 0,
				"taxDetails": null,
				"itemTaxes": 0.0,
				"simId": null,
				"newSim": false,
				"category": "VirtualSim",
				"saccCode": "00659",
				"lastModifiedDate": 1522937305252,
				"deviceLineItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
				"cpe": false
			},
			"billingSystem": null,
			"numberPortabilityVO": null,
			"lastModifiedDate": 1522937305252,
			"securityDeposit": 0,
			"securityDepositWaiveCode": null,
			"waiveActivationFees": false,
			"stackableDataPromoCorrelationId": null,
			"meaCode": "MM1",
			"upgradeReasonCodes": "EA",
			"oldEsnNumber": "89148000001659093974",
			"network4gIndicator": true,
			"minNumber": null,
			"transferredFromMtn": null,
			"twoDUpgradeItem": false,
			"existingDeviceSorId": "MGCK2LL/A",
			"existingPlanSorId": null,
			"twoDUpgradeDownpaymentPercentage": 0.0,
			"edgeUpBuyOutFlag": false,
			"edgeUpDetails": null,
			"edgeupAmount": 0.0,
			"edgeBuyoutAmount": 0.0,
			"upgradeOptionCode": null,
			"promoBadgeMessages": null,
			"offerType": null,
			"downPaymentPercentage": null,
			"edgeEligibleInd": true,
			"deviceType": "SMARTPHONE",
			"deviceManufacturerName": "Apple",
			"buyOutDetails": null,
			"devicePaymentConfig": {
				"configId": null,
				"term": 24,
				"percentage": 100,
				"startDate": 1505462400000,
				"endDate": 253402250400000,
				"upgradeOptionCode": "DP",
				"description": null,
				"devicePaymentCategoryType": null
			},
			"itemCost": "769.0",
			"freeOvernightEligible": false,
			"sorSkuId": "Retail",
			"trunkMTN": null,
			"branchMTN": null,
			"graftAction": null,
			"shipCommitInd": null,
			"sorDeviceCategory": "4G Smartphone",
			"spoAction": null,
			"lineSpoImpacts": null,
			"vehicleColor": "",
			"sameDayDelivery": true,
			"firstActiveTabletInd": "N",
			"countOfPhonesOnShareplan": 4,
			"seoUrl": "smartphones/apple-iphone-7-plus/",
			"storeId": null,
			"originalUpgradeFee": 0.0,
			"priceForFullRetailPriceListID": 0.0,
			"originalActivationFee": 0.0,
			"flow": "EUP",
			"dmdDeviceCategory": null,
			"userRemovedExistingFeatures": null,
			"e911AddressDetails": null,
			"rio": false,
			"hostCommerceItemId": null,
			"promotions": [{
				"barCodeId": null,
				"promoAmount": "200.00",
				"itemAmount": null,
				"itemType": "ITA",
				"promoName": "UAT 200 OFF SMARTPHONE PREVIOUS DEVICE RETURN REQ",
				"sedOffer": "105261",
				"itemCode": "MNR12LL/A",
				"promoDescription": "UAT 200 Off Smartphone - Previous Device Return Required"
			}],
			"vzwSbdOfferlist": null,
			"simCPE": false,
			"deviceNumber": null,
			"deviceTypeIndicator": null,
			"deviceSorId": null,
			"deviceCapabilityInd": null,
			"edgeContract": true,
			"numberShare": false,
			"upgradeFeeWaived": false,
			"btaeligibileFlag": true
		}],
		"planList": [{
			"id": "SDC49106b37a944408f4652b4abc046a366_plan_1",
			"quantity": 0,
			"type": null,
			"skuId": "sku2580028",
			"productId": "plan2880001",
			"sorId": "99230",
			"itemAmount": 0.0,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 160.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Go Unlimited",
			"skuDisplayName": null,
			"listPrice": 160.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "SDC49106b37a944408f4652b4abc046a366_plan_1",
				"orderId": "SDC49106b37a944408f4652b4abc046a366",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 160.0,
				"offerName": null,
				"creationDate": 1522937560045,
				"lastModifiedDate": 1522937560045,
				"version": 1
			}],
			"orderId": "SDC49106b37a944408f4652b4abc046a366",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"planLevel": "Account Level",
			"lastModifiedDate": 1522937305274,
			"sharedPlan": true,
			"cpcDone": false,
			"sorCategoryCode": "61",
			"upgradeDevices": [{
				"name": "iPhone&reg; 7 Plus",
				"price": "40.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "4174893929",
				"listPrice": 40.0,
				"deviceLineItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
				"discountPriceVal": "0.00"
			}],
			"newDevices": [],
			"existingDevices": [{
				"name": "Apple&reg; iPhone&reg; 6 16GB in Silver",
				"price": "40.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "4174894461",
				"listPrice": 40.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}, {
				"name": "Apple&reg; iPhone&reg; 6 16GB in Silver",
				"price": "40.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "4175401349",
				"listPrice": 40.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}, {
				"name": "Apple&reg; iPhone&reg; 6 16GB in Silver",
				"price": "40.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "4176690341",
				"listPrice": 40.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}],
			"activationFees": [{
				"contractId": "0002",
				"amount": 40.0
			}, {
				"contractId": "0012",
				"amount": 40.0
			}, {
				"contractId": "0048",
				"amount": 30.0
			}],
			"ecpdItemAmount": null,
			"ecpdItemDiscount": null
		}],
		"plans": {
			"dueMonthly": "160.00",
			"dueToday": "0.00",
			"planOnlyDueMonthly": "160.00",
			"items": [{
				"planType": "Go Unlimited",
				"lineAccessCharges": [{
					"name": "SMARTPHONE",
					"mtn": "4174893929",
					"price": "40.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				}],
				"accountAccess": {
					"name": "Go Unlimited",
					"mtn": null,
					"price": "160.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": "160.00",
				"spoBadgeMessage": null,
				"planDisplayName": "Go Unlimited",
				"planImageURL": null,
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null
			}],
			"upgradeDevices": [{
				"name": "iPhone&reg; 7 Plus",
				"price": "40.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "4174893929",
				"listPrice": 40.0,
				"deviceLineItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
				"discountPriceVal": "0.00"
			}],
			"newDevices": [],
			"existingDevices": [{
				"name": "Apple&reg; iPhone&reg; 6 16GB in Silver",
				"price": "40.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "4174894461",
				"listPrice": 40.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}, {
				"name": "Apple&reg; iPhone&reg; 6 16GB in Silver",
				"price": "40.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "4175401349",
				"listPrice": 40.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}, {
				"name": "Apple&reg; iPhone&reg; 6 16GB in Silver",
				"price": "40.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "4176690341",
				"listPrice": 40.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}],
			"dueMonthlyPlanWithLAC": "320.00",
			"discountedDueMonthlyPlanWithLAC": "0.00"
		},
		"featureList": [{
			"id": "SDC49106b37a944408f4652b4abc046a366_feature_1",
			"quantity": 1,
			"type": "INSUR,D",
			"skuId": "sku401064",
			"productId": "sfo80072",
			"sorId": "66332",
			"itemAmount": 0.0,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Decline Equipment Protection",
			"skuDisplayName": null,
			"listPrice": 0.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "SDC49106b37a944408f4652b4abc046a366_feature_1",
				"orderId": "SDC49106b37a944408f4652b4abc046a366",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 0.0,
				"offerName": null,
				"creationDate": 1522937560045,
				"lastModifiedDate": 1522937560045,
				"version": 1
			}],
			"orderId": "SDC49106b37a944408f4652b4abc046a366",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
			"featureCharge": 0.0,
			"featureType": "INS",
			"lastModifiedDate": 1522937305262
		}, {
			"id": "SDC49106b37a944408f4652b4abc046a366_feature_2",
			"quantity": 0,
			"type": null,
			"skuId": "sku2560176",
			"productId": "sfo80079",
			"sorId": "85432",
			"itemAmount": 0.0,
			"itemAmountOriginal": null,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Phone Plan",
			"skuDisplayName": null,
			"listPrice": 0.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "SDC49106b37a944408f4652b4abc046a366_feature_2",
				"orderId": null,
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 0.0,
				"offerName": null,
				"creationDate": 1522937560045,
				"lastModifiedDate": 1522937560045,
				"version": 1
			}],
			"orderId": null,
			"version": 0,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
			"featureCharge": 0.0,
			"featureType": "LAC",
			"lastModifiedDate": null
		}],
		"accessoryList": null,
		"paymentGroup": [{
			"classtype": "com.vzw.order.vo.BillToAccount",
			"id": null,
			"orderId": null,
			"paymentMethod": "BTA",
			"creditCardValidated": false,
			"amount": 68.62,
			"billingAddress": {
				"id": null,
				"emailAddress": "PREETHA.SIVAKUMAR@VERIZON.COM",
				"phoneNumber": "7267752032",
				"lastName": "BOWER",
				"firstName": "RAVI",
				"zipCode": "65734",
				"orderId": null,
				"userId": null,
				"npaNxxNumber": null,
				"address1": "7483 STATE HIGHWAY 37 LOT 31",
				"address2": null,
				"city": "Purdy",
				"state": "MO",
				"addressVerified": true,
				"textAlertOptin": false,
				"newsLetterOptin": false,
				"paperFreeBillingIndicatorFlag": false,
				"middleName": null,
				"firmName": null,
				"businessName": null,
				"apartmentNum": "31",
				"addressDirection": "",
				"poBox": "",
				"streetNumber": "7483",
				"streetName": "STATE HIGHWAY 37",
				"streetType": "",
				"ruralRoute": null,
				"ruralDel": "",
				"zipCode4": null,
				"zipCode5": null,
				"faxNumber": null,
				"addressType": null,
				"country": "",
				"prefix": null,
				"suffix": null,
				"postbox": null,
				"companyname": null,
				"ruralrte": "",
				"county": null,
				"address3": null,
				"postalcode": "65734",
				"version": 0,
				"lastModifiedDate": null,
				"addressConfirmationStatus": null
			},
			"version": 0,
			"lastModifiedDate": null,
			"pieEncrypted": false,
			"btaEligible": true,
			"accountNumber": "0287799083-00001",
			"btaAmntLimit": 750.0,
			"btaAmntRemaining": 232.93,
			"btaAmntMinusCurrentOrder": 164.31
		}],
		"contactInfo": {
			"id": null,
			"emailAddress": "PREETHA.SIVAKUMAR@VERIZON.COM",
			"phoneNumber": "7267752032",
			"lastName": "BOWER",
			"firstName": "RAVI",
			"zipCode": "65734",
			"orderId": null,
			"userId": null,
			"npaNxxNumber": null,
			"address1": "7483 STATE HIGHWAY 37 LOT 31",
			"address2": null,
			"city": "Purdy",
			"state": "MO",
			"addressVerified": true,
			"textAlertOptin": false,
			"newsLetterOptin": false,
			"paperFreeBillingIndicatorFlag": false,
			"middleName": null,
			"firmName": null,
			"businessName": null,
			"apartmentNum": "31",
			"addressDirection": "",
			"poBox": "",
			"streetNumber": "7483",
			"streetName": "STATE HIGHWAY 37",
			"streetType": "",
			"ruralRoute": null,
			"ruralDel": "",
			"zipCode4": null,
			"zipCode5": null,
			"faxNumber": null,
			"addressType": null,
			"country": "",
			"prefix": null,
			"suffix": null,
			"postbox": null,
			"companyname": null,
			"ruralrte": "",
			"county": null,
			"address3": null,
			"postalcode": "65734",
			"version": 0,
			"lastModifiedDate": null,
			"addressConfirmationStatus": null
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": {
			"tradeInDeviceDppMsg": "We'll send you a prepaid box to mail in your trade-in. This is only an estimate until we receive and appraise your device.",
			"warningMessage": null,
			"tradeInDeviceHeaderMsg": "You'll see an estimated $194.00 credit within 1-2 bill cycles.",
			"tradeInCredit": "-194.00",
			"tradeInDevices": [{
				"activeDevice": null,
				"tradeInCredit": "87.00",
				"tradeInDeviceFooter": null,
				"offerDetailsMsg": null,
				"tradeInDeviceHeaderMsg": null,
				"tradeInCreditMsg": "Trade-in credit: $87.00",
				"bicApplied": null,
				"color": "Silver",
				"dataWipeText": null,
				"deviceBrand": null,
				"deviceId": "ID: 359296069735380",
				"discAmt": null,
				"disconnectedDate": null,
				"displayName": "iPhone 6",
				"dppCredit": "0.0",
				"dppAppliedCommerceItemId": null,
				"dppAppliedMdn": null,
				"errorMessage": null,
				"modalOsName": null,
				"modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone-6-silver?$device-lg$",
				"modelName": null,
				"mtn": null,
				"nickName": null,
				"originalAppraisalPrice": "87.00",
				"price": null,
				"promoCodeError": null,
				"promoCreditType": null,
				"promoQualifyMessage": null,
				"promoValue": null,
				"shortDisplayName": null,
				"size": "16GB",
				"success": true,
				"regularPromoApplied": null,
				"existingAppraisedReferenceId": null,
				"appraiseTradeInDeviceWithOutDeviceId": false,
				"flow": null
			}],
			"orginaltradeInCredit": null
		},
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "68.62",
		"totalDueMonthly": "19.58",
		"subTotalDueToday": "0.00",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "38.62",
		"employeeDiscount": "0.00",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"ispuEligibleFlag": true,
			"addressInfo": {
				"firstName": "RAVI",
				"lastName": "BOWER",
				"companyName": null,
				"address1": "7483 STATE HIGHWAY 37 LOT 31",
				"address2": null,
				"city": "Purdy",
				"state": "MO",
				"zipcode": "65734",
				"businessName": null,
				"postalCode": null,
				"email": "PREETHA.SIVAKUMAR@VERIZON.COM",
				"phoneNumber": "7267752032"
			},
			"contactInfo": {
				"emailAddress": "PREETHA.SIVAKUMAR@VERIZON.COM",
				"phoneNumber": "7267752032",
				"firstName": "RAVI",
				"lastName": "BOWER",
				"smsMdn": null,
				"activeSMSCapableMtnList": ["4174894461", "4175401349", "4174893929", "4176690341"]
			},
			"shippingTypesInfo": [{
				"estimatedDeliveryDate": "2018-04-09 09:12:52",
				"estimatedDeliveryDateText": "Monday 4/9 by 9:12AM",
				"shippingDescription": "Free 2 Day by 8pm",
				"shippingOptionId": "SHP002",
				"shippingCost": "0.00",
				"shortDescription": "Free 2 Day by 8pm",
				"active": true,
				"addedShippingOptionId": true,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Mon, Apr 9 if ordered by 4pm today. Signature required.",
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-04-06 09:12:52",
				"estimatedDeliveryDateText": "Friday 4/6 by 9:12AM",
				"shippingDescription": "Next Day by 8pm",
				"shippingOptionId": "SHP004",
				"shippingCost": "12.99",
				"shortDescription": "Next Day by 8pm",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Fri, Apr 6. Next Day by 8pm. Signature required.",
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-04-06 09:12:52",
				"estimatedDeliveryDateText": "Friday 4/6 by 9:12AM",
				"shippingDescription": "Next Day by 10:30am",
				"shippingOptionId": "SHP005",
				"shippingCost": "14.99",
				"shortDescription": "Next Day by 10:30am",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Fri, Apr 6. Next Day by 10:30am. Signature required.",
				"sddAvailableWindows": null
			}],
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": null,
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": null,
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": true,
			"tradeInAddress": {
				"firstName": "RAVI",
				"lastName": "BOWER",
				"address1": "7483 STATE HIGHWAY 37 LOT 31",
				"address2": null,
				"city": "Purdy",
				"state": "MO",
				"zipcode": "65734",
				"companyName": null
			},
			"nonSddEligibleMsg": null,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": true,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "RAVI",
				"lastName": "BOWER",
				"businessName": null,
				"zipcode": "65734",
				"state": "MO",
				"address2": null,
				"address1": "7483 STATE HIGHWAY 37 LOT 31",
				"companyName": null,
				"city": "Purdy"
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": "XXXX-XXXX-XXXX-0001",
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": null,
				"creditCardExpMonth": null,
				"creditCardExpYear": null,
				"billingZipCode": null,
				"creditCardType": null,
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "BTA",
			"giftCardList": [],
			"savedCardInfo": [],
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
			"expirationYears": ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"]
		},
		"devices": {
			"dueMonthly": 19.58,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 19.58,
			"dueToday": 0.0,
			"accessories": [],
			"accessoriesBundle": [],
			"items": [{
				"deviceName": "iPhone&reg; 7 Plus",
				"dueMonthly": "19.58",
				"dueToday": "0.00",
				"upgradeFee": "30.00",
				"activationFee": "0.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": "27.92",
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": true,
				"mtn": "4174893929",
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Decline Equipment Protection",
					"mtn": null,
					"price": "0.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"optionalFeatures": [],
				"installmentBalance": "469.99",
				"edgeRetailPrice": "669.99",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": null,
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 19.58,
				"deviceLACFee": "40.00",
				"manufactureName": "Apple",
				"color": "Black",
				"size": "32GB",
				"displayName": "iPhone&reg; 7 Plus",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "669.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": null,
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": true,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"promoOfferText": "UAT 200 OFF SMARTPHONE PREVIOUS DEVICE RETURN REQ",
				"promoApplied": true,
				"commerceItemId": "SDC49106b37a944408f4652b4abc046a366_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "EUP",
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"edgeDevice": true,
				"eupdevice": false,
				"accessory": false,
				"disountedInstantCreditAmt": "0.00"
			}],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": null
		},
		"dueMonthlyView": {
			"title": "Due Monthly (device only)",
			"dueMonthlyPrice": "19.58",
			"items": [{
				"name": "iPhone&reg; 7 Plus",
				"description": "iPhone&reg; 7 Plus",
				"manufacturer": "Apple",
				"color": "Black",
				"size": "32GB",
				"priceBreakDown": [{
					"lable": "Decline Equipment Protection",
					"price": "0.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Device Payment",
					"price": "19.58",
					"description": "For 24 months, 0% APR with down payment. Reduced retail price: <span class='textDecLineThrough red'>$669.99</span> $469.99",
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 19.58,
					"itemStrikeThroughPrice": 27.92,
					"noOfBicOccurences": 0
				}],
				"edge": true
			}],
			"tmpMd": null
		},
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false
	}
};