const pdpJSON = {
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "productDetails": {
      "badgeRetailIconImageName": null,
      "manufacturerDisplayName": "Samsung",
      "badgeTwoYearToolTip": null,
      "lineAccess": null,
      "dealInStoreStaticUrl": "https://forms.verizonwireless.com/dgf/optin/2012/06282012_omni_thankyou/index.html",
      "cqContent": null,
      "badgeEdgeIconImageName": null,
      "brandName": "Samsung",
      "categoryName": "smartphones",
      "rectangularBadgeText": null,
      "badgeTwoYearIconImageName": null,
      "badgeRetailDisplayName": null,
      "deviceType": "4G Smartphone",
      "badgeEdgeToolTip": null,
      "skuDetails": [{
        "colorName": "Orchid Gray",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Orchid_Gray?$device-lg$",
        "upgradeOptionEllPDPLbl50": "Buy the Galaxy S8 and upgrade to a new annual upgrade eligible device every year.",
        "promotionDetails": null,
        "restrictionFlag": false,
        "upgradeOptionEllPDPLbl70": "Buy the Galaxy S8 and upgrade to a new Galaxy S8 after 70% is paid off.",
        "devicePrice": [{
          "mailInRebateAmount": 0.0,
          "priceListId": "edgeRemainingMonthPriceListId",
          "bicOfferApplied": false,
          "ecpdDiscountOffer": false,
          "bicAdditionalContractText": null,
          "edgeFullRetailPrice": 756.0,
          "alwaysEligibleDownPaymentPercentage": null,
          "mailInRebateText": null,
          "sedEcpdDiscountPercentage": 0.0,
          "selected": true,
          "edgeEnabled": true,
          "earlyTerminationText": null,
          "rebateAmount": 0.0,
          "orgiginalMonthlyPrice": 0.0,
          "alwaysEligibleDownPaymentPercentageText": null,
          "orignalFullRetailPrice": 0.0,
          "edgeDownpayment": "0.00",
          "mailInRebateIndicator": false,
          "edgeType": null,
          "upgradeFee": 0.0,
          "activationFee": 30.0,
          "bicDiscountedContractPrice": 0.0,
          "waivedActivationFeePromo": false,
          "discountPrice": null,
          "ecpdDiscount": 0.0,
          "bicContractPrice": 0.0,
          "contractDetail": "/mo.",
          "contractPrice": "31.50",
          "contractTerm": 99,
          "originalPrice": 31.5,
          "creditOptionVOList": null,
          "fullRetailPrice": 756.0,
          "waivedUpgradeFeePromo": false,
          "contractTitle": "$0 Down (for qualified customers) $31.50/mo for 24 months; 0% APR Retail Price: $756.00",
          "contractName": "24 Monthly Payments",
          "contractToDevicePaymentEligibilityInd": false,
          "promotionDetails": null,
          "badgePromoContentText": null,
          "alwaysEligibleForUpgrade": false,
          "puEligibleFlag": false
        }, {
          "mailInRebateAmount": 0.0,
          "priceListId": "fullRetailPriceListId",
          "bicOfferApplied": false,
          "ecpdDiscountOffer": false,
          "bicAdditionalContractText": null,
          "edgeFullRetailPrice": 756.0,
          "alwaysEligibleDownPaymentPercentage": null,
          "mailInRebateText": null,
          "sedEcpdDiscountPercentage": 0.0,
          "selected": false,
          "edgeEnabled": false,
          "earlyTerminationText": null,
          "rebateAmount": 0.0,
          "orgiginalMonthlyPrice": 0.0,
          "alwaysEligibleDownPaymentPercentageText": null,
          "orignalFullRetailPrice": 0.0,
          "edgeDownpayment": "0.00",
          "mailInRebateIndicator": false,
          "edgeType": null,
          "upgradeFee": 0.0,
          "activationFee": 0.0,
          "bicDiscountedContractPrice": 0.0,
          "waivedActivationFeePromo": false,
          "discountPrice": null,
          "ecpdDiscount": 0.0,
          "bicContractPrice": 0.0,
          "contractDetail": null,
          "contractPrice": "756.00",
          "contractTerm": 0,
          "originalPrice": 756.0,
          "creditOptionVOList": null,
          "fullRetailPrice": 756.0,
          "waivedUpgradeFeePromo": false,
          "contractTitle": "No Early Termination Fee",
          "contractName": "Retail Price",
          "contractToDevicePaymentEligibilityInd": false,
          "promotionDetails": null,
          "badgePromoContentText": null,
          "alwaysEligibleForUpgrade": false,
          "puEligibleFlag": false
        }],
        "skuImageName": "Samsung_Galaxy_S8_Orchid_Gray",
        "upgradeOptionEllPDPTip70": "First, buy Galaxy S8 on monthly device payments. After 30 days and 70% of your Galaxy S8 is paid off, you can trade in and upgrade to the newest.",
        "selected": false,
        "upgradeOptionEllPDPTip50": "Buy the Galaxy S8 on device payment. After 30 days and 50% of your Galaxy S8 is paid off, you can trade it in and upgrade to the newest one.\n<br/>\nSubject to <a href=\"http://www.verizonwireless.com/support/upgrade-program-legal/\">Upgrade Program Terms and Conditions</a>.",
        "restrictionMessage": null,
        "sameDayDeliveryFlag": true,
        "capacity": "64GB",
        "inventoryStatus": 1002,
        "deviceSkuId": "sku2360003",
        "devicePaymentPercentage": "50",
        "deviceSorId": "SMG950UZVV",
        "skuListDiscountPricing": {
          "skuListPrice": [{
            "priceListId": "edgeFullRetailPriceListId",
            "price": 756.0
          }, {
            "priceListId": "twoYearPriceListId",
            "price": 249.99
          }, {
            "priceListId": "edgeFirstMonthPriceListId",
            "price": 31.5
          }, {
            "priceListId": "fullRetailPriceListId",
            "price": 756.0
          }, {
            "priceListId": "edgeRemainingMonthPriceListId",
            "price": 31.5
          }],
          "skuDiscountPrice": []
        },
        "colorImage": null,
        "upgradeOptionCode": "UO",
        "annualUpgradeEligible": true,
        "displayName": "Samsung Galaxy S8 64GB in Orchid Gray",
        "colorCode": "#868499",
        "mobileAppImageName": null,
        "shippingDateLabel": "Ships byOct 06",
        "shippingDateStatusCode": 1002,
        "carouselImages": ["https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Orchid_Gray", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8CHAR_a_005_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8CHAR_a_009_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8CHAR_a_013_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8CHAR_b_001_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8CHAR_b_005_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8CHAR_b_009_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8CHAR_b_013_spin"]
      }, {
        "colorName": "Arctic Silver",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Silver?$device-lg$",
        "upgradeOptionEllPDPLbl50": "Buy the Galaxy S8 and upgrade to a new annual upgrade eligible device every year.",
        "promotionDetails": null,
        "restrictionFlag": false,
        "upgradeOptionEllPDPLbl70": "Buy the Galaxy S8 and upgrade to a new Galaxy S8 after 70% is paid off.",
        "devicePrice": [{
          "mailInRebateAmount": 0.0,
          "priceListId": "edgeRemainingMonthPriceListId",
          "bicOfferApplied": false,
          "ecpdDiscountOffer": false,
          "bicAdditionalContractText": null,
          "edgeFullRetailPrice": 756.0,
          "alwaysEligibleDownPaymentPercentage": null,
          "mailInRebateText": null,
          "sedEcpdDiscountPercentage": 0.0,
          "selected": true,
          "edgeEnabled": true,
          "earlyTerminationText": null,
          "rebateAmount": 0.0,
          "orgiginalMonthlyPrice": 0.0,
          "alwaysEligibleDownPaymentPercentageText": null,
          "orignalFullRetailPrice": 0.0,
          "edgeDownpayment": "0.00",
          "mailInRebateIndicator": false,
          "edgeType": null,
          "upgradeFee": 0.0,
          "activationFee": 30.0,
          "bicDiscountedContractPrice": 0.0,
          "waivedActivationFeePromo": false,
          "discountPrice": null,
          "ecpdDiscount": 0.0,
          "bicContractPrice": 0.0,
          "contractDetail": "/mo.",
          "contractPrice": "31.50",
          "contractTerm": 99,
          "originalPrice": 31.5,
          "creditOptionVOList": null,
          "fullRetailPrice": 756.0,
          "waivedUpgradeFeePromo": false,
          "contractTitle": "$0 Down (for qualified customers) $31.50/mo for 24 months; 0% APR Retail Price: $756.00",
          "contractName": "24 Monthly Payments",
          "contractToDevicePaymentEligibilityInd": false,
          "promotionDetails": null,
          "badgePromoContentText": null,
          "alwaysEligibleForUpgrade": false,
          "puEligibleFlag": false
        }, {
          "mailInRebateAmount": 0.0,
          "priceListId": "fullRetailPriceListId",
          "bicOfferApplied": false,
          "ecpdDiscountOffer": false,
          "bicAdditionalContractText": null,
          "edgeFullRetailPrice": 756.0,
          "alwaysEligibleDownPaymentPercentage": null,
          "mailInRebateText": null,
          "sedEcpdDiscountPercentage": 0.0,
          "selected": false,
          "edgeEnabled": false,
          "earlyTerminationText": null,
          "rebateAmount": 0.0,
          "orgiginalMonthlyPrice": 0.0,
          "alwaysEligibleDownPaymentPercentageText": null,
          "orignalFullRetailPrice": 0.0,
          "edgeDownpayment": "0.00",
          "mailInRebateIndicator": false,
          "edgeType": null,
          "upgradeFee": 0.0,
          "activationFee": 0.0,
          "bicDiscountedContractPrice": 0.0,
          "waivedActivationFeePromo": false,
          "discountPrice": null,
          "ecpdDiscount": 0.0,
          "bicContractPrice": 0.0,
          "contractDetail": null,
          "contractPrice": "756.00",
          "contractTerm": 0,
          "originalPrice": 756.0,
          "creditOptionVOList": null,
          "fullRetailPrice": 756.0,
          "waivedUpgradeFeePromo": false,
          "contractTitle": "No Early Termination Fee",
          "contractName": "Retail Price",
          "contractToDevicePaymentEligibilityInd": false,
          "promotionDetails": null,
          "badgePromoContentText": null,
          "alwaysEligibleForUpgrade": false,
          "puEligibleFlag": false
        }],
        "skuImageName": "Samsung_Galaxy_S8_Silver",
        "upgradeOptionEllPDPTip70": "First, buy Galaxy S8 on monthly device payments. After 30 days and 70% of your Galaxy S8 is paid off, you can trade in and upgrade to the newest.",
        "selected": true,
        "upgradeOptionEllPDPTip50": "Buy the Galaxy S8 on device payment. After 30 days and 50% of your Galaxy S8 is paid off, you can trade it in and upgrade to the newest one.\n<br/>\nSubject to <a href=\"http://www.verizonwireless.com/support/upgrade-program-legal/\">Upgrade Program Terms and Conditions</a>.",
        "restrictionMessage": null,
        "sameDayDeliveryFlag": true,
        "capacity": "64GB",
        "inventoryStatus": 1000,
        "deviceSkuId": "sku2360001",
        "devicePaymentPercentage": "50",
        "deviceSorId": "SMG950UZSV",
        "skuListDiscountPricing": {
          "skuListPrice": [{
            "priceListId": "edgeFullRetailPriceListId",
            "price": 756.0
          }, {
            "priceListId": "twoYearPriceListId",
            "price": 249.99
          }, {
            "priceListId": "edgeFirstMonthPriceListId",
            "price": 31.5
          }, {
            "priceListId": "fullRetailPriceListId",
            "price": 756.0
          }, {
            "priceListId": "edgeRemainingMonthPriceListId",
            "price": 31.5
          }],
          "skuDiscountPrice": []
        },
        "colorImage": null,
        "upgradeOptionCode": "UO",
        "annualUpgradeEligible": true,
        "displayName": "Samsung Galaxy S8 64GB in Arctic Silver",
        "colorCode": "#CCCCCC",
        "mobileAppImageName": null,
        "shippingDateLabel": null,
        "shippingDateStatusCode": 1000,
        "carouselImages": ["https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Silver", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8SLVR_a_005_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8SLVR_a_009_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8SLVR_a_013_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8SLVR_b_001_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8SLVR_b_005_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8SLVR_b_009_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8SLVR_b_013_spin"]
      }, {
        "colorName": "Midnight Black",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Black?$device-lg$",
        "upgradeOptionEllPDPLbl50": "Buy the Galaxy S8 and upgrade to a new annual upgrade eligible device every year.",
        "promotionDetails": null,
        "restrictionFlag": false,
        "upgradeOptionEllPDPLbl70": "Buy the Galaxy S8 and upgrade to a new Galaxy S8 after 70% is paid off.",
        "devicePrice": [{
          "mailInRebateAmount": 0.0,
          "priceListId": "edgeRemainingMonthPriceListId",
          "bicOfferApplied": false,
          "ecpdDiscountOffer": false,
          "bicAdditionalContractText": null,
          "edgeFullRetailPrice": 756.0,
          "alwaysEligibleDownPaymentPercentage": null,
          "mailInRebateText": null,
          "sedEcpdDiscountPercentage": 0.0,
          "selected": true,
          "edgeEnabled": true,
          "earlyTerminationText": null,
          "rebateAmount": 0.0,
          "orgiginalMonthlyPrice": 0.0,
          "alwaysEligibleDownPaymentPercentageText": null,
          "orignalFullRetailPrice": 0.0,
          "edgeDownpayment": "0.00",
          "mailInRebateIndicator": false,
          "edgeType": null,
          "upgradeFee": 0.0,
          "activationFee": 30.0,
          "bicDiscountedContractPrice": 0.0,
          "waivedActivationFeePromo": false,
          "discountPrice": null,
          "ecpdDiscount": 0.0,
          "bicContractPrice": 0.0,
          "contractDetail": "/mo.",
          "contractPrice": "31.50",
          "contractTerm": 99,
          "originalPrice": 31.5,
          "creditOptionVOList": null,
          "fullRetailPrice": 756.0,
          "waivedUpgradeFeePromo": false,
          "contractTitle": "$0 Down (for qualified customers) $31.50/mo for 24 months; 0% APR Retail Price: $756.00",
          "contractName": "24 Monthly Payments",
          "contractToDevicePaymentEligibilityInd": false,
          "promotionDetails": null,
          "badgePromoContentText": null,
          "alwaysEligibleForUpgrade": false,
          "puEligibleFlag": false
        }, {
          "mailInRebateAmount": 0.0,
          "priceListId": "fullRetailPriceListId",
          "bicOfferApplied": false,
          "ecpdDiscountOffer": false,
          "bicAdditionalContractText": null,
          "edgeFullRetailPrice": 756.0,
          "alwaysEligibleDownPaymentPercentage": null,
          "mailInRebateText": null,
          "sedEcpdDiscountPercentage": 0.0,
          "selected": false,
          "edgeEnabled": false,
          "earlyTerminationText": null,
          "rebateAmount": 0.0,
          "orgiginalMonthlyPrice": 0.0,
          "alwaysEligibleDownPaymentPercentageText": null,
          "orignalFullRetailPrice": 0.0,
          "edgeDownpayment": "0.00",
          "mailInRebateIndicator": false,
          "edgeType": null,
          "upgradeFee": 0.0,
          "activationFee": 0.0,
          "bicDiscountedContractPrice": 0.0,
          "waivedActivationFeePromo": false,
          "discountPrice": null,
          "ecpdDiscount": 0.0,
          "bicContractPrice": 0.0,
          "contractDetail": null,
          "contractPrice": "756.00",
          "contractTerm": 0,
          "originalPrice": 756.0,
          "creditOptionVOList": null,
          "fullRetailPrice": 756.0,
          "waivedUpgradeFeePromo": false,
          "contractTitle": "No Early Termination Fee",
          "contractName": "Retail Price",
          "contractToDevicePaymentEligibilityInd": false,
          "promotionDetails": null,
          "badgePromoContentText": null,
          "alwaysEligibleForUpgrade": false,
          "puEligibleFlag": false
        }],
        "skuImageName": "Samsung_Galaxy_S8_Black",
        "upgradeOptionEllPDPTip70": "First, buy Galaxy S8 on monthly device payments. After 30 days and 70% of your Galaxy S8 is paid off, you can trade in and upgrade to the newest.",
        "selected": false,
        "upgradeOptionEllPDPTip50": "Buy the Galaxy S8 on device payment. After 30 days and 50% of your Galaxy S8 is paid off, you can trade it in and upgrade to the newest one.\n<br/>\nSubject to <a href=\"http://www.verizonwireless.com/support/upgrade-program-legal/\">Upgrade Program Terms and Conditions</a>.",
        "restrictionMessage": null,
        "sameDayDeliveryFlag": true,
        "capacity": "64GB",
        "inventoryStatus": 1000,
        "deviceSkuId": "sku2360002",
        "devicePaymentPercentage": "50",
        "deviceSorId": "SMG950UZKV",
        "skuListDiscountPricing": {
          "skuListPrice": [{
            "priceListId": "edgeFullRetailPriceListId",
            "price": 756.0
          }, {
            "priceListId": "twoYearPriceListId",
            "price": 249.99
          }, {
            "priceListId": "edgeFirstMonthPriceListId",
            "price": 31.5
          }, {
            "priceListId": "fullRetailPriceListId",
            "price": 756.0
          }, {
            "priceListId": "edgeRemainingMonthPriceListId",
            "price": 31.5
          }],
          "skuDiscountPrice": []
        },
        "colorImage": null,
        "upgradeOptionCode": "UO",
        "annualUpgradeEligible": true,
        "displayName": "Samsung Galaxy S8 64GB in Midnight Black",
        "colorCode": "#000000",
        "mobileAppImageName": null,
        "shippingDateLabel": null,
        "shippingDateStatusCode": 1000,
        "carouselImages": ["https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Black", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8BLK_a_005_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8BLK_a_009_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8BLK_a_013_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8BLK_b_001_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8BLK_b_005_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8BLK_b_009_spin", "https://ss7.vzw.com/is/image/VerizonWireless/SamGalS8BLK_b_013_spin"]
      }],
      "pdpBadgeFullRetail": null,
      "creditOptionsAvailabilityVO": null,
      "deviceId": "dev7480001",
      "badgeTwoYearDisplayName": null,
      "seoCategoryName": "smartphones",
      "marketingTout": null,
      "badgeEdgeDisplayName": null,
      "circularBadgeText": null,
      "canonicalURL": "smartphones/samsung-galaxy-s8/",
      "priceDisclaimer": null,
      "displayName": "Galaxy S8",
      "pdpBadgePayment": null,
      "badgeRetailToolTip": null,
      "seoBrandName": "samsung",
      "mobileAppImageName": null,
      "addToCartUrl": "/digital/cart/addUpdateDevice",
      "connectedDevice": false,
      "volteEnabled": true,
      "numberShareEligible": false,
      "legacyPlanFlag": false,
      "editCart": false,
      "e911AddressRequired": false,
      "rio": false
    },
    "cpcDevice": false,
    "cpcContractTermList": null,
    "cpcGoToUrl": null,
    "goToSuccessUrl": null,
    "deviceSORIDForFeature": null
  },
  "statusMessage": "Service completed Successfully."
};

export default pdpJSON;
