const protectionJSON = {
  "output": {
    "mtnDeviceInfo": {
      "mtn": null,
      "equipmentProtectionList": [{
        "sorSfoType": "INSUR,I",
        "priceTerm": "/mo",
        "sfoSkuId": "sku2880128",
        "price": "13.00",
        "wasPrice": "13.00",
        "introText": "As soon as next&ndash;day device replacement for loss, theft, damage &amp; post&ndash;warranty defects; expanded cracked screen repair options<sup>1</sup>; international coverage<sup>2</sup> and unlimited access to Tech Coach experts.",
        "displayName": "Total Mobile Protection",
        "preSelected": false,
        "sfoSORId": "85915",
        "hasEcpdDiscount": false,
        "defaultDisplayFlag": false,
        "additionalTapList": null,
        "tmpMdPlan": false
      }, {
        "sorSfoType": "INSUR,W",
        "priceTerm": "/mo",
        "sfoSkuId": "sku1230437",
        "price": "9.00",
        "wasPrice": "9.00",
        "introText": "As soon as next&ndash;day device replacement for loss, theft, damage &amp; post&ndash;warranty defects; expanded cracked screen repair options<sup>1</sup> and international coverage<sup>2</sup>.",
        "displayName": "Total Equipment Coverage",
        "preSelected": false,
        "sfoSORId": "81495",
        "hasEcpdDiscount": false,
        "defaultDisplayFlag": false,
        "additionalTapList": null,
        "tmpMdPlan": false
      }, {
        "sorSfoType": "INSUR,G",
        "priceTerm": "/mo",
        "sfoSkuId": "sku401075",
        "price": "7.00",
        "wasPrice": "7.00",
        "introText": "100% instant access to a Tech Coach expert with zero prompts, menus or transfers.  Does not include protection.",
        "displayName": "Tech Coach",
        "preSelected": false,
        "sfoSORId": "77963",
        "hasEcpdDiscount": false,
        "defaultDisplayFlag": false,
        "additionalTapList": null,
        "tmpMdPlan": false
      }, {
        "sorSfoType": "INSUR,I",
        "priceTerm": "/mo",
        "sfoSkuId": "sku2880124",
        "price": "6.75",
        "wasPrice": "6.75",
        "introText": "As soon as next&ndash;day device replacement for loss, theft &amp; damage; expanded cracked screen repair options<sup>1</sup> and international coverage<sup>2</sup>.",
        "displayName": "Wireless Phone Protection",
        "preSelected": false,
        "sfoSORId": "85913",
        "hasEcpdDiscount": false,
        "defaultDisplayFlag": false,
        "additionalTapList": null,
        "tmpMdPlan": false
      }, {
        "sorSfoType": "INSUR,W",
        "priceTerm": "/mo",
        "sfoSkuId": "sku401085",
        "price": "3.00",
        "wasPrice": "3.00",
        "introText": "Coverage against post&ndash;warranty defects",
        "displayName": "Extended Warranty",
        "preSelected": false,
        "sfoSORId": "79184",
        "hasEcpdDiscount": false,
        "defaultDisplayFlag": false,
        "additionalTapList": null,
        "tmpMdPlan": false
      }, {
        "sorSfoType": "INSUR,D",
        "priceTerm": "/mo",
        "sfoSkuId": "sku401064",
        "price": "0.00",
        "wasPrice": "0.00",
        "introText": "If your device is lost, stolen, damaged, or experiences a post&ndash;warranty defect, the replacement cost may be as high as the retail price. You only have 30 days to enroll in coverage after your device activation.",
        "displayName": "Decline Equipment Protection",
        "preSelected": true,
        "sfoSORId": "66332",
        "hasEcpdDiscount": false,
        "defaultDisplayFlag": false,
        "additionalTapList": null,
        "tmpMdPlan": false
      }],
      "tapFeatureInfo": null,
      "tapExist": false,
      "tapEligible": false,
      "tapMsg": null,
      "tpmdHeader": null,
      "tpmdDescription": null,
      "tpmdButtonText": null,
      "tmprefreshOptionAvailable": false
    },
    "cq": null,
    "saveUrl": "/od/cust/auth/cart/addOrUpdateFeature",
    "commerceItemId": null,
    "deviceSkuId": "sku2150070",
    "deviceProdId": "dev6640013",
    "editProtection": false,
    "deviceProtectionRequired": true,
    "fromEditDeviceForEUP": false,
    "multiUpgradeDetails": null,
    "bundleAccessories": []
  },
  "errorMap": null,
  "statusMessage": "getProtectionFeatures",
  "statusCode": "00"
};

export default protectionJSON;