const reviewOrderJSON = {
  statusCode: '00',
  errorMap: null,
  output: {
    shippingInfoUpdated: true,
    shippingTypeInfoUpdated: true,
    checkoutStates: {
      shippingAddressRequired: false,
      shippingMethodRequired: false,
      paymentRequired: false,
    },
    shippingInfo: {
      addressInfo: {
        firstName: 'BRADLEY',
        lastName: 'BOYD',
        companyName: null,
        address1: '1914 BATON DR',
        address2: null,
        city: 'VIENNA',
        state: 'VA',
        zipcode: '22182',
        businessName: null,
        postalCode: null,
        email: null,
        phoneNumber: null,
      },
      contactInfo: {
        emailAddress: 'BOYD.BRAD@GMAIL.COM',
        phoneNumber: '7033910111',
        firstName: 'BRADLEY',
        lastName: 'BOYD',
        smsMdn: null,
      },
      shippingTypesInfo: [
        {
          estimatedDeliveryDate: 'Wed 01/25',
          shippingDescription: '3 to 5 Day Ground',
          shippingOptionId: 'ECONOMYSHP',
          shippingCost: 0,
          shortDescription: null,
          active: true,
          addedShippingOptionId: false,
          signatureRequired: 'SHIPPING_EMAIL_SIGNATURE_NOT_REQUIRED',
        },
        {
          estimatedDeliveryDate: 'Tue 01/24',
          shippingDescription: '2 Day by 8pm',
          shippingOptionId: 'SHP003',
          shippingCost: 6.99,
          shortDescription: null,
          active: true,
          addedShippingOptionId: true,
          signatureRequired: 'SHIPPING_EMAIL_SIGNATURE_REQUIRED',
        },
        {
          estimatedDeliveryDate: 'Mon 01/23',
          shippingDescription: 'Next Day by 8pm',
          shippingOptionId: 'SHP004',
          shippingCost: 12.99,
          shortDescription: null,
          active: true,
          addedShippingOptionId: false,
          signatureRequired: 'SHIPPING_EMAIL_SIGNATURE_REQUIRED',
        },
        {
          estimatedDeliveryDate: 'Mon 01/23',
          shippingDescription: 'Next Day by 10:30am',
          shippingOptionId: 'SHP005',
          shippingCost: 14.99,
          shortDescription: null,
          active: true,
          addedShippingOptionId: false,
          signatureRequired: 'SHIPPING_EMAIL_SIGNATURE_REQUIRED',
        },
        {
          estimatedDeliveryDate: 'Sat 01/21',
          shippingDescription: 'Saturday by 12pm',
          shippingOptionId: 'SHP006',
          shippingCost: 19.99,
          shortDescription: null,
          active: true,
          addedShippingOptionId: false,
          signatureRequired: 'SHIPPING_EMAIL_SIGNATURE_REQUIRED',
        },
      ],
      ispudetailsInfo: null,
    },
    billingInfo: {
      billToAccountNumber: null,
      selectedPaymentMode: 'savedCard',
      giftCardList: null,
      creditCardInfo: {
        savedCardNickName: 'VISA 0831',
        preselectCard: null,
        creditCardNumber: 'XXXX-XXXX-XXXX-0831',
        creditCardExpMonth: '08',
        creditCardExpYear: '2017',
        billingZipCode: null,
        creditCardType: 'visa',
        creditCardVerificationNumber: null,
      },
      billingAddress: {
        firstName: 'BRADLEY',
        lastName: 'BOYD',
        businessName: null,
        zipcode: '22182',
        state: 'VA',
        address2: null,
        address1: '1914 BATON DR',
        companyName: null,
        city: 'VIENNA',
      },
      expirationMonths: [
        '01',
        '02',
        '03',
        '04',
        '05',
        '06',
        '07',
        '08',
        '09',
        '10',
        '11',
        '12',
      ],
      expirationYears: [
        '2017',
        '2018',
        '2019',
        '2020',
        '2021',
        '2022',
        '2023',
        '2024',
        '2025',
        '2026',
      ],
    },
    orderId: 'O12109586452',
    dueToday: 73.4,
    dueMonthly: 166.24,
    plans: {
      dueMonthly: 130,
      dueToday: 0,
      items: [
        {
          planType: 'The New Verizon Plan',
          lineAccessCharges: [
            {
              name: '4G Smartphone',
              mtn: '7576203305',
              price: 20,
              discountPrice: 0,
              retailPrice: 0,
              hasEcpdDiscount: false,
              promoMessage: null,
              originalPrice: 0,
              amountAfterInstantCredit: 0,
              instantCreditAmount: 0,
              disountedInstantCreditAmt: 0,
            },
          ],
          accountAccess: {
            name: '<span>8 GB </span><span>Shared Data, </span><span>Carryover Data, </span><span>Unlimited </span><span>Talk &amp; Text </span>',
            mtn: null,
            price: 70,
            discountPrice: 0,
            retailPrice: 0,
            hasEcpdDiscount: false,
            promoMessage: null,
            originalPrice: 0,
            amountAfterInstantCredit: 0,
            instantCreditAmount: 0,
            disountedInstantCreditAmt: 0,
          },
          accountLevelFeatures: [],
          totalMonthlyPlanCost: 130,
          spoBadgeMessage: null,
        },
      ],
    },
    devices: {
      dueMonthly: 36.24,
      deviceTotalDueMonthly: 36.24,
      dueToday: 20,
      accessories: null,
      items: [
        {
          deviceName: 'Apple&reg; iPhone&reg; 7 Plus 128GB in Jet Black',
          dueMonthly: 36.24,
          dueToday: 0,
          upgradeFee: 20,
          activationFee: 0,
          mtn: '7576203305',
          deviceImageUrl: 'https://mobile.vzw.com/hybridClient/is/image/VerizonWireless/iphone7-plus-front-jetblk?$device-mini$',
          protectionFeature: {
            name: 'Decline Equipment Protection',
            mtn: null,
            price: 0,
            discountPrice: 0,
            retailPrice: 0,
            hasEcpdDiscount: false,
            promoMessage: null,
            originalPrice: 0,
            imageUrl: null,
            hasBogoDiscount: false,
            qty: null,
            amountAfterInstantCredit: 0,
            instantCreditAmount: 0,
            disountedInstantCreditAmt: 0,
          },
          optionalFeatures: [],
          installmentBalance: 869.99,
          edgeRetailPrice: 869.99,
          edgeItemDownPaymentAmount: 0,
          mailInRebateAmount: 0,
          transferredFromMtn: null,
          devicePromotionList: [
            {
              PromoDescription: 'Your $16.24 monthly bill credits begin within 2-3 cycle.',
            },
          ],
          bicOfferApplied: true,
          bicContractPrice: 36.24,
          bicDiscountedContractPrice: 20,
          bicAdditionalContractText: '$36.24/mo less $16.24/mo bill credit for 24 mos; 0% APR. Bill credits end when balance is paid. Line must remain in good standing.',
          bicMessageMap: {
            message: 'Your $16.24 monthly bill credits begin within 2-3 cycle.',
            tooltip: '$36.24/mo less $16.24/mo bill credit for 24 mos; 0% APR. Bill credits end when balance is paid. Line must remain in good standing.',
          },
          edgeUpAmount: 0,
          displayDeviceDueMonthly: 56.24,
          deviceLACFee: 20,
          manufactureName: 'Apple',
          color: 'Apple Jet Black',
          size: '128GB',
          displayName: 'iPhone&reg; 7 Plus',
          contractTerm: '0',
          edgeUpBuyOutAmount: 0,
          fullRetailPrice: 869.99,
          amountAfterInstantCredit: 0,
          accessory: false,
          edgeDevice: true,
          eupdevice: false,
          instantCreditAmount: 0,
          disountedInstantCreditAmt: 0,
        },
      ],
      buddyUpgrade: false,
    },
    accessories: null,
    taxes: [
      {
        name: 'TAXES & FEES',
        price: 53.4,
        discountPrice: 0,
        retailPrice: 0,
        originalPrice: 0,
        city: 'VIENNA',
        state: 'VA',
        taxCalculated: true,
        taxNotCalculatedMsg: null,
      },
    ],
    selectedShippingType: {
      type: 'SHIPPING',
      shippingTypeName: 'FREE 2 Day by 8pm',
      price: 0,
      discountPrice: 0,
      estimatedDeliveryDate: 'Thu 12/22',
    },
    depositAmount: 0,
    employeeDiscount: 0,
    saveAmount: 0,
    totalUpgradeFee: 20,
    recycleDeviceAppraise: 0,
    edgeOrderTotalDownPayment: 0,
    giftCard1Info: null,
    giftCard2Info: null,
    opalImpersonator: null,
    stackableDataDescription: [
      'iPhone 7 Plus Jet Black 128GB ',
      '[757-620-3305] ',
      '- 2GB',
      ' Additional Data. BONUS - 2 GB/MO FOR LIFE',
      '<br><hr class="stackRule"\\>',
    ],
    stackbleDataAggregateTotals: '+ FREE 2 GB of extra data / mo. ',
    edgeUpBuyOutAmount: 0,
    edgeupBuyOutMtnList: null,
    promotionList: [],
    tapFeatureDetails: null,
    cpcOrder: false,
    amountAfterInstantCredit: 0,
    datagapDisclosureAgreement: null,
    pastDueAmount: 0,
    instantCreditAmount: 0,
    tradeInPromoDetails: null,
    deviceConfigInfo: {
      npaNxxdetails: null,
    },
    termsAndConditionsInfo: {
      edgeTerms: [
        {
          edgeDeviceName: 'Apple&reg; iPhone&reg; 7 Plus 32GB in Gold',
          deviceLabel: 'Device added',
          edgeTermsAndCondition: "         <h3>RETAIL INSTALLMENT SALE AGREEMENT / RETAIL INSTALLMENT OBLIGATION &#8212; SUBJECT TO STATE REGULATION</h3>         <div class=\"row\">          <span class=\"column50 bold\">SELLER (CREDITOR):</span>          <span class=\"column50\">Verizon Wireless Service LLC (\"Verizon Wireless\")<br/>One Verizon Way, Basking Ridge, NJ 07920 (908) 559-7000</span>          <span class=\"column50 bold\">AGREEMENT #</span>           <span class=\"column50\">1800372595</span>          <span class=\"column50 bold\">BUYER&#39;S NAME:</span>          <span class=\"column50\">RYAN JACOBS</span>          <span class=\"column50 bold\">BUYER&#39;S PHONE NUMBER:</span>          <span class=\"column50\"> 8136144718</span>          <span class=\"column50 bold\">BUYER&#39;S ADDRESS:</span>          <span class=\"column50\">385 S NORTH LAKE BLVD APT 1040  ALTAMONTE SPRINGS FL 32701 5251</span>              <span class=\"column50 bold\">DESCRIPTION OF GOODS:</span>                    <span class=\"column50\">MNR32LL/A &nbsp; (<b>&#34;DEVICE&#34;</b>)</span>                   <span class=\"column50 bold\">TRANSACTION DATE:</span>          <span class=\"column50\">01/24/2017</span>          </div>         <div class=\"row\">          <p>YOU, meaning the Buyer named above, agree to pay US, the Seller/Creditor named above as Verizon Wireless, the Total Sale Price of the goods identified            above according to the Terms of this Retail Installment Sale Agreement/ Retail Installment Obligation (referred to below as &#34;Agreement&#34;).          </p>         </div>         <div class=\"row\">          <h4>ANNUAL PERCENTAGE RATE</h4>          <p>The cost of your credit as a yearly rate</p>          <p>0 %</p>          <h4>FINANCE CHARGE</h4>          <p>The dollar amount the credit will cost you</p>          <p class=\"bold\">$0.00</p>          <h4>AMOUNT FINANCED</h4>          <p>The amount of credit provided to you or on your behalf</p>          <p>$769.99</p>          <h4>TOTAL OF PAYMENTS</h4>          <p>The amount you will have paid after you have made all payments as scheduled</p>          <p>$769.99</p>          <h4>TOTAL SALE PRICE</h4>          <p>The total cost of your purchase on credit including your down payment of $0.00</p>          <p>$769.99</p>          <h4>Your payment schedule will be</h4>          <p>Number of Payments: 24   Payment 1: $32.15; Payment 2-24: $32.08;</p>          <p>Amount of Payments: $769.99</p>         </div>                           <div class=\"row fine\">          <h4>When Payments are Due:</h4>                                                                                  <div class=\"column25 payments\">               <span class=\"bold\">Payments<br />1 to 6</span>                         <span>                            02/26/2017                  </span>                 <span>                            03/29/2017                  </span>                 <span>                            04/28/2017                  </span>                 <span>                            05/29/2017                  </span>                 <span>                            06/28/2017                  </span>                 <span>                            07/29/2017                  </span>              </div>                                                      <div class=\"column25 payments\">               <span class=\"bold\">Payments<br />7 to 12</span>                         <span>                            08/29/2017                  </span>                 <span>                            09/28/2017                  </span>                 <span>                            10/29/2017                  </span>                 <span>                            11/28/2017                  </span>                 <span>                            12/29/2017                  </span>                 <span>                            01/29/2018                  </span>              </div>                                                      <div class=\"column25 payments\">               <span class=\"bold\">Payments<br />13 to 18</span>                         <span>                            02/26/2018                  </span>                 <span>                            03/29/2018                  </span>                 <span>                            04/28/2018                  </span>                 <span>                            05/29/2018                  </span>                 <span>                            06/28/2018                  </span>                 <span>                            07/29/2018                  </span>              </div>                                                             <div class=\"column25 payments\">               <span class=\"bold\">Payments<br />19 to 24</span>                         <span>                            08/29/2018                  </span>                 <span>                            09/28/2018                  </span>                 <span>                            10/29/2018                  </span>                 <span>                            11/28/2018                  </span>                 <span>                            12/29/2018                  </span>                 <span>                            01/29/2019                  </span>              </div>                                      </div>         <div class=\"row\">          <p class=\"uppercase bold\">PAYMENTS RECEIVED 15 OR MORE DAYS AFTER YOUR DUE DATE MAY INCUR A LATE PAYMENT FEE OF UP TO 5% OR $5, WHICHEVER IS LESS.PLEASE SEE YOUR AGREEMENT TERMS FOR ANY ADDITIONAL INFORMATION ABOUT NONPAYMENT, DEFAULT, ANY            REQUIRED PAYMENT IN FULL BEFORE THE SCHEDULED PAYMENT DATES, AND PREPAYMENT TERMS.          </p>         </div>         <div class=\"row fine\">          <p>           <span class=\"bold\">AGREEMENT.</span> THIS RETAIL INSTALLMENT SALES AGREEMENT (<b>&ldquo;AGREEMENT&rdquo;</b>) REQUIRES THAT YOU AGREE TO AND           MAINTAIN SERVICE WITH VERIZON WIRELESS UNDER YOUR CUSTOMER AGREEMENT. ALTHOUGH YOUR CUSTOMER AGREEMENT IS A SEPARATE           DOCUMENT, EXCEPT AS PROHIBITED BY APPLICABLE LAW, THE WAIVERS AND LIMITATIONS OF LIABILITY, DISCLAIMER OF WARRANTIES,           AND OTHER PROVISIONS OF YOUR CUSTOMER AGREEMENT ARE INCORPORATED BY THIS REFERENCE IN THIS AGREEMENT, AND SHALL SURVIVE           TERMINATION OF YOUR CUSTOMER AGREEMENT. ADDITIONALLY, ANY DISPUTES UNDER THIS AGREEMENT SHALL BE RESOLVED IN ACCORDANCE           WITH THE DISPUTE RESOLUTION PROVISIONS IN YOUR CUSTOMER AGREEMENT UNDER THE HEADING: &ldquo;HOW DO I RESOLVE DISPUTES           WITH VERIZON WIRELESS,&rdquo; WHICH TERMS ARE INCORPORATED BY REFERENCE. SPECIFICALLY, YOU AND VERIZON WIRELESS BOTH AGREE           TO RESOLVE ALL DISPUTES UNDER THIS AGREEMENT ONLY BY ARBITRATION OR SMALL CLAIMS COURT AND YOU WAIVE ANY RIGHT TO A JUDGE           OR JURY IN ANY ARBITRATION.          </p>          <p>           <span class=\"bold\">PAYMENTS.</span> Payment is due as stated on your bill. IF WE DO NOT RECEIVE PAYMENT WITHIN 15 DAYS OF THE DUE DATE, WE MAY CHARGE           YOU A LATE PAYMENT FEE OF UP TO 5% OF THE UNPAID BALANCE OF YOUR BILL OR $5, WHICHEVER IS LESS, except where prohibited by           law. Your specific payment schedule is provided above. Returned checks will be subject to a fee of up to $25, except where           prohibited by law. Payments you make will be applied first to balances due under your Customer Agreement and then to balances           due under this Agreement. If you have more than one Retail Installment Sales Agreement on your account, payments will be            applied to the oldest one first, and then to more recent ones in order of age; if two Retail Installment Sales Agreements            are entered into on the same day, the one added to our system first will be deemed older.Your payment            schedule is determined by the date that you accept these terms and conditions, which allows us to apply charges to            your bill. If you order a Device that is not available for shipment at the time of order, we will provide you            with a payment schedule based on our best estimate of when your Device will be shipped. Your first payment           will not be due until the Device is shipped, at which point we will charge the credit card you provided at the time of your           Order or, if eligible apply the first payment to your bill. For any Device not available for shipment at the time of order,           you agree that we may update the estimated payment schedule when your Device is shipped, and we will provide the new payment           schedule to you in writing. Additionally, if a delay in accepting this Agreement or activating your Device results in any           charges becoming due on a date(s) later than the payment schedule, we will provide you with an updated payment schedule on           your bill. If you do not activate your Device within 45 days of receipt, or if you cancel your Customer Agreement, you agree            that Verizon Wireless may charge, and you agree to pay, the entire remaining balance owed for your Device as soon as your next bill.           If your Device qualifies for an Early Upgrade offer, visit <a href=\"#\" onclick=\"return false;\">verizonwireless.com/upgradeterms123</a> for further details, terms and conditions.          </p>          <p>           <span class=\"bold\">PREPAYMENT.</span> You may pay the total amount due under this Agreement at any time before the final scheduled payment is due,            and you will not have to pay a penalty.  If you pay more than the monthly  payment due any excess amount you pay will be credited to your account,            and applied to any future charges pursuant to Section 2 above.          </p>          <p>           <span class=\"bold\">RISK OF LOSS: INSURANCE.</span> You bear the entire risk of loss, theft or damage to the Device from any cause during            the term of this Agreement. Even if the Device is lost, stolen or damaged, you remain obligated for the total of the payments. We           recommend that you obtain property insurance on the Device. You may obtain property insurance from others on goods purchased under this Agreement.          </p>          <p>           <span class=\"bold\">DEFAULT AND REMEDIES.</span> You are in default under this Agreement if you fail to make any required payment when due or within           fifteen (15) days of the due date; you cancel your Customer Agreement; we cancel your Customer Agreement for good cause; you           breach any covenant, representation or warranty hereunder, or default in the performance of any other obligation which is           not cured within ten (10) days after written notice to you; or we terminate your Service for breach           (each a &ldquo;Default&rdquo;). To the extent permitted by applicable law, upon a Default we have the right to require you           to pay immediately the entire remaining balance in full under this Agreement, and to pay us actual and reasonable costs of collection.          </p>          <p>           <span class=\"bold\">ASSIGNMENT.</span> We may, without your consent, and without giving you notice, assign or transfer this Agreement or any payment or any           other sums due or to become due hereunder. In such event our assignee will have, to the extent transferred or assigned to it, all our           rights, powers, privileges and remedies under the Agreement. You agree you will not assign this Agreement or any interest in it and will           not sell or offer to sell or transfer or enter into any lease with respect to the Device covered by this Agreement without our prior           written consent.          </p>          <p>           <span class=\"bold\">MILITARY LENDING ACT DISCLOSURE.</span> If you are a member of the active military, or a spouse or dependent of the active military,            the following apply (the federal government requires us to provide this notice to you even though we do not assess any of the fees referenced below):              Federal law provides important protections to members of the Armed Forces and their dependents relating to extensions of consumer credit.             In general, the cost of consumer credit to a member of the Armed Forces and his or her dependent may not exceed an annual percentage rate of 36 percent.             This rate must include, as applicable to the credit transaction or account: The costs associated with credit insurance premiums;             fees for ancillary products sold in connection with the credit transaction; any application fee charged (other than certain application fees for specified credit             transactions or accounts); and any participation fee charged (other than certain participation fees for a credit card account).             Please refer to the Truth In Lending Act disclosures in your Agreement for information regarding your monthly payments. To hear this statement of rights under the             Military Lending Act, please call 800-922-0204 and mention Military Lending Act.             </p>          <p>           <span class=\"bold\">ELECTRONIC ACCESS TO AGREEMENT.</span> By signing below, you acknowledge that you have access to Verizon Wireless&#8217;           Website at <a href=\"http://www.verizonwireless.com\">www.verizonwireless.com</a>, where a copy of this Agreement will be available to you.           If you want a paper copy of this Agreement, you may ask your sales representative to email or print a copy for you.          </p>         </div>         <div class=\"row itemize\">          <h4>ITEMIZATION OF AMOUNT FINANCED OF:&nbsp; $769.99</h4>          <p>(A) CASH PRICE (excluding tax): <span>$769.99</span></p>          <p>(B) DOWN PAYMENT (if applicable): <span>$0.00</span></p>                  <p>(C) FINANCE CHARGE: <span>$0.00</span></p>          <p>(D) TAXES AND FEES: <span>$53.90</span></p>          <p>           (E) AMOUNT FINANCED:            <span>            <script>if('769.99'.indexOf('$') == -1) document.write('$');</script>769.99           </span>          </p>          <p>(the amount of credit provided to you on your behalf)</p>         </div>         <div class=\"row fine bold\">          <p>Do not sign this agreement before you read it or if it contains any blank spaces for           information that is available at the time you sign this agreement.          </p>          <p>You are entitled to a completely filled-in copy of this agreement at the time you           sign it. Keep it to protect your legal rights.          </p>          <p>Under the law, you have the right to pay off in advance the full amount due at any time.           If you desire to prepay the full amount due, the amount due will be furnished upon request.          </p>          <p>You have the right to redeem the property if repossessed for a default and, to require, under certain conditions, a resale of the property, if repossessed.</p>          <p>This contract is covered by state and federal laws, and you have the rights of a buyer under such laws.</p>          <p>ANY HOLDER OF THIS CONSUMER CREDIT CONTRACT IS SUBJECT TO ALL CLAIMS AND DEFENSES WHICH THE DEBTOR COULD           ASSERT AGAINST THE SELLER OF GOODS OR SERVICES OBTAINED UNDER THIS AGREEMENT OR WITH THE PROCEEDS HEREOF. RECOVERY           HEREUNDER BY THE DEBTOR SHALL NOT EXCEED AMOUNTS PAID BY THE DEBTOR HEREUNDER.          </p>          <p>This is a retail installment sale agreement and not a lease. We have a limited return policy. Please ask for details.</p>         </div>         <div class=\"row fine\">                 </div>         <div class=\"row fine\">                   <p>Version 12/15/2016</p>                  </div>                     ",
        },
      ],
      partialMonthChargesText: null,
      promotionTextCPC: null,
      agreementText: "<h4>My Verizon Wireless Customer Agreement</h4>\r\r\r\r<p><em>(Para una copia de este documento en Espa&ntilde;ol, visite nuestro website: <strong>vzw.com/espanol.)</strong></em></p>\r\r\r\r<p><strong>Thanks for choosing Verizon Wireless. In this Customer Agreement, you'll find important information about your Service, including our ability to make changes to your Service or this agreement's terms, our liability if things don't work as planned and how any disputes between us must be resolved in arbitration or small claims court . If you're signing up for Service for a minimum contract term, you'll also find information about that contract term and what happens if you cancel a line of Service early or don't pay on time, including the possibility of an early termination fee you may owe Verizon Wireless.</strong></p>\r\r\r\r<h4>My Service</h4>\r\r\r\r<p><strong>Your Service terms and conditions are part of this agreement.</strong> Your Plan includes your monthly allowances and features, where you can use them (your \"Coverage Area\"), and their monthly and pay&ndash;per&ndash;use charges. You can also subscribe to several Optional Services, like data add&ndash;on packages. Together, your Plan and any Optional Services you select are your Service. The terms and conditions for your Service can be found in the brochures that are available when you activate, or online at <strong>verizonwireless.com</strong></p>\r\r\r\r<h4>How do I accept this Agreement?</h4>\r\r\r\r<p>You accept this Agreement by:</p>\r\r\r\r<ul>\r\r\t<li>Agreeing in writing, by email, over the phone, or in person;</li>\r\r\t<li>Opening a package that says you are accepting by opening it; or</li>\r\r\t<li>Activating your Service.</li>\r\r</ul>\r\r\r\r<p>When you accept, you're representing that you are at least 18 years old and are legally able to accept an agreement. If you're accepting for an organization, you're representing that you are authorized to bind that organization, and where the context requires, \"you\" means the organization. By accepting you are agreeing to every provision of this Agreement whether or not you have to read it.</p>\r\r\r\r<p><strong>If you do accept, you can cancel a line of Service within 14 days of accepting this Agreement without having to pay an early termination fee as long as you return, within the applicable return period, any equipment you purchased from us or one of our authorized agents at a discount in connection with your acceptance of this Agreement, but you'll still have to pay for your Service through that date. If you signed up for Prepaid Service, no refunds will be granted after 14 days or if your account has been activated.</strong><br /><br />If you change your device or receive a Service promotion, you may be required to change your Plan to one that we are currently offering at that time.</p>\r\r\r\r<h4>My privacy</h4>\r\r\r\r<p>We collect personal information about you. We gather some information through our relationship with you, such as information about the quantity, technical configuration, type, destination and amount of your use of our telecommunications services. You can find out how we use, share and protect the information we collect about you in our Privacy Policy, available at Verizon.com/Privacy. By entering this Agreement, you consent to our data collection, use and sharing practices described in our Privacy Policy. It is your responsibility to notify people who connect devices through your mobile hotspot, Jetpack or wireless router that we will collect, use and share information about their device and use of the Service in accordance with our Privacy Policy. We provide you with choices to limit, in certain circumstances, our use of the data we have about you. You can review these choices at Verizon.com/Privacy#limits. If there are additional specific advertising and marketing practices for which your consent is necessary, we will seek your consent (such as through the privacy-related notices you receive when you purchase or use our products and services) before engaging in those practices. If you subscribe to Service for which usage charges are billed at the end of the billing period (¿Postpay Service¿), we may investigate your credit history at any time and share credit information about you with credit reporting agencies and other Verizon companies. If you¿d like the name and address of any credit agency that gives us a credit report about you, just ask.</p>\r\r\r\r<p>Many services and applications offered through your device may be provided by third parties. Before you use, link to or download a service or application provided by a third party, you should review the terms of such service or application and applicable privacy policy. Personal information you submit may be read, collected or used by the service or application provider and/or other users of those forums.</p>\r\r\r\r<p>You consent to allow Verizon Wireless and anyone who collects on our behalf to contact you about your account status, including past due or current charges, using prerecorded calls, email and calls or messages delivered by an automatic telephone dialing system to any wireless phone number or email address you provide. Verizon Wireless will treat any email address you provide as your private email that is not accessible by unauthorized third parties. Unless you notify us that your wireless service is based in a different time zone, calls will be made to your cellular device during permitted calling hours based upon the time zone affiliated with the mobile telephone number you provide.</p>\r\r\r\r<h4>What happens if my Postpay Service is canceled before the end of my contract term?</h4>\r\r\r\r<p>If you're signing up for Postpay Service, you're agreeing to subscribe to a line of Service either on a month&ndash;to&ndash;month basis or for a minimum contract term, as shown on your receipt or order confirmation. (If your Service is suspended without billing, or at a reduced billing rate, that time doesn't count toward completing your contract term.) Once you've completed your contract term, you'll automatically become a customer on a month&ndash;to&ndash;month basis for that line of Service. <strong>If you cancel a line of Service, or if we cancel it for good cause, during its contract term, you'll have to pay an early termination fee. If your contract term results from your purchase of an advanced device on or after November 14, 2014, your early termination fee will be &#36;350, which will decline by &#36;10 per month upon completion of months 7&ndash;17, by &#36;20 per month upon completion of months 18&ndash;22, and by &#36;60 upon completion of month 23 and will be &#36;0 upon completion of your contract term. For other contract terms entered into on or after November 14, 2014, your early termination fee will be &#36;175, which will decline by &#36;5 per month upon completion of months 7&ndash;17, &#36;10 per month upon completion of months 18&ndash;22, &#36;30 upon completion of month 23 and will be &#36;0 upon completion of your contract term. If your contract results from your purchase of an advanced device prior to November 14, 2014, your early termination fee will be &#36;350 minus &#36;10 for each full month of your contract term that you complete. For other contract terms entered into prior to November 14, 2014, your early termination fee will be &#36;175 minus &#36;5 for each full month of your contract term that you complete. Cancellations will become effective on the last day of that month's billing cycle,</strong> and you are responsible for all charges incurred until then. Also, if you bought your wireless device from an authorized agent or third&ndash;party vendor, you should check whether they charge a separate termination fee.</p>\r\r\r\r<h4>Can I take my wireless phone number to another carrier?</h4>\r\r\r\r<p>You may be able to take, or \"port\", your wireless phone number to another carrier. If you port a number from us, we'll treat it as though you asked us to cancel your Service for that number. After the porting is completed, you won't be able to use our service for that number, but you'll remain responsible for all fees and charges through the end of that billing cycle, just like any other cancellation. If you're a Prepaid customer, you won't be entitled to a refund of any balance on your account. If you port a number to us, please be aware that we may not be able to provide some services right away, such as 911 location services. You don't have any rights to your wireless phone number, except for any right you may have to port it.</p>\r\r\r\r<h4>Directory information</h4>\r\r\r\r<p>We will not publish your wireless phone number in any available directory or give it to anyone for that purpose, unless you ask us to.</p>\r\r\r\r<h4>Can I have someone else manage my Postpay account?</h4>\r\r\r\r<p>No problem &ndash; just tell us by phone, in person, or in writing. You can appoint someone to manage your Postpay account for a single transaction, or until you tell us otherwise. The person you appoint will be able to make changes to your account, including adding new lines of Service, buying new wireless devices, and extending your contract term. Any changes that person makes will be treated as modifications to this agreement.</p>\r\r\r\r<h4>Can Verizon Wireless change this Agreement or my Service?</h4>\r\r\r\r<p>We may change prices or any other term of your Service or this agreement at any time, but we'll provide notice first, including written notice if you have Postpay Service. If you use your Service after the change takes effect, that means you're accepting the change. If you're a Postpay customer and a change to your Plan or this agreement has a material adverse effect on you, you can cancel the line of Service that has been affected within 60 days of receiving the notice with no early termination fee if we fail to negate the change after you notify us of your objection to it. Notwithstanding this provision, if we make any changes to the dispute resolution provision of this Agreement, such changes will not affect the resolution of any disputes that arose before such change.</p>\r\r\r\r<h4>My wireless device</h4>\r\r\r\r<p>Your wireless device must comply with Federal Communications Commission regulations, be certified for use on our network, and be compatible with your Service. Please be aware that we may change your wireless device's software, applications or programming remotely, without notice. This could affect your stored data, or how you've programmed or use your wireless device. By activating Service that uses a SIM (Subscriber Identity Module) card, you agree we own the intellectual property and software in the SIM card, that we may change the software or other data in the SIM card remotely and without notice, and we may utilize any capacity in the SIM card for administrative, network, business and/or commercial purposes. If you bought a wireless device for Postpay Service from Verizon Wireless that doesn't use a SIM card, and you want to reprogram it for use with another wireless network, the default programming code is set to \"000000\" or \"123456.\" But please note that your wireless device may not work with another wireless network, or the other wireless carrier may not accept your wireless device on its network. If you activate a 3G phone&ndash;in&ndash;the&ndash;box wireless device for Prepaid Service, it can only be used for Prepaid Service during the first six (6) months after activation. If you activate a 4G LTE phone&ndash;in&ndash;the&ndash;box wireless device for Prepaid Service, it cannot be used with any other service until it is first activated on Prepaid Service and the first monthly payment is made.</p>\r\r\r\r<h4>Where and how does Verizon Wireless Service work?</h4>\r\r\r\r<p>Wireless devices use radio transmissions, so unfortunately you can't get Service if your device isn't in range of a transmission signal. And please be aware that even within your Coverage Area, many things can affect the availability and quality of your Service, including network capacity, your device, terrain, buildings, foliage and weather.</p>\r\r\r\r<h4>How can I prevent unintended charges on my bill?</h4>\r\r\r\r<p>You agree to pay all access, usage and other charges that you or any other user of your wireless device incurred. If multiple wireless devices are associated with your account, you agree to pay all charges incurred by users of those wireless devices. Many services and applications are accessible on or through wireless devices, including purchases of games, movies, music and other content. Some of these services are provided by Verizon Wireless. Others are provided by third parties that may offer the option to bill the charges to your Verizon Wireless bill or other methods of payment. Charges may be one&ndash;time or recurring. The amount and frequency of the charges will be disclosed to you or the person using your device or a device associated with your account at the time a purchase is made. If the purchaser chooses to have the charges billed to your account, such charges will become part of the amount due for that billing cycle. <strong>Verizon Wireless offers tools to block or restrict these services, and to block all billing for third&ndash;party services on your Verizon Wireless bill, at verizonwireless.com/myverizon</strong></p>\r\r\r\r<h4>What charges are set by Verizon Wireless?</h4>\r\r\r\r<p>For Postpay Service, our charges include Federal Universal Service, Regulatory and Administrative charges, and we may also include other charges related to our governmental costs. We set these charges; they aren't taxes, they aren't required by law, they are not necessarily related to anything the government does, they are kept by us in whole or in part, and the amounts and what they pay for may change.</p>\r\r\r\r<h4>Government taxes, fees and surcharges</h4>\r\r\r\r<p>You must pay all taxes, fees and surcharges set by federal, state and local governments. Please note that we may not always be able to notify you in advance of changes to these charges.</p>\r\r\r\r<h4>What are roaming charges?</h4>\r\r\r\r<p>You're \"roaming\" whenever your wireless device uses a transmission site outside your Coverage Area or uses another company's transmission site. Sometimes roaming happens even when you're within your Coverage Area. There may be higher rates and extra charges (including charges for long distance, tolls or calls that don't connect) for roaming calls, depending on your Plan.</p>\r\r\r\r<h4>How does Verizon Wireless calculate my charges?</h4>\r\r\r\r<p>For charges based on the amount of time used or data sent or received, we'll round up any fraction to the next full minute or, depending on how you're billed for data usage, the next full megabyte or gigabyte. For outgoing calls, usage time starts when you first press <strong>Send</strong> or the call connects to a network, and for incoming calls, it starts when the call connects to a network (which may be before it rings). Usage time may end several seconds after you press <strong>End</strong> or after the call disconnects. For calls made on our network, we charge only for calls that are answered, including by machines. For Postpay Service, usage cannot always be processed right away and may be included in a later bill, but the usage will still count towards your allowance for the month when the Service was used.</p>\r\r\r\r<h4>How and when can I dispute charges?</h4>\r\r\r\r<p>If you're a Postpay customer, you can dispute your bill within 180 days of receiving it, but unless otherwise provided by law or unless you're disputing charges because your wireless device was lost or stolen, you still have to pay all charges until the dispute is resolved. If you're a Prepaid customer, you can dispute a charge within 180 days of the date the disputed charge was incurred. <strong>YOU MAY CALL US TO DISPUTE CHARGES ON YOUR BILL OR ANY SERVICE(S) FOR WHICH YOU WERE BILLED, BUT IF YOU WISH TO PRESERVE YOUR RIGHT TO BRING AN ARBITRATION OR SMALL CLAIMS CASE REGARDING SUCH DISPUTE, YOU MUST WRITE TO US AT THE CUSTOMER SERVICE ADDRESS ON YOUR BILL, OR SEND US A COMPLETED NOTICE OF DISPUTE FORM (AVAILABLE AT VERIZONWIRELESS.COM), WITHIN THE 180&ndash;DAY PERIOD MENTIONED ABOVE. IF YOU DO NOT NOTIFY US IN WRITING OF SUCH DISPUTE WITHIN THE 180&ndash;DAY PERIOD, YOU WILL HAVE WAIVED YOUR RIGHT TO DISPUTE THE BILL OR SUCH SERVICE(S) AND TO BRING AN ARBITRATION OR SMALL CLAIMS CASE REGARDING ANY SUCH DISPUTE.</strong></p>\r\r\r\r<h4>What are my rights for dropped calls or interrupted service?</h4>\r\r\r\r<p>If you drop a call in your Coverage Area, redial. If it's answered within 5 minutes, call us within 90 days if you're a Postpay customer, or within 45 days if you're a Prepaid customer, and we'll give you a 1&ndash;minute airtime credit. If you're a Postpay customer and you lose Service in your Coverage Area for more than 24 hours in a row and we're at fault, call us within 180 days and we'll give you a credit for the time lost. Please be aware that these are your only rights for dropped calls or interrupted Service.</p>\r\r\r\r<h4>About my payments</h4>\r\r\r\r<p>If you're a Postpay customer and we don't get your payment on time, we will charge you a late fee of up to 1.5 percent per month (18 percent per year) on the unpaid balance, or a flat &#36;5 per month, whichever is greater, if allowed by law in the state of your billing address. (If you choose another company to bill you for our Service [such as another Verizon company], late fees are set by that company or by its tariffs and may be higher than our late fees.) Late fees are part of the rates and charges you agree to pay us. If you fail to pay on time and Verizon Wireless refers your account(s) to a third party for collection, a collection fee will be assessed and will be due at the time of the referral to the third party. The fee will be calculated at the maximum percentage permitted by applicable law, not to exceed 18 percent. We may require a deposit at the time of activation or afterward, or an increased deposit. We'll pay simple interest on any deposit at the rate the law requires. We may apply deposits or payments in any order to any amounts you owe us on any account. If your final credit balance is less than $1, we will refund it only if you ask. If your service is suspended or terminated, you may have to pay a fee to have service reactivated.</p>\r\r\r\r<p>If you're a Prepaid customer, you may replenish your balance at any time before the expiration date by providing us with another payment. Your balance may not exceed $1,000 and you may be prevented from replenishing if your balance reaches $1,000. We will suspend service when your account reaches the expiration date and any unused balance will be forfeited.</p>\r\r\r\r<p>We may charge you up to $25 for any returned check.</p>\r\r\r\r<h4>What if my wireless device gets lost or stolen?</h4>\r\r\r\r<p>We're here to help. It's important that you notify us right away, so we can suspend your Service to keep someone else from using it. If you're a Postpay customer and your wireless device is used after the loss or theft but before you report it, and you want a credit for any charges for that usage, we're happy to review your account activity and any other information you'd like us to consider. Keep in mind that you may be held responsible for the charges if you delayed reporting the loss or theft without good reason, but you don't have to pay any charges you dispute while they are being investigated. If you're a California customer and we haven't given you a courtesy suspension of recurring monthly charges during the past year, we'll give you one for 30 days or until you replace or recover your wireless device, whichever comes first.</p>\r\r\r\r<h4>What are Verizon Wireless rights to limit or end service or end this Agreement?</h4>\r\r\r\r<p>We can, without notice, limit, suspend or end your Service or any agreement with you for any good cause, including, but not limited to: (1) if you: (a) breach this Agreement; (b) resell your Service; (c) use your Service for any illegal purpose, including use that violates trade and economic sanctions and prohibitions promulgated by any US governmental agency; (d) install, deploy or use any regeneration equipment or similar mechanism (for example, a repeater) to originate, amplify, enhance, retransmit or regenerate an RF signal without our permission; (e) steal from or lie to us; or, if you're a Postpay customer; (f) do not pay your bill on time; (g) incur charges larger than a required deposit or billing limit, or materially in excess of your monthly access charges (even if we haven't yet billed the charges); (h) provide credit information we can't verify; or (i) are unable to pay us or go bankrupt; or (2) if you, any user of your device or any line of service on your account, or any account manager on your account: (a) threaten, harass, or use vulgar and/or inappropriate language toward our representatives; (b) interfere with our operations; (c) \"spam,\" or engage in other abusive messaging or calling; (d) modify your device from its manufacturer's specifications; or (e) use your Service in a way that negatively affects our network or other customers. We can also temporarily limit your Service for any operational or governmental reason.</p>\r\r\r\r<h4>Am I eligible for special discounts?</h4>\r\r\r\r<p>If you're a Postpay customer, you may be eligible for a discount if you are and remain affiliated with an organization that has an agreement with us. Unless your discount is through a government employee discount program, we may share certain information about your Service (including your name, your wireless telephone number and your total monthly charges) with your organization from time to time to make sure you're still eligible. We may adjust or remove your discount according to your organization's agreement with us, and remove your discount if your eligibility ends or your contract term expires. In any case, this won't be considered to have a material adverse effect on you.</p>\r\r\r\r<h4>Disclaimer of warranties</h4>\r\r\r\r<p><strong>We make no representations or warranties, express or implied, including, to the extent permitted by applicable law, any implied warranty of merchantability or fitness for a particular purpose, about your Service, your wireless device, or any applications you access through your wireless device. We do not warrant that your wireless device will work perfectly or will not need occasional upgrades or modifications, or that it will not be negatively affected by network&ndash;related modifications, upgrades or similar activity. If you download or use applications, services or software provided by third parties (including voice applications), 911 or E911, or other calling functionality, may work differently than services offered by us, or may not work at all. Please review all terms and conditions of such third&ndash;party products. Verizon Wireless is not responsible for any third&ndash;party information, content, applications or services you access, download or use on your device. You are responsible for maintaining virus and other Internet security protections when accessing these third&ndash;party products or services. For additional information, visit the Verizon Content Policy at responsibility.verizon.com/contentpolicy</strong></p>\r\r\r\r<p><strong>Please be aware that if you activated your wireless device through our Open Development program, we can't vouch for the device's call quality or overall functionality.</strong></p>\r\r\r\r<h4>Waivers and limitations of liability</h4>\r\r\r\r<p><strong>You and Verizon Wireless both agree to limit claims against each other for damages or other monetary relief to direct damages. This limitation and waiver will apply regardless of the theory of liability. That means neither of us will try to get any indirect, special, consequential, treble or punitive damages from the other. This limitation and waiver also applies if you bring a claim against one of our suppliers, to the extent we would be required to indemnify the supplier for the claim.</strong> You agree we aren't responsible for problems caused by you or others, or by any act of God. You also agree we aren't liable for missed or deleted voice mails or other messages, or for any information (like pictures) that gets lost or deleted if we work on your device. If another wireless carrier is involved in any problem (for example, while you're roaming), you also agree to any limitations of liability that it imposes.</p>\r\r\r\r<div style=\"width:auto;height:auto;border:2px solid black; padding: 5px;\">\r\r<h4>How do I resolve disputes with Verizon Wireless?</h4>\r\r\r\r<p><strong>WE HOPE TO MAKE YOU A HAPPY CUSTOMER, BUT IF THERE'S AN ISSUE THAT NEEDS TO BE RESOLVED, THIS SECTION OUTLINES WHAT'S EXPECTED OF BOTH OF US.</strong></p>\r\r\r\r<p><strong>YOU AND VERIZON WIRELESS BOTH AGREE TO RESOLVE DISPUTES ONLY BY ARBITRATION OR IN SMALL CLAIMS COURT. YOU UNDERSTAND THAT BY THIS AGREEMENT YOU ARE GIVING UP THE RIGHT TO BRING A CLAIM IN COURT OR IN FRONT OF A JURY. WHILE THE PROCEDURES MAY BE DIFFERENT, AN ARBITRATOR CAN AWARD YOU THE SAME DAMAGES AND RELIEF, AND MUST HONOR THE SAME TERMS IN THIS AGREEMENT, AS A COURT WOULD. IF THE LAW ALLOWS FOR AN AWARD OF ATTORNEYS' FEES, AN ARBITRATOR CAN AWARD THEM TOO. WE ALSO BOTH AGREE THAT:</strong></p>\r\r\r\r<p>(1) THE FEDERAL ARBITRATION ACT APPLIES TO THIS AGREEMENT. EXCEPT FOR SMALL CLAIMS COURT CASES THAT QUALIFY, ANY DISPUTE THAT IN ANY WAY RELATES TO OR ARISES OUT OF THIS AGREEMENT OR FROM ANY EQUIPMENT, PRODUCTS AND SERVICES YOU RECEIVE FROM US (OR FROM ANY ADVERTISING FOR ANY SUCH PRODUCTS OR SERVICES), INCLUDING ANY DISPUTES YOU HAVE WITH OUR EMPLOYEES OR AGENTS, WILL BE RESOLVED BY ONE OR MORE NEUTRAL ARBITRATORS BEFORE THE AMERICAN ARBITRATION ASSOCIATION (\"AAA\") OR BETTER BUSINESS BUREAU (\"BBB\"). YOU CAN ALSO BRING ANY ISSUES YOU MAY HAVE TO THE ATTENTION OF FEDERAL, STATE, OR LOCAL GOVERNMENT AGENCIES, AND IF THE LAW ALLOWS, THEY CAN SEEK RELIEF AGAINST US FOR YOU.</p>\r\r\r\r<p>(2) UNLESS YOU AND VERIZON WIRELESS AGREE OTHERWISE, THE ARBITRATION WILL TAKE PLACE IN THE COUNTY OF YOUR BILLING ADDRESS. FOR CLAIMS OVER $10,000, THE AAA'S WIRELESS INDUSTRY ARBITRATION (\"WIA\") RULES WILL APPLY. IN SUCH CASES, THE LOSER CAN ASK FOR A PANEL OF THREE NEW ARBITRATORS TO REVIEW THE AWARD. FOR CLAIMS OF $10,000 OR LESS, THE PARTY BRINGING THE CLAIM CAN CHOOSE EITHER THE AAA'S RULES FOR CONSUMER DISPUTES OR THE BBB'S RULES FOR BINDING ARBITRATION OR, ALTERNATIVELY, CAN BRING AN INDIVIDUAL ACTION IN SMALL CLAIMS COURT. YOU CAN GET PROCEDURES, RULES AND FEE INFORMATION FROM THE AAA (WWW.ADR.ORG), THE BBB (WWW.BBB.ORG) OR FROM US. FOR CLAIMS OF $10,000 OR LESS, YOU CAN CHOOSE WHETHER YOU'D LIKE THE ARBITRATION CARRIED OUT BASED ONLY ON DOCUMENTS SUBMITTED TO THE ARBITRATOR, OR BY A HEARING IN PERSON OR BY PHONE.</p>\r\r\r\r<p><strong>(3) THIS AGREEMENT DOESN'T ALLOW CLASS OR COLLECTIVE ARBITRATIONS EVEN IF THE AAA OR BBB PROCEDURES OR RULES WOULD. NOTWITHSTANDING ANY OTHER PROVISION OF THIS AGREEMENT, THE ARBITRATOR MAY AWARD MONEY OR INJUNCTIVE RELIEF ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF WARRANTED BY THAT PARTY'S INDIVIDUAL CLAIM. NO CLASS OR REPRESENTATIVE OR PRIVATE ATTORNEY GENERAL THEORIES OF LIABILITY OR PRAYERS FOR RELIEF MAY BE MAINTAINED IN ANY ARBITRATION HELD UNDER THIS AGREEMENT. ANY QUESTION REGARDING THE ENFORCEABILITY OR INTERPRETATION OF THIS PARAGRAPH SHALL BE DECIDED BY A COURT AND NOT THE ARBITRATOR.</strong></p>\r\r\r\r<p>(4) IF EITHER OF US INTENDS TO SEEK ARBITRATION UNDER THIS AGREEMENT, THE PARTY SEEKING ARBITRATION MUST FIRST NOTIFY THE OTHER PARTY OF THE DISPUTE IN WRITING AT LEAST 30 DAYS IN ADVANCE OF INITIATING THE ARBITRATION. NOTICE TO VERIZON WIRELESS SHOULD BE SENT TO VERIZON WIRELESS DISPUTE RESOLUTION MANAGER, ONE VERIZON WAY, VC52N080, BASKING RIDGE, NJ 07920. THE NOTICE MUST DESCRIBE THE NATURE OF THE CLAIM AND THE RELIEF BEING SOUGHT. IF WE ARE UNABLE TO RESOLVE OUR DISPUTE WITHIN 30 DAYS, EITHER PARTY MAY THEN PROCEED TO FILE A CLAIM FOR ARBITRATION. WE'LL PAY ANY FILING FEE THAT THE AAA OR BBB CHARGES YOU FOR ARBITRATION OF THE DISPUTE. IF YOU PROVIDE US WITH SIGNED WRITTEN NOTICE THAT YOU CANNOT PAY THE FILING FEE, VERIZON WIRELESS WILL PAY THE FEE DIRECTLY TO THE AAA OR BBB. IF THAT ARBITRATION PROCEEDS, WE'LL ALSO PAY ANY ADMINISTRATIVE AND ARBITRATOR FEES CHARGED LATER, AS WELL AS FOR ANY APPEAL TO A PANEL OF THREE NEW ARBITRATORS (IF THE ARBITRATION AWARD IS APPEALABLE UNDER THIS AGREEMENT).</p>\r\r\r\r<p>(5) WE ALSO OFFER CUSTOMERS THE OPTION OF PARTICIPATING IN A FREE INTERNAL MEDIATION PROGRAM. THIS PROGRAM IS ENTIRELY VOLUNTARY AND DOES NOT AFFECT EITHER PARTY'S RIGHTS IN ANY OTHER ASPECT OF THESE DISPUTE RESOLUTION PROCEDURES. IN OUR VOLUNTARY MEDIATION PROGRAM, WE WILL ASSIGN AN EMPLOYEE WHO'S NOT DIRECTLY INVOLVED IN THE DISPUTE TO HELP BOTH SIDES REACH AN AGREEMENT. THAT PERSON HAS ALL THE RIGHTS AND PROTECTIONS OF A MEDIATOR AND THE PROCESS HAS ALL OF THE PROTECTIONS ASSOCIATED WITH MEDIATION. FOR EXAMPLE, NOTHING SAID IN THE MEDIATION CAN BE USED LATER IN AN ARBITRATION OR LAWSUIT. IF YOU'D LIKE TO KNOW MORE, PLEASE CONTACT US AT <strong>VERIZONWIRELESS.COM</strong> OR THROUGH CUSTOMER SERVICE. IF YOU'D LIKE TO START THE MEDIATION PROCESS, PLEASE GO TO <strong>VERIZONWIRELESS.COM</strong> OR CALL CUSTOMER SERVICE FOR A NOTICE OF DISPUTE FORM TO FILL OUT, AND MAIL, FAX OR EMAIL IT TO US ACCORDING TO THE DIRECTIONS ON THE FORM.</p>\r\r\r\r<p>(6) WE MAY, BUT ARE NOT OBLIGATED TO, MAKE A WRITTEN SETTLEMENT OFFER ANYTIME BEFORE ARBITRATION BEGINS. THE AMOUNT OR TERMS OF ANY SETTLEMENT OFFER MAY NOT BE DISCLOSED TO THE ARBITRATOR UNTIL AFTER THE ARBITRATOR ISSUES AN AWARD ON THE CLAIM. IF YOU DON'T ACCEPT THE OFFER AND THE ARBITRATOR AWARDS YOU AN AMOUNT OF MONEY THAT'S MORE THAN OUR OFFER BUT LESS THAN $5,000, OR IF WE DON'T MAKE YOU AN OFFER, AND THE ARBITRATOR AWARDS YOU ANY AMOUNT OF MONEY BUT LESS THAN $5,000, THEN WE AGREE TO PAY YOU $5,000 INSTEAD OF THE AMOUNT AWARDED. IN THAT CASE WE ALSO AGREE TO PAY ANY REASONABLE ATTORNEYS' FEES AND EXPENSES, REGARDLESS OF WHETHER THE LAW REQUIRES IT FOR YOUR CASE. IF THE ARBITRATOR AWARDS YOU MORE THAN $5,000, THEN WE WILL PAY YOU THAT AMOUNT.</p>\r\r\r\r<p>(7) AN ARBITRATION AWARD AND ANY JUDGMENT CONFIRMING IT APPLY ONLY TO THAT SPECIFIC CASE; IT CAN'T BE USED IN ANY OTHER CASE EXCEPT TO ENFORCE THE AWARD ITSELF.</p>\r\r\r\r<p><strong>(8) IF FOR SOME REASON THE PROHIBITION ON CLASS ARBITRATIONS SET FORTH IN SUBSECTION (3) CANNOT BE ENFORCED, THEN THE AGREEMENT TO ARBITRATE WILL NOT APPLY.</strong></p>\r\r\r\r<p><strong>(9) IF FOR ANY REASON A CLAIM PROCEEDS IN COURT RATHER THAN THROUGH ARBITRATION, YOU AND VERIZON WIRELESS AGREE THAT THERE WILL NOT BE A JURY TRIAL. YOU AND VERIZON WIRELESS UNCONDITIONALLY WAIVE ANY RIGHT TO TRIAL BY JURY IN ANY ACTION, PROCEEDING OR COUNTERCLAIM ARISING OUT OF OR RELATING TO THIS AGREEMENT IN ANY WAY. IN THE EVENT OF LITIGATION, THIS PARAGRAPH MAY BE FILED TO SHOW A WRITTEN CONSENT TO A TRIAL BY THE COURT.</strong></p></div>\r\r\r\r<h4>About this Agreement</h4>\r\r\r\r<p>If we don't enforce our rights under this Agreement in one instance, that doesn't mean we won't or can't enforce those rights in any other instance. You cannot assign this Agreement or any of your rights or duties under it without our permission. However, we may assign this Agreement or any debt you owe us without notifying you. <strong>If you're a Postpay customer, please note that many notices we send to you will show up as messages on your monthly bill. If you have online billing, those notices will be deemed received by you when your online bill is available for viewing. If you get a paper bill, those notices will be deemed received by you three days after we mail the bill to you. If we send other notices to you, they will be considered received immediately if we send them to your wireless device, or to any email or fax number you've given us, or after three days if we mail them to your billing address. If you need to send notices to us, please send them to the customer service address on your latest bill.</strong></p>\r\r\r\r<p><strong>If you're a Prepaid customer and we send notices to you, they will be considered received immediately if we send them to your wireless device or to any email or fax number you've given us, or if we post them as a precall notification on your Service, or after three days if we mail them to the most current address we have for you. If you need to send notices to us, please send them to the Prepaid Customer Service address at verizonwireless.com/contactus</strong></p>\r\r\r\r<p><strong>If any part of this Agreement, including anything regarding the arbitration process (except for the prohibition on class arbitrations as explained in part 8 of the dispute resolution section above), is ruled invalid, that part may be removed from this Agreement.</strong></p>\r\r\r\r<p><strong>This Agreement and the documents it incorporates form the entire agreement between us. You can't rely on any other documents, or on what's said by any Sales or Customer Service Representatives, and you have no other rights regarding Service or this agreement.</strong> This agreement isn't for the benefit of any third party except our parent companies, affiliates, subsidiaries, agents, predecessors and successors in interest. Except where we've agreed otherwise elsewhere in this Agreement, this Agreement and any disputes covered by it are governed by federal law and the laws of the state encompassing the area code of your wireless phone number when you accepted this Agreement, without regard to the conflicts of laws and rules of that state.</p>\r\r\r\r<p>Last Updated: 11/18/16</p>",
      eppTermsAndConditions: null,
      eppCustomerType: false,
    },
  },
  statusMessage: 'Service completed Successfully.',
};
export default reviewOrderJSON;
