const pdpJSON = {
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "productDetails": {
      "badgeRetailIconImageName": null,
      "manufacturerDisplayName": "LG",
      "badgeTwoYearToolTip": null,
      "lineAccess": null,
      "dealInStoreStaticUrl": "https://forms.verizonwireless.com/dgf/optin/2012/06282012_omni_thankyou/index.html",
      "cqContent": null,
      "badgeEdgeIconImageName": null,
      "brandName": "LG",
      "categoryName": "connected-devices",
      "rectangularBadgeText": null,
      "badgeTwoYearIconImageName": null,
      "badgeRetailDisplayName": null,
      "deviceType": "3G Connected Device",
      "badgeEdgeToolTip": null,
      "skuDetails": [
        {
          "colorName": "Blue",
          "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_GizmoPal2_Light_Blue?$device-lg$",
          "upgradeOptionEllPDPLbl50": null,
          "promotionDetails": null,
          "restrictionFlag": false,
          "upgradeOptionEllPDPLbl70": null,
          "devicePrice": [
            {
              "mailInRebateAmount": 0,
              "priceListId": "fullRetailPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 0,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": false,
              "edgeEnabled": false,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 0,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": null,
              "contractPrice": "79.99",
              "contractTerm": 0,
              "originalPrice": 79.99,
              "creditOptionVOList": null,
              "fullRetailPrice": 79.99,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "No Early Termination Fee",
              "contractName": "Retail Price",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": null,
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            }
          ],
          "skuImageName": "LG_GizmoPal2_Light_Blue",
          "upgradeOptionEllPDPTip70": null,
          "selected": false,
          "upgradeOptionEllPDPTip50": null,
          "restrictionMessage": null,
          "sameDayDeliveryFlag": true,
          "capacity": null,
          "inventoryStatus": 1000,
          "deviceSkuId": "sku1820297",
          "devicePaymentPercentage": "100",
          "deviceSorId": "LG-VC110B",
          "skuListDiscountPricing": {
            "skuListPrice": [
              {
                "priceListId": "twoYearPriceListId",
                "price": 79.99
              },
              {
                "priceListId": "fullRetailPriceListId",
                "price": 79.99
              }
            ],
            "skuDiscountPrice": []
          },
          "colorImage": null,
          "upgradeOptionCode": "DP",
          "annualUpgradeEligible": false,
          "displayName": "GizmoPal&reg; 2 by LG in Blue",
          "colorCode": "#008080",
          "mobileAppImageName": null,
          "shippingDateLabel": null,
          "shippingDateStatusCode": 1000,
          "carouselImages": []
        },
        {
          "colorName": "Pink",
          "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_GizmoPal2_Pink?$device-lg$",
          "upgradeOptionEllPDPLbl50": null,
          "promotionDetails": null,
          "restrictionFlag": false,
          "upgradeOptionEllPDPLbl70": null,
          "devicePrice": [
            {
              "mailInRebateAmount": 0,
              "priceListId": "fullRetailPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 0,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": false,
              "edgeEnabled": false,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 0,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": null,
              "contractPrice": "79.99",
              "contractTerm": 0,
              "originalPrice": 79.99,
              "creditOptionVOList": null,
              "fullRetailPrice": 79.99,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "No Early Termination Fee",
              "contractName": "Retail Price",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": null,
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            }
          ],
          "skuImageName": "LG_GizmoPal2_Pink",
          "upgradeOptionEllPDPTip70": null,
          "selected": false,
          "upgradeOptionEllPDPTip50": null,
          "restrictionMessage": null,
          "sameDayDeliveryFlag": true,
          "capacity": null,
          "inventoryStatus": 1003,
          "deviceSkuId": "sku1820299",
          "devicePaymentPercentage": "100",
          "deviceSorId": "LG-VC110",
          "skuListDiscountPricing": {
            "skuListPrice": [
              {
                "priceListId": "twoYearPriceListId",
                "price": 79.99
              },
              {
                "priceListId": "fullRetailPriceListId",
                "price": 79.99
              }
            ],
            "skuDiscountPrice": []
          },
          "colorImage": null,
          "upgradeOptionCode": "DP",
          "annualUpgradeEligible": false,
          "displayName": "GizmoPal&reg; 2 by LG in Pink",
          "colorCode": "#f49ac2",
          "mobileAppImageName": null,
          "shippingDateLabel": "Ships bySep 08",
          "shippingDateStatusCode": 1003,
          "carouselImages": []
        }
      ],
      "pdpBadgeFullRetail": null,
      "creditOptionsAvailabilityVO": null,
      "deviceId": "dev5480086",
      "badgeTwoYearDisplayName": null,
      "seoCategoryName": "connected-devices",
      "marketingTout": null,
      "badgeEdgeDisplayName": null,
      "circularBadgeText": null,
      "canonicalURL": "connected-devices/lg-gizmopal-2/",
      "priceDisclaimer": "Your discounts have been applied.",
      "displayName": "GizmoPal&reg; 2",
      "pdpBadgePayment": null,
      "badgeRetailToolTip": null,
      "seoBrandName": "lg",
      "mobileAppImageName": null,
      "addToCartUrl": "/digital/cart/expressAddToCart",
      "connectedDevice": true,
      "volteEnabled": false,
      "numberShareEligible": false,
      "legacyPlanFlag": false,
      "editCart": false,
      "e911AddressRequired": false,
      "rio": false
    },
    "cpcDevice": false,
    "cpcContractTermList": null,
    "cpcGoToUrl": null,
    "goToSuccessUrl": null,
    "deviceSORIDForFeature": null
  },
  "statusMessage": "Service completed Successfully."
};

export default pdpJSON;
