const pdpJSON = {
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "productDetails": {
      "badgeRetailIconImageName": null,
      "manufacturerDisplayName": "Samsung",
      "badgeTwoYearToolTip": null,
      "lineAccess": null,
      "dealInStoreStaticUrl": "https://forms.verizonwireless.com/dgf/optin/2012/06282012_omni_thankyou/index.html",
      "cqContent": null,
      "badgeEdgeIconImageName": null,
      "brandName": "Samsung",
      "categoryName": "smartphones",
      "rectangularBadgeText": null,
      "badgeTwoYearIconImageName": null,
      "badgeRetailDisplayName": null,
      "deviceType": "4G Smartphone",
      "badgeEdgeToolTip": "$960 device payment purchase req. Less up to $480 trade-in/promo credit applied over 24 months; promo credit ends when balance is paid or line terminated; 0% APR. Fully paid-off eligible trade-in must be in good working and cosmetic condition.\r",
      "skuDetails": [
        {
          "colorName": "Midnight Black",
          "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Great_Black_VZW?$device-lg$",
          "upgradeOptionEllPDPLbl50": null,
          "promotionDetails": null,
          "restrictionFlag": false,
          "upgradeOptionEllPDPLbl70": null,
          "devicePrice": [
            {
              "mailInRebateAmount": 0,
              "priceListId": "fullRetailPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 0,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": true,
              "edgeEnabled": false,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 0,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": null,
              "contractPrice": "960.00",
              "contractTerm": 0,
              "originalPrice": 960,
              "creditOptionVOList": null,
              "fullRetailPrice": 960,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "No Early Termination Fee",
              "contractName": "Retail Price",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": null,
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            }
          ],
          "skuImageName": "Great_Black_VZW",
          "upgradeOptionEllPDPTip70": null,
          "selected": true,
          "upgradeOptionEllPDPTip50": null,
          "restrictionMessage": null,
          "sameDayDeliveryFlag": false,
          "capacity": "64GB",
          "inventoryStatus": 1002,
          "deviceSkuId": "sku2630270",
          "devicePaymentPercentage": "100",
          "deviceSorId": "SMN950UZKV",
          "skuListDiscountPricing": {
            "skuListPrice": [
              {
                "priceListId": "twoYearPriceListId",
                "price": 449.99
              },
              {
                "priceListId": "fullRetailPriceListId",
                "price": 960
              }
            ],
            "skuDiscountPrice": []
          },
          "colorImage": null,
          "upgradeOptionCode": "DP",
          "annualUpgradeEligible": false,
          "displayName": "Samsung Galaxy Note8 in Midnight Black",
          "colorCode": "#000000",
          "mobileAppImageName": null,
          "shippingDateLabel": "Ships bySep 14",
          "shippingDateStatusCode": 1002,
          "carouselImages": [
            "https://ss7.vzw.com/is/image/VerizonWireless/Great_Black_VZW",
            "https://ss7.vzw.com/is/image/VerizonWireless/Great_Black_VZW_Left",
            "https://ss7.vzw.com/is/image/VerizonWireless/Great_Black_VZW_Back",
            "https://ss7.vzw.com/is/image/VerizonWireless/Great_Black_VZW_Right",
            "https://ss7.vzw.com/is/image/VerizonWireless/Great_Black_VZW_Stylus"
          ]
        },
        {
          "colorName": "Orchid Gray",
          "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Great_Orchidgray?$device-lg$",
          "upgradeOptionEllPDPLbl50": null,
          "promotionDetails": null,
          "restrictionFlag": false,
          "upgradeOptionEllPDPLbl70": null,
          "devicePrice": [
            {
              "mailInRebateAmount": 0,
              "priceListId": "fullRetailPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 0,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": true,
              "edgeEnabled": false,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 0,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": null,
              "contractPrice": "960.00",
              "contractTerm": 0,
              "originalPrice": 960,
              "creditOptionVOList": null,
              "fullRetailPrice": 960,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "No Early Termination Fee",
              "contractName": "Retail Price",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": null,
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            }
          ],
          "skuImageName": "Great_Orchidgray",
          "upgradeOptionEllPDPTip70": null,
          "selected": false,
          "upgradeOptionEllPDPTip50": null,
          "restrictionMessage": null,
          "sameDayDeliveryFlag": false,
          "capacity": "64GB",
          "inventoryStatus": 1002,
          "deviceSkuId": "sku2630268",
          "devicePaymentPercentage": "100",
          "deviceSorId": "SMN950UZVV",
          "skuListDiscountPricing": {
            "skuListPrice": [
              {
                "priceListId": "twoYearPriceListId",
                "price": 449.99
              },
              {
                "priceListId": "fullRetailPriceListId",
                "price": 960
              }
            ],
            "skuDiscountPrice": []
          },
          "colorImage": null,
          "upgradeOptionCode": "DP",
          "annualUpgradeEligible": false,
          "displayName": "Samsung Galaxy Note8 In Orchid Gray",
          "colorCode": "#868499",
          "mobileAppImageName": null,
          "shippingDateLabel": "Ships bySep 14",
          "shippingDateStatusCode": 1002,
          "carouselImages": [
            "https://ss7.vzw.com/is/image/VerizonWireless/Great_Orchidgray",
            "https://ss7.vzw.com/is/image/VerizonWireless/Great_Orchidgray_Left",
            "https://ss7.vzw.com/is/image/VerizonWireless/Great_Orchidgray_Back",
            "https://ss7.vzw.com/is/image/VerizonWireless/Great_Orchidgray_Right",
            "https://ss7.vzw.com/is/image/VerizonWireless/Great_Orchidgray_Stylus"
          ]
        }
      ],
      "pdpBadgeFullRetail": null,
      "creditOptionsAvailabilityVO": null,
      "deviceId": "dev8520011",
      "badgeTwoYearDisplayName": null,
      "seoCategoryName": "smartphones",
      "marketingTout": null,
      "badgeEdgeDisplayName": "Get up to 50% off w/trade-in\r\r\r",
      "circularBadgeText": null,
      "canonicalURL": "smartphones/samsung-galaxy-note-8/",
      "priceDisclaimer": null,
      "displayName": "Galaxy Note8",
      "pdpBadgePayment": null,
      "badgeRetailToolTip": null,
      "seoBrandName": "samsung",
      "mobileAppImageName": null,
      "addToCartUrl": "/digital/cart/expressAddToCart",
      "connectedDevice": false,
      "volteEnabled": false,
      "numberShareEligible": false,
      "legacyPlanFlag": false,
      "e911AddressRequired": false,
      "rio": false
    },
    "cpcDevice": false,
    "cpcContractTermList": null,
    "cpcGoToUrl": null,
    "goToSuccessUrl": null,
    "deviceSORIDForFeature": null
  },
  "statusMessage": "Service completed Successfully."
};

export default pdpJSON;
