const pdpJSON = {
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "productDetails": {
      "badgeRetailIconImageName": null,
      "manufacturerDisplayName": "Google",
      "badgeTwoYearToolTip": null,
      "lineAccess": null,
      "dealInStoreStaticUrl": "https://forms.verizonwireless.com/dgf/optin/2012/06282012_omni_thankyou/index.html",
      "cqContent": null,
      "badgeEdgeIconImageName": null,
      "brandName": "Google",
      "categoryName": "smartphones",
      "rectangularBadgeText": null,
      "badgeTwoYearIconImageName": null,
      "badgeRetailDisplayName": null,
      "deviceType": "4G Smartphone",
      "badgeEdgeToolTip": null,
      "skuDetails": [
        {
          "colorName": "Very Silver",
          "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver?$device-lg$",
          "upgradeOptionEllPDPLbl50": null,
          "promotionDetails": null,
          "restrictionFlag": false,
          "upgradeOptionEllPDPLbl70": null,
          "devicePrice": [
            {
              "mailInRebateAmount": 0,
              "priceListId": "edgeRemainingMonthPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 769.99,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": true,
              "edgeEnabled": true,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 30,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": "/mo.",
              "contractPrice": "32.08",
              "contractTerm": 99,
              "originalPrice": 32.08,
              "creditOptionVOList": null,
              "fullRetailPrice": 769.99,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "$0 Down (for qualified customers) $32.08/mo for 24 months; 0% APR Retail Price: $769.99",
              "contractName": "24 Monthly Payments",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": "Up to $300 off w/ trade & unlimited.<a href=\"#\" data-aemurl=\"/wcms/reusable-content/offers/pixel-xl.html\" class=\"aemUrlContentOverlayOffer\"> See offer details.</a>",
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            },
            {
              "mailInRebateAmount": 0,
              "priceListId": "fullRetailPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 769.99,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": false,
              "edgeEnabled": false,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 0,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": null,
              "contractPrice": "769.99",
              "contractTerm": 0,
              "originalPrice": 769.99,
              "creditOptionVOList": null,
              "fullRetailPrice": 769.99,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "No Early Termination Fee",
              "contractName": "Retail Price",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": "Up to $300 off w/ trade & unlimited.<a href=\"#\" data-aemurl=\"/wcms/reusable-content/offers/pixel-xl.html\" class=\"aemUrlContentOverlayOffer\"> See offer details.</a>",
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            }
          ],
          "skuImageName": "Google_Marlin_Silver",
          "upgradeOptionEllPDPTip70": null,
          "selected": false,
          "upgradeOptionEllPDPTip50": null,
          "restrictionMessage": null,
          "sameDayDeliveryFlag": true,
          "capacity": "32GB",
          "inventoryStatus": 1000,
          "deviceSkuId": "sku2170533",
          "devicePaymentPercentage": "100",
          "deviceSorId": "G-2PW2100-021-B",
          "skuListDiscountPricing": {
            "skuListPrice": [
              {
                "priceListId": "edgeFullRetailPriceListId",
                "price": 769.99
              },
              {
                "priceListId": "twoYearPriceListId",
                "price": 319.99
              },
              {
                "priceListId": "edgeFirstMonthPriceListId",
                "price": 32.15
              },
              {
                "priceListId": "fullRetailPriceListId",
                "price": 769.99
              },
              {
                "priceListId": "edgeRemainingMonthPriceListId",
                "price": 32.08
              }
            ],
            "skuDiscountPrice": []
          },
          "colorImage": null,
          "upgradeOptionCode": "DP",
          "annualUpgradeEligible": false,
          "displayName": "Google Pixel XL 32GB in Very Silver",
          "colorCode": "#d7d7d7",
          "mobileAppImageName": "https://ss7.vzw.com/is/image/VerizonWireless/google-pixel-xl-silver?$device-lg$",
          "shippingDateLabel": null,
          "shippingDateStatusCode": 1000,
          "carouselImages": [
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver",
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver-side",
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver-back"
          ]
        },
        {
          "colorName": "Quite Black",
          "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Slate?$device-lg$",
          "upgradeOptionEllPDPLbl50": null,
          "promotionDetails": null,
          "restrictionFlag": false,
          "upgradeOptionEllPDPLbl70": null,
          "devicePrice": [
            {
              "mailInRebateAmount": 0,
              "priceListId": "edgeRemainingMonthPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 769.99,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": true,
              "edgeEnabled": true,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 30,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": "/mo.",
              "contractPrice": "32.08",
              "contractTerm": 99,
              "originalPrice": 32.08,
              "creditOptionVOList": null,
              "fullRetailPrice": 769.99,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "$0 Down (for qualified customers) $32.08/mo for 24 months; 0% APR Retail Price: $769.99",
              "contractName": "24 Monthly Payments",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": "Up to $300 off w/ trade & unlimited.<a href=\"#\" data-aemurl=\"/wcms/reusable-content/offers/pixel-xl.html\" class=\"aemUrlContentOverlayOffer\"> See offer details.</a>",
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            },
            {
              "mailInRebateAmount": 0,
              "priceListId": "fullRetailPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 769.99,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": false,
              "edgeEnabled": false,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 0,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": null,
              "contractPrice": "769.99",
              "contractTerm": 0,
              "originalPrice": 769.99,
              "creditOptionVOList": null,
              "fullRetailPrice": 769.99,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "No Early Termination Fee",
              "contractName": "Retail Price",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": "Up to $300 off w/ trade & unlimited.<a href=\"#\" data-aemurl=\"/wcms/reusable-content/offers/pixel-xl.html\" class=\"aemUrlContentOverlayOffer\"> See offer details.</a>",
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            }
          ],
          "skuImageName": "Google_Marlin_Slate",
          "upgradeOptionEllPDPTip70": null,
          "selected": false,
          "upgradeOptionEllPDPTip50": null,
          "restrictionMessage": null,
          "sameDayDeliveryFlag": true,
          "capacity": "32GB",
          "inventoryStatus": 1000,
          "deviceSkuId": "sku2170535",
          "devicePaymentPercentage": "100",
          "deviceSorId": "G-2PW2100-021-A",
          "skuListDiscountPricing": {
            "skuListPrice": [
              {
                "priceListId": "edgeFullRetailPriceListId",
                "price": 769.99
              },
              {
                "priceListId": "twoYearPriceListId",
                "price": 319.99
              },
              {
                "priceListId": "edgeFirstMonthPriceListId",
                "price": 32.15
              },
              {
                "priceListId": "fullRetailPriceListId",
                "price": 769.99
              },
              {
                "priceListId": "edgeRemainingMonthPriceListId",
                "price": 32.08
              }
            ],
            "skuDiscountPrice": []
          },
          "colorImage": null,
          "upgradeOptionCode": "DP",
          "annualUpgradeEligible": false,
          "displayName": "Google Pixel XL 32GB in Quite Black",
          "colorCode": "#000000",
          "mobileAppImageName": "https://ss7.vzw.com/is/image/VerizonWireless/google-pixel-xl-slate?$device-lg$",
          "shippingDateLabel": null,
          "shippingDateStatusCode": 1000,
          "carouselImages": [
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Slate",
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Slate-side",
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Slate-back"
          ]
        },
        {
          "colorName": "Very Silver",
          "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver?$device-lg$",
          "upgradeOptionEllPDPLbl50": null,
          "promotionDetails": null,
          "restrictionFlag": false,
          "upgradeOptionEllPDPLbl70": null,
          "devicePrice": [
            {
              "mailInRebateAmount": 0,
              "priceListId": "edgeRemainingMonthPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 869.99,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": true,
              "edgeEnabled": true,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 30,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": "/mo.",
              "contractPrice": "36.24",
              "contractTerm": 99,
              "originalPrice": 36.24,
              "creditOptionVOList": null,
              "fullRetailPrice": 869.99,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "$0 Down (for qualified customers) $36.24/mo for 24 months; 0% APR Retail Price: $869.99",
              "contractName": "24 Monthly Payments",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": "Up to $300 off w/ trade & unlimited.<a href=\"#\" data-aemurl=\"/wcms/reusable-content/offers/pixel-xl.html\" class=\"aemUrlContentOverlayOffer\"> See offer details.</a>",
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            },
            {
              "mailInRebateAmount": 0,
              "priceListId": "fullRetailPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 869.99,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": false,
              "edgeEnabled": false,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 0,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": null,
              "contractPrice": "869.99",
              "contractTerm": 0,
              "originalPrice": 869.99,
              "creditOptionVOList": null,
              "fullRetailPrice": 869.99,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "No Early Termination Fee",
              "contractName": "Retail Price",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": "Up to $300 off w/ trade & unlimited.<a href=\"#\" data-aemurl=\"/wcms/reusable-content/offers/pixel-xl.html\" class=\"aemUrlContentOverlayOffer\"> See offer details.</a>",
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            }
          ],
          "skuImageName": "Google_Marlin_Silver",
          "upgradeOptionEllPDPTip70": null,
          "selected": true,
          "upgradeOptionEllPDPTip50": null,
          "restrictionMessage": null,
          "sameDayDeliveryFlag": true,
          "capacity": "128GB",
          "inventoryStatus": 1003,
          "deviceSkuId": "sku2170532",
          "devicePaymentPercentage": "100",
          "deviceSorId": "G-2PW2100-022-B",
          "skuListDiscountPricing": {
            "skuListPrice": [
              {
                "priceListId": "edgeFullRetailPriceListId",
                "price": 869.99
              },
              {
                "priceListId": "twoYearPriceListId",
                "price": 419.99
              },
              {
                "priceListId": "edgeFirstMonthPriceListId",
                "price": 36.47
              },
              {
                "priceListId": "fullRetailPriceListId",
                "price": 869.99
              },
              {
                "priceListId": "edgeRemainingMonthPriceListId",
                "price": 36.24
              }
            ],
            "skuDiscountPrice": []
          },
          "colorImage": null,
          "upgradeOptionCode": "DP",
          "annualUpgradeEligible": false,
          "displayName": "Google Pixel XL 128GB in Very Silver",
          "colorCode": "#d7d7d7",
          "mobileAppImageName": "https://ss7.vzw.com/is/image/VerizonWireless/google-pixel-xl-silver?$device-lg$",
          "shippingDateLabel": "Ships bySep 21",
          "shippingDateStatusCode": 1003,
          "carouselImages": [
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver",
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver-side",
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Silver-back"
          ]
        },
        {
          "colorName": "Quite Black",
          "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Slate?$device-lg$",
          "upgradeOptionEllPDPLbl50": null,
          "promotionDetails": null,
          "restrictionFlag": false,
          "upgradeOptionEllPDPLbl70": null,
          "devicePrice": [
            {
              "mailInRebateAmount": 0,
              "priceListId": "edgeRemainingMonthPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 869.99,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": true,
              "edgeEnabled": true,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 30,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": "/mo.",
              "contractPrice": "36.24",
              "contractTerm": 99,
              "originalPrice": 36.24,
              "creditOptionVOList": null,
              "fullRetailPrice": 869.99,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "$0 Down (for qualified customers) $36.24/mo for 24 months; 0% APR Retail Price: $869.99",
              "contractName": "24 Monthly Payments",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": "Up to $300 off w/ trade & unlimited.<a href=\"#\" data-aemurl=\"/wcms/reusable-content/offers/pixel-xl.html\" class=\"aemUrlContentOverlayOffer\"> See offer details.</a>",
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            },
            {
              "mailInRebateAmount": 0,
              "priceListId": "fullRetailPriceListId",
              "bicOfferApplied": false,
              "ecpdDiscountOffer": false,
              "bicAdditionalContractText": null,
              "edgeFullRetailPrice": 869.99,
              "alwaysEligibleDownPaymentPercentage": null,
              "mailInRebateText": null,
              "sedEcpdDiscountPercentage": 0,
              "selected": false,
              "edgeEnabled": false,
              "earlyTerminationText": null,
              "rebateAmount": 0,
              "orgiginalMonthlyPrice": 0,
              "alwaysEligibleDownPaymentPercentageText": null,
              "orignalFullRetailPrice": 0,
              "edgeDownpayment": "0.00",
              "mailInRebateIndicator": false,
              "edgeType": null,
              "upgradeFee": 0,
              "activationFee": 0,
              "bicDiscountedContractPrice": 0,
              "waivedActivationFeePromo": false,
              "discountPrice": null,
              "ecpdDiscount": 0,
              "bicContractPrice": 0,
              "contractDetail": null,
              "contractPrice": "869.99",
              "contractTerm": 0,
              "originalPrice": 869.99,
              "creditOptionVOList": null,
              "fullRetailPrice": 869.99,
              "waivedUpgradeFeePromo": false,
              "contractTitle": "No Early Termination Fee",
              "contractName": "Retail Price",
              "contractToDevicePaymentEligibilityInd": false,
              "promotionDetails": "Up to $300 off w/ trade & unlimited.<a href=\"#\" data-aemurl=\"/wcms/reusable-content/offers/pixel-xl.html\" class=\"aemUrlContentOverlayOffer\"> See offer details.</a>",
              "badgePromoContentText": null,
              "alwaysEligibleForUpgrade": false,
              "puEligibleFlag": false
            }
          ],
          "skuImageName": "Google_Marlin_Slate",
          "upgradeOptionEllPDPTip70": null,
          "selected": false,
          "upgradeOptionEllPDPTip50": null,
          "restrictionMessage": null,
          "sameDayDeliveryFlag": true,
          "capacity": "128GB",
          "inventoryStatus": 1003,
          "deviceSkuId": "sku2170534",
          "devicePaymentPercentage": "100",
          "deviceSorId": "G-2PW2100-022-A",
          "skuListDiscountPricing": {
            "skuListPrice": [
              {
                "priceListId": "edgeFullRetailPriceListId",
                "price": 869.99
              },
              {
                "priceListId": "twoYearPriceListId",
                "price": 419.99
              },
              {
                "priceListId": "edgeFirstMonthPriceListId",
                "price": 36.47
              },
              {
                "priceListId": "fullRetailPriceListId",
                "price": 869.99
              },
              {
                "priceListId": "edgeRemainingMonthPriceListId",
                "price": 36.24
              }
            ],
            "skuDiscountPrice": []
          },
          "colorImage": null,
          "upgradeOptionCode": "DP",
          "annualUpgradeEligible": false,
          "displayName": "Google Pixel XL 128GB in Quite Black",
          "colorCode": "#000000",
          "mobileAppImageName": "https://ss7.vzw.com/is/image/VerizonWireless/google-pixel-xl-slate?$device-lg$",
          "shippingDateLabel": "Ships bySep 10",
          "shippingDateStatusCode": 1003,
          "carouselImages": [
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Slate",
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Slate-side",
            "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Slate-back"
          ]
        }
      ],
      "pdpBadgeFullRetail": null,
      "creditOptionsAvailabilityVO": null,
      "deviceId": "dev6720119",
      "badgeTwoYearDisplayName": null,
      "seoCategoryName": "smartphones",
      "marketingTout": null,
      "badgeEdgeDisplayName": "Up to $300 off w/ trade & unlimited.<a href=\"#\" data-aemurl=\"/wcms/reusable-content/offers/pixel-xl.html\" class=\"aemUrlContentOverlayOffer\"> See offer details.</a>",
      "circularBadgeText": null,
      "canonicalURL": "smartphones/google-pixel-xl/",
      "priceDisclaimer": "Your discounts have been applied.",
      "displayName": "Pixel XL, Phone by Google",
      "pdpBadgePayment": null,
      "badgeRetailToolTip": null,
      "seoBrandName": "google",
      "mobileAppImageName": "https://ss7.vzw.com/is/image/VerizonWireless/google-pixel-xl-silver?$device-lg$",
      "addToCartUrl": "/digital/cart/expressAddToCart",
      "connectedDevice": false,
      "volteEnabled": true,
      "numberShareEligible": false,
      "legacyPlanFlag": false,
      "editCart": false,
      "e911AddressRequired": false,
      "rio": false
    },
    "cpcDevice": false,
    "cpcContractTermList": null,
    "cpcGoToUrl": null,
    "goToSuccessUrl": null,
    "deviceSORIDForFeature": null
  },
  "statusMessage": "Service completed Successfully."
};

export default pdpJSON;
