const mdnJSON  =
//https://testman.verizonwireless.com/od/cust/auth/mtnDetail/json?flow=EUP&t=Kzg1oSs5k6GifXswC8wvBw==&selectedOption=upgrade

{
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "mtnDetailsList": [
      {
        "upgradeEligbile": true,
        "displayMtn": "765.620.4048",
        "mtn": "7656204048",
        "encryptedMTN": "LLXKnZkFb1lczPNqK3Gdfw==",
        "upgradeMessage": null,
        "nickname": "MATT                  JETER-4048",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/SamsungGusto2?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Basic Phone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Samsung",
        "deviceId": "",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Gusto&trade; 2 in Snow Silver",
        "deviceName": "Samsung Gusto II Snow Silver",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "buyoutRestrictedForEdge": false,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": " ",
        "daccCode": "00657",
        "deviceProdId": "dev40514",
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "765.620.3802",
        "mtn": "7656203802",
        "encryptedMTN": "Kzg1oSs5k6GifXswC8wvBw==",
        "upgradeMessage": null,
        "nickname": "MATT                  JETER-3802",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/sam_u810_renown?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": {
          "title": "Here's how you can upgrade today.",
          "subtitle": "You have a balance of $0.00",
          "paidToDate": "$0.00 Paid to date",
          "totalPrice": "$649.99 total price",
          "returnOptionTitle": null,
          "returnOptionDescription": null,
          "returnOptionLegal": null,
          "keepOptionTitle": null,
          "keepOptionDescription": "To upgrade this device, it must be paid off in full. If you would like to upgrade today, just pay off the remaining balance of $0.00",
          "keepOptionLegal": null,
          "legalDisclaimer": null,
          "edgeUpRequiredPercentage": "100",
          "paidAmountPercentage": "0.0",
          "upgradeSummary": null,
          "deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
          "deviceAgreementLink": null
        },
        "annualUpgradeMessage": null,
        "deviceType": "Basic Phone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Samsung",
        "deviceId": "",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Samsung Renown&trade;",
        "deviceName": "SCH-u810",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "buyoutRestrictedForEdge": false,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": " ",
        "daccCode": "00280",
        "deviceProdId": "dev40354",
        "annualUpgradeWarning": false
      }
    ],
    "accountLevelInEligibleCode": null,
    "accountLevelInEligibleMessage": null,
    "selectedMTN": null,
    "aalRedirect": null,
    "accountLevelInEligibleDetails": null,
    "cartRedirect": "/od/cust/auth/cart/getCartDetails",
    "shopLandingRedirect": "/od/cust/auth/shoplanding/",
    "mtnMainTitle": "Would you like to upgrade or add a new device?",
    "catergoryCode": null,
    "unlimitedPlan": "Y",
    "pastDueDetails": null,
    "submitAddALineUrl": "/od/cust/auth/submitaddaline",
    "customerType": null,
    "edgeEligible": true,
    "ajaxCallUrl": "/od/cust/auth/submitSummary",
    "ajaxCallSelectedMTN": "/od/cust/auth/mtnDetail/json?flow=EUP&t=",
    "redirectURL": null,
    "sharedPlan": false,
    "aalboxEnable": true,
    "aalAllowed": true
  },
  "cpcRequired": false
}

export default mdnJSON;
