const mdnJSON  ={
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "mtnDetailsList": [
      {
        "upgradeEligbile": true,
        "displayMtn": "520.456.2794",
        "mtn": "5204562794",
        "encryptedMTN": "24pE8AFT33RZBDJxKvLZ5w==",
        "upgradeMessage": null,
        "nickname": "HANK                  HENDERSO-2794",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/home_phone_connect_f256vw?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Other Devices",
        "familyType": "Tablet Internet Home",
        "familyTypeRestricted": true,
        "contractTermMisMatch": false,
        "brand": "Verizon",
        "deviceId": "",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Verizon Wireless Home Phone in Black",
        "deviceName": "Wireless Home Phone",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": " ",
        "daccCode": "00642",
        "deviceProdId": "dev40490",
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "520.559.0281",
        "mtn": "5205590281",
        "encryptedMTN": "wevtkoGgB6ITs8dlDieyXA==",
        "upgradeMessage": null,
        "nickname": "HANK                  HENDERSO-0281",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_G_Vista?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "LG",
        "deviceId": "352265060697700",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "LG G Vista in Black",
        "deviceName": "LG G Vista",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "4GE",
        "daccCode": "00783",
        "deviceProdId": "dev2880118",
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "520.559.0637",
        "mtn": "5205590637",
        "encryptedMTN": "QgvamgRPp+6Fu7HASsWi4w==",
        "upgradeMessage": null,
        "nickname": "HANK                  HENDERSO-0637",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S5_White?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Samsung",
        "deviceId": "990004853390880",
        "twoYearContract": {
          "title": "Get a new device before your contract ends.",
          "subTitle": "Getting a New Device",
          "endDate": "05/14/2018",
          "daysPercentage": "80.13698630136986",
          "description": "If you upgrade today, you can choose to make monthly payments for your new device or get it at the full retail price. If you pay monthly, we'll need 15.00% of the retail price as down payment.",
          "contractTermText": "2-year contract",
          "mtnSummarPageSubText": null,
          "daysRemainingText": "145 days remaining",
          "mtnSummaryPageSubTitle": "Getting a New Device",
          "mtnSummaryPageTitle": "Get a new device before your contract ends."
        },
        "annualUpgrade": false,
        "displayDeviceName": "Samsung Galaxy S&reg; 5 in Shimmery White",
        "deviceName": "Samsung Galaxy S 5 White",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "alwaysEligibleForUpgrade": true,
        "sorDeviceType": "4GE",
        "daccCode": "00772",
        "deviceProdId": "dev2080010",
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": false,
        "displayMtn": "520.508.3689",
        "mtn": "5205083689",
        "encryptedMTN": "DA9RHAnOgc8JRrTMDRI4OQ==",
        "upgradeMessage": null,
        "nickname": "HANK                  HENDERSO-3689",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/hum-plus-vzw?$device-thumb$",
        "inEligibleCode": "14",
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Other Devices",
        "familyType": "Connected",
        "familyTypeRestricted": true,
        "contractTermMisMatch": true,
        "brand": "Verizon",
        "deviceId": "",
        "twoYearContract": {
          "title": "Get a new device before your contract ends.",
          "subTitle": "Getting a New Device",
          "endDate": "06/17/2018",
          "daysPercentage": "75.47945205479452",
          "description": "If you upgrade today, you can choose to make monthly payments for your new device or get it at the full retail price. If you pay monthly, we'll need 15.00% of the retail price as down payment.",
          "contractTermText": "2-year contract",
          "mtnSummarPageSubText": null,
          "daysRemainingText": "179 days remaining",
          "mtnSummaryPageSubTitle": "Getting a New Device",
          "mtnSummaryPageTitle": "Get a new device before your contract ends."
        },
        "annualUpgrade": false,
        "displayDeviceName": "Hum<sup>&#43;</sup> by Verizon in Black",
        "deviceName": "Hum by Verizon",
        "eligibleUpgradeTypeList": [
          "Retail"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "alwaysEligibleForUpgrade": true,
        "sorDeviceType": " ",
        "daccCode": "00900",
        "deviceProdId": "dev5400100",
        "annualUpgradeWarning": false
      }
    ],
    "accountLevelInEligibleCode": null,
    "accountLevelInEligibleMessage": null,
    "selectedMTN": null,
    "aalRedirect": null,
    "accountLevelInEligibleDetails": null,
    "cartRedirect": "/preorder/cart/getCartDetails",
    "shopLandingRedirect": "/preorder/shoplanding/",
    "mtnMainTitle": "Would you like to upgrade or add a new device?",
    "catergoryCode": null,
    "unlimitedPlan": "N",
    "pastDueDetails": null,
    "submitAddALineUrl": "/preorder/submitaddaline",
    "customerType": null,
    "edgeEligible": true,
    "ajaxCallUrl": "/preorder/submitSummary",
    "ajaxCallSelectedMTN": null,
    "redirectURL": null,
    "sharedPlan": true,
    "aalboxEnable": true,
    "aalAllowed": true
  },
  "cpcRequired": false
}

export default mdnJSON;
