const mdnJSON = {
		"statusCode": "00",
		"errorMap": null,
		"output": {
			"mtnDetailsList": [{
				"upgradeEligbile": true,
				"displayMtn": "574.303.2781",
				"mtn": "5743032781",
				"encryptedMTN": "dMKWvNOqDE4Ts8dlDieyXA==",
				"upgradeMessage": null,
				"nickname": "TYLER REYES",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LGVN251%5FCosmos3?$device-lg$",
				"inEligibleCode": null,
				"inEligibleDetails": null,
				"loanInfo": null,
				"annualUpgradeMessage": null,
				"deviceType": "Basic Phone",
				"familyType": "Phone",
				"familyTypeRestricted": false,
				"contractTermMisMatch": false,
				"brand": "LG",
				"deviceId": "",
				"twoYearContract": {
					"title": "Get a new device before your contract ends.",
					"subTitle": "Getting a New Device",
					"endDate": "05/04/2018",
					"daysPercentage": "60.273972602739725",
					"description": "If you upgrade today, you can choose to make monthly payments for your new device or get it at the full retail price. If you pay monthly, we'll need 15.00% of the retail price as down payment.",
					"contractTermText": "2-year contract",
					"mtnSummarPageSubText": null,
					"daysRemainingText": "290 days remaining",
					"mtnSummaryPageSubTitle": "Getting a New Device",
					"mtnSummaryPageTitle": "Get a new device before your contract ends."
				},
				"annualUpgrade": false,
				"displayDeviceName": "Cosmos&trade; 3",
				"deviceName": "LG Cosmos&trade; 3 in Black",
				"eligibleUpgradeTypeList": ["Retail", "Edge"],
				"showTransferUpgrade": true,
				"transferUpgradeInProgress": false,
				"mtnAddedToTheCart": false,
				"deviceProductId": null,
				"alwaysEligibleForUpgrade": true,
				"myOffersPromoText": "Get upto $300 when you upgrade to iPhone 8",
				"annualUpgradeWarning": false
			}, {
				"upgradeEligbile": true,
				"displayMtn": "574.354.7324",
				"mtn": "5743547324",
				"encryptedMTN": "rOjf63jylPD5XrmcLScnQQ==",
				"upgradeMessage": null,
				"nickname": "TYLER REYES",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_Tab_E_Vertical?$device-lg$",
				"inEligibleCode": null,
				"inEligibleDetails": null,
				"loanInfo": null,
				"annualUpgradeMessage": null,
				"deviceType": "Tablet",
				"familyType": "Tablet Internet Home",
				"familyTypeRestricted": true,
				"contractTermMisMatch": false,
				"brand": "Samsung",
				"deviceId": "990005914440890",
				"twoYearContract": {
					"title": "Get a new device before your contract ends.",
					"subTitle": "Getting a New Device",
					"endDate": "06/15/2018",
					"daysPercentage": "54.52054794520548",
					"description": "If you upgrade today, you can choose to make monthly payments for your new device or get it at the full retail price. If you pay monthly, we'll need 15.00% of the retail price as down payment.",
					"contractTermText": "2-year contract",
					"mtnSummarPageSubText": null,
					"daysRemainingText": "332 days remaining",
					"mtnSummaryPageSubTitle": "Getting a New Device",
					"mtnSummaryPageTitle": "Get a new device before your contract ends."
				},
				"annualUpgrade": false,
				"displayDeviceName": "Galaxy Tab E",
				"deviceName": "Samsung Galaxy Tab E in Black",
				"eligibleUpgradeTypeList": ["Retail", "Edge"],
				"transferTakerMTNs": [999999999, 888888888],
				"showTransferUpgrade": true,
				"mtnAddedToTheCart": false,
				"deviceProductId": null,
				"alwaysEligibleForUpgrade": true,
				"myOffersPromoText": null,
				"annualUpgradeWarning": false
			}, {
				"upgradeEligbile": true,
				"displayMtn": "574.354.1233",
				"mtn": "5743541233",
				"encryptedMTN": "brQcTx7rD3LJAJWpTFX0IQ==",
				"upgradeMessage": null,
				"nickname": "TYLER REYES",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Hero2_Gold?$device-lg$",
				"inEligibleCode": null,
				"inEligibleDetails": null,
				"loanInfo": {
					"title": "Here's how you can upgrade today.",
					"subtitle": "You have a balance of $594.00",
					"paidToDate": "Paid to date:$198.00",
					"totalPrice": "$792.00 total price",
					"returnOptionTitle": "Return your device and pay $163.28",
					"returnOptionDescription": "If your device is working properly, send it in after you upgrade and you're all set.",
					"keepOptionTitle": "Keep your device and pay $653.28",
					"keepOptionDescription": "To upgrade this device, it must be paid off in full. If you would like to upgrade today, just pay off the remaining balance of $594.00",
					"edgeUpRequiredPercentage": 100.0,
					"paidAmountPercentage": "25",
					"upgradeSummary": null,
					"deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
					"deviceAgreementLink": null,
					"remainingAmountText": "$594.00 remaining",
					"pendingInstallmentText": "18 of 24 payments completed",
					"subtitleDescriptionText": null
				},
				"annualUpgradeMessage": null,
				"deviceType": "Smartphone",
				"familyType": "Phone",
				"familyTypeRestricted": false,
				"contractTermMisMatch": false,
				"brand": "Samsung",
				"deviceId": "357753074380315",
				"twoYearContract": null,
				"annualUpgrade": false,
				"displayDeviceName": "Galaxy S7 edge",
				"deviceName": "Samsung Galaxy S7 edge 32GB in Gold Platinum",
				"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
				"showTransferUpgrade": true,
				"transferTakerMTNs": [999999999, 888888888],
				"mtnAddedToTheCart": false,
				"deviceProductId": null,
				"alwaysEligibleForUpgrade": false,
				"myOffersPromoText": null,
				"annualUpgradeWarning": false
			}, {
				"upgradeEligbile": true,
				"displayMtn": "574.261.4159",
				"mtn": "5742614159",
				"encryptedMTN": "Ie0tqR3/E6F+G1mv3uL+ag==",
				"upgradeMessage": null,
				"nickname": "TYLER REYES",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Novatel_MiFi7730L?$device-lg$",
				"inEligibleCode": null,
				"inEligibleDetails": null,
				"loanInfo": null,
				"annualUpgradeMessage": null,
				"deviceType": "Internet",
				"familyType": "Tablet Internet Home",
				"familyTypeRestricted": true,
				"contractTermMisMatch": false,
				"brand": "Verizon",
				"deviceId": "990006382056702",
				"twoYearContract": {
					"title": "Get a new device before your contract ends.",
					"subTitle": "Getting a New Device",
					"endDate": "05/01/2019",
					"daysPercentage": "10.684931506849315",
					"description": "If you upgrade today, you can choose to make monthly payments for your new device or get it at the full retail price. If you pay monthly, we'll need 30.00% of the retail price as down payment.",
					"contractTermText": "2-year contract",
					"mtnSummarPageSubText": null,
					"daysRemainingText": "652 days remaining",
					"mtnSummaryPageSubTitle": "Getting a New Device",
					"mtnSummaryPageTitle": "Get a new device before your contract ends."
				},
				"annualUpgrade": false,
				"displayDeviceName": "Jetpack&reg; MiFi&reg; 7730L",
				"deviceName": "Verizon Jetpack&reg; 4G LTE MHS MiFi 7730L",
				"eligibleUpgradeTypeList": ["Retail", "Edge"],
				"transferTakerMTNs": [999999999, 888888888],
				"showTransferUpgrade": true,
				"mtnAddedToTheCart": false,
				"deviceProductId": null,
				"alwaysEligibleForUpgrade": true,
				"myOffersPromoText": null,
				"annualUpgradeWarning": false
			}],
			"accountLevelInEligibleCode": null,
			"accountLevelInEligibleMessage": null,
			"selectedMTN": null,
			"aalRedirect": "/digital/shoplanding/?flow=AAL",
			"accountLevelInEligibleDetails": null,
			"cartRedirect": "/digital/cart/getCartDetails",
			"shopLandingRedirect": "/digital/shoplanding/",
			"mtnMainTitle": "Would you like to upgrade or add a new device?",
			"unlimitedPlan": "Y",
			"pastDueDetails": null,
			"aalAllowed": true,
			"aalboxEnable": true,
			"transferGiverMTNs": ["2102433567", "2546400503", "9123466258"],
			"transferTakerMTNs": ["2544470061", "7572012545"],
		},
		"ajaxCallUrl": "/digital/smartphones/"
	};

export default mdnJSON;
