

const mdnJSON = {
	"statusCode": "00",
	"errorMap": null,
	"output": {
		"mtnDetailsList": [{
			"upgradeEligbile": true,
			"displayMtn": "316.531.2490",
			"mtn": "3165312490",
			"encryptedMTN": "RmDAj3Gj6qPZHwSjhbr6kw==",
			"upgradeMessage": null,
			"nickname": "KENNY                 REYES-2490",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/home_phone_connect_f256vw?$device-thumb$",
			"inEligibleCode": null,
			"inEligibleDetails": null,
			"loanInfo": null,
			"annualUpgradeMessage": null,
			"deviceType": "Other Devices",
			"familyType": "Tablet Internet Home",
			"familyTypeRestricted": true,
			"contractTermMisMatch": false,
			"brand": "Verizon",
			"deviceId": "",
			"twoYearContract": null,
			"annualUpgrade": false,
			"displayDeviceName": "Home Phone Connect F256VW",
			"deviceName": "Home Phone Connect F256",
			"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
			"mtnAddedToTheCart": false,
			"lineSharingIndicator": null,
			"buyoutRestrictedForEdge": false,
			"showTransferUpgrade": false,
			"transferredFromMtns": null,
			"alwaysEligibleForUpgrade": false,
			"sorDeviceType": " ",
			"daccCode": "00642",
			"deviceProdId": "dev40490",
			"estimatedTradeInValue": "0.00",
			"annualUpgradeWarning": false
		}, {
			"upgradeEligbile": true,
			"displayMtn": "316.640.5114",
			"mtn": "3166405114",
			"encryptedMTN": "97L7aXF6a3YmdCLyD0FFXA==",
			"upgradeMessage": null,
			"nickname": "KENNY                 REYES-5114",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/LG_Exalt2?$device-thumb$",
			"inEligibleCode": null,
			"inEligibleDetails": null,
			"loanInfo": {
				"title": "Here's how you can upgrade today.",
				"subtitle": "You have a balance of $0.00",
				"paidToDate": "$31.43 Paid to date",
				"totalPrice": "$149.99 total price",
				"returnOptionTitle": null,
				"returnOptionDescription": null,
				"returnOptionLegal": null,
				"keepOptionTitle": null,
				"keepOptionDescription": "To upgrade this device, it must be paid off in full. If you would like to upgrade today, just pay off the remaining balance of $0.00",
				"keepOptionLegal": null,
				"legalDisclaimer": null,
				"bogoInd": null,
				"bogoPresent": false,
				"bogoUpgradeMessage": "",
				"edgeUpRequiredPercentage": "100",
				"paidAmountPercentage": "21.0",
				"upgradeSummary": null,
				"deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
				"deviceAgreementLink": null
			},
			"annualUpgradeMessage": null,
			"deviceType": "Basic Phone",
			"familyType": "Phone",
			"familyTypeRestricted": false,
			"contractTermMisMatch": false,
			"brand": "LG",
			"deviceId": "",
			"twoYearContract": null,
			"annualUpgrade": false,
			"displayDeviceName": "LG Exalt&trade; II in Black",
			"deviceName": "LG Exalt 2",
			"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
			"mtnAddedToTheCart": false,
			"lineSharingIndicator": null,
			"buyoutRestrictedForEdge": false,
			"showTransferUpgrade": false,
			"transferredFromMtns": null,
			"alwaysEligibleForUpgrade": false,
			"sorDeviceType": " ",
			"daccCode": "00883",
			"deviceProdId": "dev5080048",
			"estimatedTradeInValue": "0.00",
			"annualUpgradeWarning": false
		}, {
			"upgradeEligbile": true,
			"displayMtn": "316.644.7405",
			"mtn": "3166447405",
			"encryptedMTN": "FNgbhRw88h9ikUE8vbkqLA==",
			"upgradeMessage": null,
			"nickname": "KENNY                 REYES-7405",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iPhoneSE_rsGld?$device-thumb$",
			"inEligibleCode": null,
			"inEligibleDetails": null,
			"loanInfo": {
				"title": "Here's how you can upgrade today.",
				"subtitle": "You have a balance of $0.00",
				"paidToDate": "$333.35 Paid to date",
				"totalPrice": "$499.99 total price",
				"returnOptionTitle": null,
				"returnOptionDescription": null,
				"returnOptionLegal": null,
				"keepOptionTitle": null,
				"keepOptionDescription": "To upgrade this device, it must be paid off in full. If you would like to upgrade today, just pay off the remaining balance of $0.00",
				"keepOptionLegal": null,
				"legalDisclaimer": null,
				"bogoInd": null,
				"bogoPresent": false,
				"bogoUpgradeMessage": "",
				"edgeUpRequiredPercentage": "100",
				"paidAmountPercentage": "67.0",
				"upgradeSummary": null,
				"deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
				"deviceAgreementLink": null
			},
			"annualUpgradeMessage": null,
			"deviceType": "Smartphone",
			"familyType": "Phone",
			"familyTypeRestricted": false,
			"contractTermMisMatch": false,
			"brand": "Apple",
			"deviceId": "355433073088200",
			"twoYearContract": null,
			"annualUpgrade": false,
			"displayDeviceName": "Apple&reg; iPhone&reg; SE 64GB in Rose Gold",
			"deviceName": "IPHONE SE ROSE GOLD 64GB",
			"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
			"mtnAddedToTheCart": false,
			"lineSharingIndicator": null,
			"buyoutRestrictedForEdge": false,
			"showTransferUpgrade": false,
			"transferredFromMtns": null,
			"alwaysEligibleForUpgrade": false,
			"sorDeviceType": "4GE",
			"daccCode": "00924",
			"deviceProdId": "dev6000008",
			"estimatedTradeInValue": "0.00",
			"annualUpgradeWarning": false
		}],
		"accountLevelInEligibleCode": null,
		"accountLevelInEligibleMessage": null,
		"selectedMTN": null,
		"aalRedirect": null,
		"accountLevelInEligibleDetails": null,
		"cartRedirect": "/od/cust/auth/cart/getCartDetails",
		"shopLandingRedirect": "/od/cust/auth/shoplanding/",
		"mtnMainTitle": "Would you like to upgrade or add a new device?",
		"catergoryCode": null,
		"unlimitedPlan": "N",
		"pastDueDetails": null,
		"submitAddALineUrl": "/od/cust/auth/submitaddaline",
		"transferGiverMTNs": null,
		"transferTakerMTNs": null,
		"customerType": null,
		"edgeEligible": true,
		"ajaxCallUrl": "/od/cust/auth/submitSummary",
		"ajaxCallSelectedMTN": "/od/cust/auth/mtnDetail/json?flow=EUP&t=",
		"redirectURL": null,
		"sharedPlan": true,
		"submitByodRedirectUrl": "/od/cust/auth/byod/bring-your-own-device",
		"aalAllowed": true,
		"aalboxEnable": false,
		"byodAllowed": true
	},
	"cpcRequired": false
}

export default mdnJSON;
