exports.mtnDetailAjax = {
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "mtnDetailsList": [{
      "upgradeEligbile": true,
      "displayMtn": "808.268.0598",
      "mtn": "8082680598",
      "encryptedMTN": "Nzp56LTU7MSlxXhwY297Fg==",
      "upgradeMessage": null,
      "nickname": "ETHAN               K GRADY-0598",
      "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-matblk?$device-thumb$",
      "inEligibleCode": null,
      "inEligibleDetails": null,
      "loanInfo": {
        "title": "Want to upgrade early?",
        "subtitle": "You're $162.55 into paying off your current device",
        "paidToDate": "$162.55 Paid to date",
        "totalPrice": "$649.99 total price",
        "returnOptionTitle": "Return your device and pay $162.44",
        "returnOptionDescription": "Send in your device after you upgrade if its in working condition and youre all set.",
        "returnOptionLegal": "The device you return will be applied to your remaining balance and cant be used as a trade-in towards a new device or promotion.",
        "keepOptionTitle": "Pay $487.44 and Keep your device",
        "keepOptionDescription": "Pay off your remaining balance and keep your old device",
        "keepOptionLegal": "Trade-in value can be used torwards a new device or promotion.",
        "legalDisclaimer": "Subject to credit authorization, account standing and other qualifying conditions. Taxes and fees not included.",
        "edgeUpRequiredPercentage": 10.0,
        "paidAmountPercentage": "25.0",
        "upgradeSummary": null,
        "deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
        "deviceAgreementLink": null
      },
      "annualUpgradeMessage": null,
      "deviceType": "Smartphone",
      "familyType": "Phone",
      "familyTypeRestricted": false,
      "contractTermMisMatch": false,
      "brand": "Apple",
      "deviceId": "355824083188759",
      "twoYearContract": {
        "title": "Get a new device before your contract ends.",
        "subTitle": "Getting a New Device",
        "endDate": "05/14/2018",
        "daysPercentage": "80.13698630136986",
        "description": "If you upgrade today, you can choose to make monthly payments for your new device or get it at the full retail price. If you pay monthly, we'll need 15.00% of the retail price as down payment.",
        "contractTermText": "2-year contract",
        "mtnSummarPageSubText": null,
        "daysRemainingText": "145 days remaining",
        "mtnSummaryPageSubTitle": "Getting a New Device",
        "mtnSummaryPageTitle": "Get a new device before your contract ends."
      },
      "annualUpgrade": false,
      "displayDeviceName": "Apple&reg; iPhone&reg; 7 32GB in Black",
      "deviceName": "iPhone 7 Black 32GB",
      "eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
      "mtnAddedToTheCart": false,
      "lineSharingIndicator": "",
      "alwaysEligibleForUpgrade": false,
      "sorDeviceType": "4GE",
      "daccCode": "00969",
      "deviceProdId": "dev6640012",
      "annualUpgradeWarning": false
    }],
    "accountLevelInEligibleCode": null,
    "accountLevelInEligibleMessage": null,
    "selectedMTN": null,
    "aalRedirect": null,
    "accountLevelInEligibleDetails": null,
    "cartRedirect": "/od/cust/auth/cart/getCartDetails",
    "shopLandingRedirect": "/od/cust/auth/shoplanding/",
    "mtnMainTitle": "Would you like to add another line?",
    "catergoryCode": null,
    "unlimitedPlan": "N",
    "pastDueDetails": null,
    "submitAddALineUrl": "/od/cust/auth/submitaddaline",
    "customerType": null,
    "edgeEligible": true,
    "ajaxCallUrl": "/od/cust/auth/submitSummary",
    "ajaxCallSelectedMTN": "/od/cust/auth/mtnDetail/json?flow=EUP&t=",
    "redirectURL": null,
    "sharedPlan": true,
    "aalboxEnable": true,
    "aalAllowed": true
  },
  "cpcRequired": false
};
