const mdnJSON  =
{
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "mtnDetailsList": [
      {
        "upgradeEligbile": false,
        "displayMtn": "408.205.0474",
        "mtn": "4082050474",
        "encryptedMTN": "RuD3nMBRDnNMz+DYJM0WQg==",
        "upgradeMessage": null,
        "nickname": "TYLER                 BOWER-0474",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_ipadmini_retina_silver?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Tablet",
        "familyType": "Tablet Internet Home",
        "familyTypeRestricted": true,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "3586770546487902",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Apple&reg; iPad&reg; mini 2 16GB in Silver",
        "deviceName": "IPAD MINI RETINA 16GB SILVER",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "buyoutRestrictedForEdge": false,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "4GE",
        "daccCode": "00684",
        "deviceProdId": "dev1080028",
        "estimatedTradeInValue": "0.00",
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": false,
        "displayMtn": "408.834.2776",
        "mtn": "4088342776",
        "encryptedMTN": "qa/95Q6Cj/UNAq0hbkE33g==",
        "upgradeMessage": null,
        "nickname": "TYLER                 BOWER-2776",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Ellipsis_2_Jetpack_Franklin_Wireless_MHS800L_REVISED?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Internet",
        "familyType": "Tablet Internet Home",
        "familyTypeRestricted": true,
        "contractTermMisMatch": false,
        "brand": "Verizon",
        "deviceId": "354197072865708",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Verizon Ellipsis&reg; Jetpack&reg; MHS800L in Black",
        "deviceName": "Ellipsis Jetpack MHS800L",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "buyoutRestrictedForEdge": false,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "4GE",
        "daccCode": "00748",
        "deviceProdId": "dev3400011",
        "estimatedTradeInValue": "0.00",
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": false,
        "displayMtn": "831.359.0326",
        "mtn": "8313590326",
        "encryptedMTN": "jcdTfMDWqSl/LzCeGMYNVg==",
        "upgradeMessage": null,
        "nickname": "TYLER                 BOWER-0326",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple%5Fipadmini%5Fwhite?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Tablet",
        "familyType": "Tablet Internet Home",
        "familyTypeRestricted": true,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "9900024061969803",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Apple&reg; iPad&reg; mini 16GB in White",
        "deviceName": "IPAD MINI 16GB WHITE",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "buyoutRestrictedForEdge": false,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "4GE",
        "daccCode": "00684",
        "deviceProdId": "dev1400031",
        "estimatedTradeInValue": "0.00",
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": false,
        "displayMtn": "408.568.9865",
        "mtn": "4085689865",
        "encryptedMTN": "6o2OG32r6xb0DQYlumQRpw==",
        "upgradeMessage": null,
        "nickname": "TYLER                 BOWER-9865",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-spgry-front?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": {
          "title": "Here's how you can upgrade today.",
          "subtitle": "You have a balance of $0.00",
          "paidToDate": "$325.03 Paid to date",
          "totalPrice": "$649.99 total price",
          "returnOptionTitle": null,
          "returnOptionDescription": null,
          "returnOptionLegal": null,
          "keepOptionTitle": null,
          "keepOptionDescription": "To upgrade this device, it must be paid off in full. If you would like to upgrade today, just pay off the remaining balance of $0.00",
          "keepOptionLegal": null,
          "legalDisclaimer": null,
          "bogoInd": null,
          "bogoPresent": false,
          "bogoUpgradeMessage": "",
          "edgeUpRequiredPercentage": "100",
          "paidAmountPercentage": "50.0",
          "upgradeSummary": null,
          "deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
          "deviceAgreementLink": null
        },
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "359155075080597",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Apple&reg; iPhone&reg; 6s 128GB in Space Gray",
        "deviceName": "iPhone 6S 128GB Space Gray",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "buyoutRestrictedForEdge": false,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "4GE",
        "daccCode": "00867",
        "deviceProdId": "dev5160002",
        "estimatedTradeInValue": "0.00",
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": false,
        "displayMtn": "831.331.3162",
        "mtn": "8313313162",
        "encryptedMTN": "IQ6nV+064c4fBZpzgERVAg==",
        "upgradeMessage": null,
        "nickname": "TYLER                 BOWER-3162",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-rsgld-front?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": {
          "title": "Here's how you can upgrade today.",
          "subtitle": "You have a balance of $0.00",
          "paidToDate": "$656.27 Paid to date",
          "totalPrice": "$749.99 total price",
          "returnOptionTitle": null,
          "returnOptionDescription": null,
          "returnOptionLegal": null,
          "keepOptionTitle": null,
          "keepOptionDescription": "To upgrade this device, it must be paid off in full. If you would like to upgrade today, just pay off the remaining balance of $0.00",
          "keepOptionLegal": null,
          "legalDisclaimer": null,
          "bogoInd": null,
          "bogoPresent": false,
          "bogoUpgradeMessage": "",
          "edgeUpRequiredPercentage": "50",
          "paidAmountPercentage": "88.0",
          "upgradeSummary": null,
          "deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
          "deviceAgreementLink": null
        },
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "355691071814370",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Apple&reg; iPhone&reg; 6s 64GB in Rose Gold",
        "deviceName": "iPhone 6S 64GB Rose Gold",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "buyoutRestrictedForEdge": false,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "4GE",
        "daccCode": "00867",
        "deviceProdId": "dev5160002",
        "estimatedTradeInValue": "0.00",
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": false,
        "displayMtn": "831.419.1132",
        "mtn": "8314191132",
        "encryptedMTN": "EafS6SgL252tQ0oOd1Lw2g==",
        "upgradeMessage": null,
        "nickname": "TYLER                 BOWER-1132",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-rsgld-front?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": {
          "title": "Here's how you can upgrade today.",
          "subtitle": "You have a balance of $0.00",
          "paidToDate": "$577.50 Paid to date",
          "totalPrice": "$660.00 total price",
          "returnOptionTitle": null,
          "returnOptionDescription": null,
          "returnOptionLegal": null,
          "keepOptionTitle": null,
          "keepOptionDescription": "To upgrade this device, it must be paid off in full. If you would like to upgrade today, just pay off the remaining balance of $0.00",
          "keepOptionLegal": null,
          "legalDisclaimer": null,
          "bogoInd": null,
          "bogoPresent": false,
          "bogoUpgradeMessage": "",
          "edgeUpRequiredPercentage": "50",
          "paidAmountPercentage": "88.0",
          "upgradeSummary": null,
          "deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
          "deviceAgreementLink": null
        },
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "355422077780710",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Apple&reg; iPhone&reg; 6s 64GB in Rose Gold",
        "deviceName": "iPhone 6S 64GB Rose Gold",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "buyoutRestrictedForEdge": false,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "4GE",
        "daccCode": "00867",
        "deviceProdId": "dev5160002",
        "estimatedTradeInValue": "0.00",
        "annualUpgradeWarning": false
      }
    ],
    "accountLevelInEligibleCode": null,
    "accountLevelInEligibleMessage": null,
    "selectedMTN": null,
    "aalRedirect": "/od/cust/auth/checkout/npaNxxNumber?flow=AAL",
    "accountLevelInEligibleDetails": null,
    "cartRedirect": "/od/cust/auth/cart/getCartDetails",
    "shopLandingRedirect": "/od/cust/auth/shoplanding/",
    "mtnMainTitle": "Would you like to add another line?",
    "catergoryCode": null,
    "unlimitedPlan": "N",
    "pastDueDetails": {
      "pastDueAmount": "371.37",
      "pastDueIgnored": true,
      "pastDueDate": null,
      "nextLink": "/od/cust/auth/submitpastdue",
      "noThanksLink": "https://vzwqa1.verizonwireless.com/ui/hub/secure/overview",
      "pastDueAccepted": false,
      "gotoUrl": null,
      "pastDuePaid": false,
      "pastDueAccount": true
    },
    "submitAddALineUrl": "/od/cust/auth/submitaddaline",
    "customerType": null,
    "edgeEligible": false,
    "ajaxCallUrl": "/od/cust/auth/submitSummary",
    "ajaxCallSelectedMTN": "/od/cust/auth/mtnDetail/json?flow=EUP&t=",
    "redirectURL": null,
    "sharedPlan": true,
    "submitByodRedirectUrl": "/od/cust/auth/byod/bring-your-own-device",
    "aalAllowed": true,
    "aalboxEnable": true
  },
  "cpcRequired": false
}

export default mdnJSON;
