exports.undoTransferUpgrade = {
	"statusCode": "00",
	"errorMap": null,
	"output": {
		"mtnDetailsList": [{
			"upgradeEligbile": true,
			"displayMtn": "210.243.3567",
			"mtn": "2102433567",
			"encryptedMTN": "Bb6invPILtyaNWQdldONkA==",
			"upgradeMessage": null,
			"nickname": "TOM                   NICKS-3567",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/generic_phone?$device-thumb$",
			"inEligibleCode": null,
			"inEligibleDetails": null,
			"loanInfo": null,
			"annualUpgradeMessage": null,
			"deviceType": "Other Devices",
			"familyType": "Phone",
			"familyTypeRestricted": true,
			"contractTermMisMatch": false,
			"brand": null,
			"deviceId": "",
			"twoYearContract": null,
			"annualUpgrade": false,
			"displayDeviceName": "ECom Service SKU",
			"deviceName": null,
			"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
			"mtnAddedToTheCart": false,
			"lineSharingIndicator": null,
			"buyoutRestrictedForEdge": false,
			"showTransferUpgrade": true,
			"transferUpgradeInProgress": false,
			"transferredFromMtn": null,
			"transferredToMtn": null,
			"alwaysEligibleForUpgrade": false,
			"sorDeviceType": null,
			"daccCode": null,
			"deviceProdId": "dev4800001",
			"estimatedTradeInValue": "0.00",
			"annualUpgradeWarning": false
		}, {
			"upgradeEligbile": true,
			"displayMtn": "254.640.0503",
			"mtn": "2546400503",
			"encryptedMTN": "GbjvcJL/v5JDoiZkz426Mw==",
			"upgradeMessage": null,
			"nickname": "TOM                   NICKS-0503",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/generic_phone?$device-thumb$",
			"inEligibleCode": null,
			"inEligibleDetails": null,
			"loanInfo": null,
			"annualUpgradeMessage": null,
			"deviceType": "Other Devices",
			"familyType": "Phone",
			"familyTypeRestricted": true,
			"contractTermMisMatch": false,
			"brand": null,
			"deviceId": "358536057178551",
			"twoYearContract": null,
			"annualUpgrade": false,
			"displayDeviceName": "ECom Service SKU",
			"deviceName": null,
			"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
			"mtnAddedToTheCart": false,
			"lineSharingIndicator": null,
			"buyoutRestrictedForEdge": false,
			"showTransferUpgrade": true,
			"transferUpgradeInProgress": false,
			"transferredFromMtn": null,
			"transferredToMtn": null,
			"alwaysEligibleForUpgrade": false,
			"sorDeviceType": null,
			"daccCode": null,
			"deviceProdId": "dev4800001",
			"estimatedTradeInValue": "0.00",
			"annualUpgradeWarning": false
		}, {
			"upgradeEligbile": true,
			"displayMtn": "912.346.6258",
			"mtn": "9123466258",
			"encryptedMTN": "zcgy/IoofhoFkAUQuWEoaA==",
			"upgradeMessage": null,
			"nickname": "TOM                   NICKS-6258",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/generic_phone?$device-thumb$",
			"inEligibleCode": null,
			"inEligibleDetails": null,
			"loanInfo": null,
			"annualUpgradeMessage": null,
			"deviceType": "Other Devices",
			"familyType": "Phone",
			"familyTypeRestricted": true,
			"contractTermMisMatch": false,
			"brand": null,
			"deviceId": "359296069620616",
			"twoYearContract": null,
			"annualUpgrade": false,
			"displayDeviceName": "ECom Service SKU",
			"deviceName": null,
			"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
			"mtnAddedToTheCart": false,
			"lineSharingIndicator": null,
			"buyoutRestrictedForEdge": false,
			"showTransferUpgrade": true,
			"transferUpgradeInProgress": false,
			"transferredFromMtn": null,
			"transferredToMtn": null,
			"alwaysEligibleForUpgrade": false,
			"sorDeviceType": null,
			"daccCode": null,
			"deviceProdId": "dev4800001",
			"estimatedTradeInValue": "0.00",
			"annualUpgradeWarning": false
		}, {
			"upgradeEligbile": true,
			"displayMtn": "254.447.0061",
			"mtn": "2544470061",
			"encryptedMTN": "qs3zlehVZvDzUfPMmeKb1Q==",
			"upgradeMessage": null,
			"nickname": "TOM                   NICKS-0061",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/generic_phone?$device-thumb$",
			"inEligibleCode": null,
			"inEligibleDetails": null,
			"loanInfo": null,
			"annualUpgradeMessage": null,
			"deviceType": "Other Devices",
			"familyType": "Phone",
			"familyTypeRestricted": true,
			"contractTermMisMatch": false,
			"brand": null,
			"deviceId": "359775073560389",
			"twoYearContract": {
				"title": "Want to upgrade early?",
				"subTitle": "You can upgrade today by buying your device or wait until your contract ends in 236 days",
				"endDate": "10/31/2018",
				"daysPercentage": "67.67123287671232",
				"description": "Your device was purchased under a 2-year contract agreement. You can upgrade to a new phone today at the retail price or you can wait until your contract ends.",
				"contractTermText": null,
				"mtnSummarPageSubText": null,
				"daysRemainingText": null,
				"mtnSummaryPageSubTitle": null,
				"mtnSummaryPageTitle": null
			},
			"annualUpgrade": false,
			"displayDeviceName": "ECom Service SKU",
			"deviceName": null,
			"eligibleUpgradeTypeList": ["Retail"],
			"mtnAddedToTheCart": false,
			"lineSharingIndicator": null,
			"buyoutRestrictedForEdge": false,
			"showTransferUpgrade": false,
			"transferUpgradeInProgress": false,
			"transferredFromMtn": null,
			"transferredToMtn": null,
			"alwaysEligibleForUpgrade": false,
			"sorDeviceType": null,
			"daccCode": null,
			"deviceProdId": "dev4800001",
			"estimatedTradeInValue": "0.00",
			"annualUpgradeWarning": false
		}, {
			"upgradeEligbile": true,
			"displayMtn": "757.201.2545",
			"mtn": "7572012545",
			"encryptedMTN": "I/GSE9zGQkVqaTXqOhDwqQ==",
			"upgradeMessage": null,
			"nickname": "TOM                   NICKS-2545",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/generic_phone?$device-thumb$",
			"inEligibleCode": null,
			"inEligibleDetails": null,
			"loanInfo": null,
			"annualUpgradeMessage": null,
			"deviceType": "Other Devices",
			"familyType": "Phone",
			"familyTypeRestricted": true,
			"contractTermMisMatch": false,
			"brand": null,
			"deviceId": "358571072768700",
			"twoYearContract": {
				"title": "Want to upgrade early?",
				"subTitle": "You can upgrade today by buying your device or wait until your contract ends in 128 days",
				"endDate": "07/15/2018",
				"daysPercentage": "82.46575342465754",
				"description": "Your device was purchased under a 2-year contract agreement. You can upgrade to a new phone today at the retail price or you can wait until your contract ends.",
				"contractTermText": null,
				"mtnSummarPageSubText": null,
				"daysRemainingText": null,
				"mtnSummaryPageSubTitle": null,
				"mtnSummaryPageTitle": null
			},
			"annualUpgrade": false,
			"displayDeviceName": "ECom Service SKU",
			"deviceName": null,
			"eligibleUpgradeTypeList": ["Retail"],
			"mtnAddedToTheCart": false,
			"lineSharingIndicator": null,
			"buyoutRestrictedForEdge": false,
			"showTransferUpgrade": false,
			"transferUpgradeInProgress": false,
			"transferredFromMtn": null,
			"transferredToMtn": null,
			"alwaysEligibleForUpgrade": false,
			"sorDeviceType": null,
			"daccCode": null,
			"deviceProdId": "dev4800001",
			"estimatedTradeInValue": "0.00",
			"annualUpgradeWarning": false
		}],
		"accountLevelInEligibleCode": null,
		"accountLevelInEligibleMessage": null,
		"selectedMTN": null,
		"aalRedirect": null,
		"accountLevelInEligibleDetails": null,
		"cartRedirect": "/od/cust/auth/cart/getCartDetails",
		"shopLandingRedirect": "/od/cust/auth/shoplanding/",
		"mtnMainTitle": "Would you like to upgrade or add a new device?",
		"catergoryCode": null,
		"unlimitedPlan": "N",
		"pastDueDetails": null,
		"submitAddALineUrl": "/od/cust/auth/submitaddaline",
		"transferGiverMTNs": ["2102433567", "2546400503", "9123466258"],
		"transferTakerMTNs": ["2544470061", "7572012545"],
		"customerType": null,
		"edgeEligible": true,
		"ajaxCallUrl": "/od/cust/auth/submitSummary",
		"ajaxCallSelectedMTN": "/od/cust/auth/mtnDetail/json?flow=EUP&t=",
		"redirectURL": null,
		"sharedPlan": true,
		"submitByodRedirectUrl": "/od/cust/auth/byod/bring-your-own-device",
		"aalAllowed": true,
		"aalboxEnable": true,
		"byodAllowed": true
	},
	"cpcRequired": false
};
