const invalidPromo_cartJSON = {
		"statusCode": "00",
		"output": {
			"orderId": "O18071257679",
			"redirectionURL": null,
			"isPOBODeviceInCart": true,
			"dueTodayPOBOHeader": null,
			"items": [{
				"deviceProdId": "dev7920215",
				"deviceManufactureName": "Motorola",
				"deviceProductDisplayName": "Moto Z<sup>2</sup> Play",
				"colorName": "Gray",
				"capacity": "32GB",
				"flow": "EUP",
				"mtn": "9494226836",
				"displayMtn": "949.422.6836",
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/MotoZ2Play_MRKT_LunarGrayDv?$device-med$&fmt=jpeg&wid=75&hei=150",
				"deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/MotoZ2Play_MRKT_LunarGrayDv?$device$&bgc=ffffff&wid=158&hei=300",
				"activationFee": "0.00",
				"waivedActivationFeePromo": false,
				"upgradeFee": "30.00",
				"waivedUpgradeFeePromo": false,
				"edgeDevice": true,
				"price": "17.00",
				"priceText": "Device payment",
				"priceSubTitle": "For 24 months.0% APR.Retail Price: $408.0",
				"edgeItemDownPaymentAmount": "0.00",
				"installmentBalance": "408.00",
				"deviceEdgeUpAmount": "0.00",
				"deviceEdgeBuyOutAmount": "0.00",
				"protectionOption": {
					"name": "Decline Equipment Protection",
					"price": "0.00",
					"featureType": "INSURANCE",
					"featureSkuId": "sku401064",
					"displayMsg": null
				},
				"commerceItemId": "ODC10848418016",
				"deviceSkuId": "sku2480355",
				"deviceSORId": "MOTXT171002",
				"lacPrice": "20.00",
				"lacText": "Smartphone line access",
				"inventoryStatus": "PreOrder",
				"inventoryAvailableDate": "Ships by Jul 06",
				"hasEcpdDiscount": false,
				"hasEcpdDiscountForDevicePayment": false,
				"devicePromotionList": [{
					"promotionalMessage": null,
					"promoDescription": "Free JBL SoundBoost Moto Mod w/purchase \r",
					"promoName": "Free JBL SoundBoost Moto Mod w/purchase \r",
					"promoAmount": "0",
					"promoContentText": null
				}],
				"bicOfferApplied": false,
				"bicContractPrice": 0.0,
				"bicDiscountedContractPrice": 0.0,
				"bicSavings": 0.0,
				"myOfferWaiveUpgradeFee": false,
				"bicMessage": null,
				"bicMessagetooltip": null,
				"editDeviceUrl": "/digital/device/deviceOptions/?deviceProdId=dev7920215&editDevice=true&commerceItemId=ODC10848418016",
				"fullRetailPrice": "408.00",
				"fromSavedCart": false,
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"dueMonthlyPrice": "37.00",
				"dueTodayPrice": "30.00",
				"monthlyPriceAfterDownPaymentBeforeDiscount": 17.0,
				"originalFullRetailPrice": 0.0,
				"hasReducedRetailPrice": false,
				"hasReducedDueMonthly": false,
				"originalDueMonthly": 0.0,
				"lineAccessPromotionText": null,
				"downPaymentPromotionText": null,
				"contractTerm": "99",
				"deviceType": "Smartphone",
				"activationFeeText": null,
				"promoOfferText": null,
				"promoApplied": false
			}],
			"accessories": [{
				"scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-usb-c-power-delivery-2-0-vehicle-charger-vpcpdtypec-m-iset?$gg-cart-th$",
				"name": "USB-C Quick Charge Car Charger",
				"quantity": 1,
				"commerceItemId": "ODC10848418021",
				"color": null,
				"size": null,
				"inventoryStatus": "InStock",
				"inventoryAvailableDate": null,
				"prodId": "acc6880019",
				"skuId": "sku2180047",
				"sorId": "VPCPDTYPEC-M",
				"hasEcpdDiscount": false,
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-usb-c-power-delivery-2-0-vehicle-charger-vpcpdtypec-m-iset?$acc-mini$",
				"hasBogoDiscount": false,
				"price": 39.99,
				"wasPrice": 39.99,
				"discounted": false,
				"discountPercentage": 0.0,
				"discountPrice": 39.99
			}, {
				"scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/jbl-soundboost-white-jblsdbouswht-iset?$gg-cart-th$",
				"name": "SoundBoost Moto Mod - White",
				"quantity": 1,
				"commerceItemId": "ODC10848418022",
				"color": "White",
				"size": null,
				"inventoryStatus": "InStock",
				"inventoryAvailableDate": null,
				"prodId": "acc6480001",
				"skuId": "sku2080002",
				"sorId": "JBLSDBOUSWHT",
				"hasEcpdDiscount": false,
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/jbl-soundboost-white-jblsdbouswht-iset?$acc-mini$",
				"hasBogoDiscount": false,
				"price": 79.99,
				"wasPrice": 79.99,
				"discounted": false,
				"discountPercentage": 0.0,
				"discountPrice": 79.99
			}],
			"taxDetails": {
				"taxPrice": "49.52",
				"cityStateString": "New York, NY",
				"stateTaxLabel": null,
				"zipCode": null
			},
			"totalDueToday": "199.50",
			"totalDueMonthly": "37.00",
			"employeeDiscount": 0,
			"pastDueBalance": "0.00",
			"emptyCartFlag": false,
			"edgeContractDeviceInCart": true,
			"totalEdgeUpAmount": "0.00",
			"totalEdgeUpBuyOutAmount": "0.00",
			"totalEdgeOrderDownPayment": "0.00",
			"tradeInCredit": null,
			"tradeInPromoDetails": null,
			"promotionList": [{
				"promoMsg": "Free JBL SoundBoost Moto Mod w/purchase \r",
				"promoAmount": "0"
			}],
			"cartMessages": {
				"cartReadyforCheckout": false,
				"message": "INVALID PROMO CODE",
				"code": null
			},
			"cartItemCount": 3,
			"mailInRebateTotal": 0,
			"mailInRebateDetails": null,
			"promoCodes": null,
			"promoCodeHeader": "Promo code? Lucky you.",
			"promoCodeLabel": "Promo code",
			"addAnotherPromoCodeText": "Add another promo code",
			"applyBtn": "Apply",
			"emptyCartMessage": "There are no items in your cart",
			"shopBtn": "Shop",
			"tradeInPromoEligible": true,
			"eligibleForSingleDeviceRibbon": false,
			"eligibleForMultiDeviceAllocation": false,
			"retrieveCartSuccessful": false,
			"standaloneAccessories": false,
			"dueTodayText": "Due today",
			"dueMonthlyText": "Due Monthly",
			"mainCartHeader": "Time to review your cart.",
			"mainCartSubTitle": "Enjoy free 2-day shipping.",
			"shopMoreBtnText": "Shop more",
			"checkoutBtn": "Check out",
			"editBtn": "Edit",
			"removeLinkText": "Remove",
			"mainCartFooterText": "Want to start over?",
			"mainCartFooterLinkText": "Emtpy your cart",
			"shopMoreLink": "/digital/shoplanding/",
			"activationFeeText": null,
			"waivedActivationText": "Waived Activation Fee",
			"upgradeFeeText": "Upgrade Fee",
			"waivedUpgradeFeeText": "Waived Upgrade Fee",
			"saveBtnLabel": "Save",
			"zipCodeHeader": "Please enter a new ZIP code",
			"tradeInCreditHeader": "Trade-in Credit for this device",
			"tradeInFooterLink": "Tell me more",
			"tradeInOfferDetailsHeader": "Offer Details",
			"tradeInOfferDetailsMsg": "long block of text",
			"tradeInConfirmationBtn": "Got it",
			"lonelyCartMessage": "Your cart is lonely.",
			"checkoutButtonURL": "/digital/checkout/initiateCheckout",
			"tradeInUrl": "/digital/tradein/prompt?gotoCart=true",
			"mainInRebateDetails": null,
			"deviceProtectionDetails": {
				"deviceProtectionDetailsHeader": "device protection details",
				"deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
				"deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
			},
			"preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
			"bicText": null,
			"hasSubmittedTradein": false,
			"cpcSucessful": false,
			"protectionURL": "/digital/protection",
			"itemsFromRetrievedCart": false,
			"totalActivationFee": "0.00",
			"bicOfferMessage": null,
			"cartMFCompatible": false,
			"cartValidationDetailsVo": {
				"cartReadyforCheckout": true,
				"cartIncompleteCode": null,
				"cartIncompleteMessage": null,
				"orderId": "O18071257679"
			},
			"cartEdited": false
		},
		"errorMap": {
			"04": "INVALID PROMO CODE"
		},
		"statusMessage": "Service completed Successfully."
	};
export default invalidPromo_cartJSON;
