const cartJSON ={
  "output": {
    "orderId": "s146606855",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "dueTodayPOBOHeader": null,
    "items": [
      {
        "deviceProdId": "dev5800066",
        "deviceManufactureName": "Samsung",
        "deviceProductDisplayName": "Galaxy S7",
        "colorName": "Black",
        "capacity": "32GB",
        "flow": "AAL",
        "mtn": "8454762127",
        "displayMtn": "845.476.2127",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Hero_Black?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Hero_Black?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "10.00",
        "waivedActivationFeePromo": true,
        "upgradeFee": "30.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "24.00",
        "priceText": "Device payment",
        "priceSubTitle": "For 24 months.0% APR.Retail Price: $576.0",
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "576.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Decline Equipment Protection",
          "price": "0.00",
          "featureType": "INSURANCE",
          "featureSkuId": "sku401064",
          "displayMsg": null
        },
        "commerceItemId": "SDC195712634",
        "deviceSkuId": "sku1900310",
        "deviceSORId": "SMG930VZKA",
        "lacPrice": "40.00",
        "lacText": "Smartphone line access",
        "inventoryStatus": "InStock",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": false,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/digital/device/deviceOptions/?deviceProdId=dev5800066&editDevice=true&commerceItemId=SDC195712634",
        "fullRetailPrice": "576.00",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "dueMonthlyPrice": "64.00",
        "dueTodayPrice": "30.00",
        "monthlyPriceAfterDownPaymentBeforeDiscount": 24,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "99",
        "deviceType": "Smartphone",
        activationFeeText: 'Activation Fee',
        "promoOfferText": null,
        "promoApplied": false,
        "transferOldNumberDetails": null
      },
      {
        "deviceProdId": "dev6360190",
        "deviceManufactureName": "Motorola",
        "deviceProductDisplayName": "Moto Z Droid",
        "colorName": "Black",
        "capacity": "32GB",
        "flow": "EUP",
        "mtn": "8457842002",
        "displayMtn": "845.784.2002",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Java_Black?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/Motorola_Java_Black?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "0.00",
        "waivedActivationFeePromo": true,
        "upgradeFee": "30.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "26.00",
        "priceText": "Device payment",
        "priceSubTitle": "For 24 months.0% APR.Retail Price: $624.0",
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "624.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "62.50",
        "protectionOption": {
          "name": "Total Mobile Protection",
          "price": "11.00",
          "featureType": "INSURANCE",
          "featureSkuId": "sku1230485",
          "displayMsg": null
        },
        "commerceItemId": "SDC195712651",
        "deviceSkuId": "sku2080195",
        "deviceSORId": "MOTXT1650",
        "lacPrice": "40.00",
        "lacText": "Smartphone line access",
        "inventoryStatus": "InStock",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": false,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/digital/device/deviceOptions/?deviceProdId=dev6360190&editDevice=true&commerceItemId=SDC195712651",
        "fullRetailPrice": "624.00",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "dueMonthlyPrice": "77.00",
        "dueTodayPrice": "92.50",
        "monthlyPriceAfterDownPaymentBeforeDiscount": 26,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "99",
        "deviceType": "Smartphone",
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "transferOldNumberDetails": null
      }
    ],
    "accessories": [],
    "taxDetails": {
      "taxPrice": "102.38",
      "cityStateString": "Newburgh, NY",
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "224.88",
    "totalDueMonthly": "141.00",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "62.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": null,
    "tradeInPromoDetails": null,
    "promotionList": [],
    "cartMessages": {
      "cartReadyforCheckout": false,
      "message": null,
      "code": null
    },
    "cartItemCount": 2,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": null,
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart",
    "mainCartSubTitle": "Enjoy free 2-day shipping.",
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/digital/mtnDetail",
    "activationFeeText": null,
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "checkoutButtonURL": "/digital/checkout/initiateCheckout",
    "tradeInUrl": "/digital/tradein/prompt?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "protectionURL": "/digital/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "10.00",
    "cartMFCompatible": false,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": null,
      "cartIncompleteMessage": null,
      "orderId": "s146606855"
    },
    "cartEdited": false
  },
  "ErrorMap": null,
  "statusMessage": "Service completed Successfully.",
  "statusCode": "00"
};

export default cartJSON;
