const cartJSON = {
  "statusCode": "00",
  "output": {
    "orderId": "SDC041be44c665c5afc80c77a9e6e78382a{d6}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "dueTodayPOBOHeader": null,
    "items": [
      {
        "deviceProdId": "dev3240008",
        "deviceManufactureName": "Apple",
        "deviceProductDisplayName": "iPhone&reg; 6",
        "colorName": "Gray",
        "capacity": "16GB",
        "flow": "NSO",
        "mtn": null,
        "displayMtn": null,
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone-6-spacegray?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone-6-spacegray?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": null,
        "originalPrice": null,
        "priceText": null,
        "priceSubTitle": null,
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": null,
        "commerceItemId": "SDC041be44c665c5afc80c77a9e6e78382a{d6}_device_1",
        "deviceSkuId": "sku1200118",
        "deviceSORId": "MG5W2LL/A",
        "lacPrice": "45.00",
        "lacText": "Smartphone line access",
        "inventoryStatus": null,
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": false,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0.0,
        "bicDiscountedContractPrice": 0.0,
        "bicSavings": 0.0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [],
        "simDetails": {
          "id": "sim001",
          "deviceLineItemId": "SDC041be44c665c5afc80c77a9e6e78382a{d6}_device_1",
          "type": "4006",
          "skuId": "sku401968",
          "productId": "sim760069",
          "sorId": "EMBD4GSIM-N",
          "displayName": "4G SIM Card",
          "category": "VirtualSim",
          "saccCode": "00659",
          "newSim": true,
          "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/SIM-card-illustration-m-2x-101116?"
        },
        "imeiId": "354407064090227",
        "transferredFromMtn": null,
        "originalActivationFee": "30.00",
        "priceForFullRetailPriceListID": "0.00",
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/pdp/dev3240008/?commerceItemId=SDC041be44c665c5afc80c77a9e6e78382a%7Bd6%7D_device_1&deviceProdId=dev3240008&catalogRefId=sku1200118&editDevice=true&flow=NSO",
        "fullRetailPrice": "0.00",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": true,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0.0,
        "originalFullRetailPrice": 0.0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0.0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "48",
        "deviceType": "SMARTPHONE",
        "activationFeeText": "One-time activation fee of $30.0 charged to your next monthly bill",
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "iPhone&reg; 6",
        "totalNumberShareExtension": 0,
        "originalUpgradeFee": "0.00",
        "totalSavings": null,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null,
        "discountedEdgeRetailPrice": null,
        "displayImeiId": "0227",
        "upgradeFeeWaived": false,
        "activationFeeWaived": false
      },
      {
        "deviceProdId": "dev3240009",
        "deviceManufactureName": "Apple",
        "deviceProductDisplayName": "iPhone&reg; 6 Plus",
        "colorName": "Gray",
        "capacity": "16GB",
        "flow": "NSO",
        "mtn": null,
        "displayMtn": null,
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone-6-plus-spacegray?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone-6-plus-spacegray?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": null,
        "originalPrice": null,
        "priceText": null,
        "priceSubTitle": null,
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": null,
        "commerceItemId": "SDC041be44c665c5afc80c77a9e6e78382a{d6}_device_2",
        "deviceSkuId": "sku1200130",
        "deviceSORId": "MGCK2LL/A",
        "lacPrice": "45.00",
        "lacText": "Smartphone line access",
        "inventoryStatus": null,
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": false,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0.0,
        "bicDiscountedContractPrice": 0.0,
        "bicSavings": 0.0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [],
        "simDetails": {
          "id": "sim001",
          "deviceLineItemId": "SDC041be44c665c5afc80c77a9e6e78382a{d6}_device_2",
          "type": "4006",
          "skuId": "sku401968",
          "productId": "sim760069",
          "sorId": "EMBD4GSIM-N",
          "displayName": "4G SIM Card",
          "category": "VirtualSim",
          "saccCode": "00659",
          "newSim": true,
          "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/SIM-card-illustration-m-2x-101116?"
        },
        "imeiId": "354387060829226",
        "transferredFromMtn": null,
        "originalActivationFee": "30.00",
        "priceForFullRetailPriceListID": "0.00",
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/pdp/dev3240009/?commerceItemId=SDC041be44c665c5afc80c77a9e6e78382a%7Bd6%7D_device_2&deviceProdId=dev3240009&catalogRefId=sku1200130&editDevice=true&flow=NSO",
        "fullRetailPrice": "0.00",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": true,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0.0,
        "originalFullRetailPrice": 0.0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0.0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "48",
        "deviceType": "SMARTPHONE",
        "activationFeeText": "One-time activation fee of $30.0 charged to your next monthly bill",
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "iPhone&reg; 6 Plus",
        "totalNumberShareExtension": 0,
        "originalUpgradeFee": "0.00",
        "totalSavings": null,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null,
        "discountedEdgeRetailPrice": null,
        "displayImeiId": "9226",
        "upgradeFeeWaived": false,
        "activationFeeWaived": false
      }
    ],
    "accessories": [],
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "0.00",
      "cityStateString": null,
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "0.00",
    "totalDueMonthly": "0.00",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": null,
    "tradeInPromoDetails": null,
    "promotionList": null,
    "cartMessages": {
      "cartReadyforCheckout": true,
      "message": "",
      "code": null
    },
    "cartItemCount": 2,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": null,
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping",
    "mainCartNextDayShippingMessage": null,
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/od/cust/auth/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "lonelyCartSubMessage": null,
    "checkoutButtonURL": "/od/cust/auth/checkout/initiateCheckout",
    "tradeInUrl": "/od/trade-in/auth?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/od/cust/auth/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "60.00",
    "itemOnJaxPlan": true,
    "anyLineFreeSPO": null,
    "paypalEnabled": true,
    "paypalApi": "/od/cust/auth/checkout/paypal/cmpilookup?triggerFrom=PAYMENT",
    "aalUrl": "/od/cust/auth/shop?flow=AAL",
    "eupUrl": "/od/cust/auth/shop?flow=EUP",
    "rawSubTotalDueToday": "0.00",
    "overallDueMonthly": "0.00",
    "additionalCharges": [],
    "accessoryGWURL": "/od/cust/auth/accessories/",
    "accessoryPDPURL": "/od/cust/auth/accessoryDetails/",
    "masterpassEnabled": false,
    "targetter": {
      "freeShippingText": "Free Shipping or In-Store Pickup",
      "freeShippingDesc": "Free shipping \n Free 2-day shipping when you order online M-F by 8PM EST, Sat by 2PM EST (excluding holidays), will deliver in two business days within the U.S. only (excluding AK & HI). 2-day orders placed after 2PM EST on Sat will deliver by Wednesday. Overnight shipping to destinations within the U.S. (excluding AK & HI) is generally available for orders placed M-F until 11PM EST, excluding holidays. Orders that contain a pre-order or backorder will ship via 2-day shipping on or prior to the committed date. Subject to credit authorization, verification and inventory availability.",
      "nextDayText": "Want it tomorrow? Order by 11PM ET w/Next Day Shipping. Pre-order devices excl'd",
      "nextDayDesc": "Depending on inventory availability for destinations within the US (excluding AK, HI) for orders placed M-F (excluding holidays). Next Day Shipping is not available for devices in pre-order status. Pre-order devices will ship as inventory becomes available",
      "contentText": "Keep your content.",
      "contentDesc": "Don't worry, we've got you covered. We'll make sure all of your pictures, contacts and content transfer from one phone to the other without issue.",
      "returnPolicyText": "14 day return policy",
      "returnPolicyDesc": "You may return or exchange wireless devices and accessories purchased from Verizon Wireless within 14 days of purchase. A restocking fee of $35 applies to any return or exchange of a wireless device (excluding Hawaii)."
    },
    "accessoryShopURL": "/od/accessories",
    "bicOfferMessage": null,
    "cartMFCompatible": true,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": null,
      "cartIncompleteMessage": null,
      "orderId": "SDC041be44c665c5afc80c77a9e6e78382a{d6}"
    },
    "cartEdited": false,
    "iconicFlow": false,
    "plans": {
      "planOnlyDueMonthly": "270.00",
      "dueMonthly": "270.00",
      "dueToday": "0.00",
      "items": [
        {
          "planType": "Go Unlimited",
          "planSorId": "99230",
          "planProdId": "plan2880001",
          "planSkuId": "sku2580028",
          "planLetter": null,
          "planDescription": "",
          "planDisplayName": "Go Unlimited",
          "planChangeURL": null,
          "planImageURL": null,
          "accountAccess": {
            "name": "Go Unlimited",
            "price": "270.00",
            "discountPrice": 0.0,
            "promoMessage": null,
            "hasEcpdDiscount": false,
            "planAmount": "270.00",
            "originalPlanAmount": "0.00"
          }
        }
      ],
      "newDevices": [
        {
          "name": "iPhone&reg; 6",
          "price": "45.00",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": null,
          "listPrice": 45.0,
          "deviceLineItemId": "SDC041be44c665c5afc80c77a9e6e78382a{d6}_device_1",
          "discountPriceVal": "0.00"
        },
        {
          "name": "iPhone&reg; 6 Plus",
          "price": "45.00",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": null,
          "listPrice": 45.0,
          "deviceLineItemId": "SDC041be44c665c5afc80c77a9e6e78382a{d6}_device_2",
          "discountPriceVal": "0.00"
        }
      ],
      "upgradeDevices": [],
      "existingDevices": [
        {
          "name": "Apple&reg; iPhone&reg; 8 Plus 64GB in Gold",
          "price": "45.00",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "5037841899",
          "listPrice": 45.0,
          "deviceLineItemId": null,
          "discountPriceVal": "0.00"
        },
        {
          "name": "Apple&reg; iPhone&reg; 8 Plus 64GB in Space Gray",
          "price": "45.00",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "5413061092",
          "listPrice": 45.0,
          "deviceLineItemId": null,
          "discountPriceVal": "0.00"
        },
        {
          "name": "iPhone 6S 16GB Rose Gold",
          "price": "45.00",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "5417288337",
          "listPrice": 45.0,
          "deviceLineItemId": null,
          "discountPriceVal": "0.00"
        },
        {
          "name": "Apple&reg; iPhone&reg; 6s 64GB in Gold",
          "price": "45.00",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "5418487619",
          "listPrice": 45.0,
          "deviceLineItemId": null,
          "discountPriceVal": "0.00"
        }
      ],
      "dueMonthlyPlanWithLAC": "540.00",
      "discountedDueMonthlyPlanWithLAC": "0.00"
    },
    "removePromoCodeURL": "/od/cust/auth/cart/removePromoCode",
    "applyPromoCodeURL": "/od/cust/auth/cart/applyPromoCode",
    "clearCartURL": "/od/cust/auth/cart/clearCart",
    "addOrUpdateDeviceURL": "/od/cust/auth/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/od/cust/auth/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/od/cust/auth/cart/changezipcode/",
    "addOrUpdateFeatureURL": "/od/cust/auth/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/od/cust/auth/checkout/initiateCheckout",
    "accountMember": false,
    "tmpMdOpted": false,
    "tmpMd": null,
    "frontEndPersonalization": null,
    "splitShipment": false,
    "authenticated": true
  },
  "errorMap": null,
  "statusMessage": ""
};

export default cartJSON;
