exports.cartJSON = {
  "statusCode": "00",
  "output": {
    "orderId": "SDC970cb4f1e15858e6b799ad26db1b2205",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "dueTodayPOBOHeader": null,
    "isFreeShipInStore": false,
    "isPreorderPurchase": false,
    "isKeepContent": false,
    "isReturnPolicy": false,
    "isTransferContent": false,
    "items": [
      {
        "deviceProdId": "dev8720046",
        "deviceManufactureName": "Apple",
        "deviceProductDisplayName": "iPhone&reg; 8",
        "colorName": "Gold",
        "capacity": "256GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": "571-340-XXXX",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iPhone8-Gld?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/iPhone8-Gld?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "27.08",
        "originalPrice": "35.41",
        "priceText": "Device payment",
        "priceSubTitle": "1st installment will appear on your bill.",
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Total Mobile Protection",
          "price": "13.00",
          "originalPrice": "13.00",
          "featureType": "INS",
          "featureSkuId": "sku2880128",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapOpted": false
        },
        "commerceItemId": "SDC970cb4f1e15858e6b799ad26db1b2205_device_1",
        "deviceSkuId": "sku2680237",
        "deviceSORId": "MQ802LL/A",
        "lacPrice": "55.00",
        "lacText": "Smartphone line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": false,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [
          
        ],
        "bicOfferApplied": false,
        "bicContractPrice": 0.0,
        "bicDiscountedContractPrice": 0.0,
        "bicSavings": 0.0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [
          
        ],
        "simDetails": null,
        "imeiId": null,
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/pdp/dev8720046/?commerceItemId=SDC970cb4f1e15858e6b799ad26db1b2205_device_1&deviceProdId=dev8720046&catalogRefId=sku2680237&editDevice=true&flow=AAL",
        "fullRetailPrice": "849.99",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": true,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0.0,
        "originalFullRetailPrice": 0.0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0.0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "99",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "iPhone&reg; 8",
        "totalNumberShareExtension": 0,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null,
        "discountedEdgeRetailPrice": "649.99",
        "displayImeiId": null
      }
    ],
    "accessories": [
      
    ],
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "39.00",
      "cityStateString": "Great Falls, VA",
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "39.00",
    "totalDueMonthly": "40.08",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": "55.00",
    "tradeInPromoDetails": {
      "tradeInDeviceDppMsg": "We'll send you a prepaid box to mail in your trade-in. This is only an estimate until we receive and appraise your device.",
      "warningMessage": null,
      "tradeInDeviceHeaderMsg": "You'll see an estimated $55.00 credit within 1-2 bill cycles.",
      "tradeInCredit": "55.00",
      "tradeInDevices": [
        {
          "activeDevice": null,
          "tradeInCredit": "55.00",
          "tradeInDeviceFooter": null,
          "offerDetailsMsg": null,
          "tradeInDeviceHeaderMsg": null,
          "tradeInCreditMsg": "Trade-in credit: $55.00",
          "bicApplied": null,
          "color": "Gray",
          "dataWipeText": null,
          "deviceBrand": null,
          "deviceId": "ID: 358677059939050",
          "discAmt": null,
          "disconnectedDate": null,
          "displayName": "iPad Mini 2",
          "dppCredit": "0.0",
          "dppAppliedCommerceItemId": null,
          "dppAppliedMdn": null,
          "errorMessage": null,
          "modalOsName": null,
          "modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/apple_ipadmini_retina_spacegray?$device-lg$",
          "modelName": null,
          "mtn": null,
          "nickName": null,
          "originalAppraisalPrice": "55.00",
          "price": null,
          "promoCodeError": null,
          "promoCreditType": null,
          "promoQualifyMessage": null,
          "promoValue": null,
          "shortDisplayName": null,
          "size": "16GB",
          "success": true
        }
      ]
    },
    "promotionList": [
      {
        "promoMsg": "UAT 200 Off Smartphone - Previous Device Return Required",
        "promoAmount": "200.00",
        "barcode": null,
        "skuId": "MQ802LL/A"
      },{
        "promoMsg": "UAT 400 Off Smartphone - Previous Device Return Required",
        "promoAmount": "400.00",
        "barcode": null,
        "skuId": "NP802LL/A"
      }
    ],
    "cartMessages": {
      "cartReadyforCheckout": true,
      "code": null,
      "message": ""
    },
    "cartItemCount": 1,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": [
      null
    ],
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping",
    "mainCartNextDayShippingMessage": null,
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/od/cust/auth/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "checkoutButtonURL": "/od/cust/auth/checkout/initiateCheckout",
    "tradeInUrl": "/od/trade-in/auth?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": true,
    "cpcSucessfulNotification": true,
    "protectionURL": "/od/cust/auth/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "30.00",
    "itemOnJaxPlan": true,
    "anyLineFreeSPO": null,
    "bicOfferMessage": null,
    "cartMFCompatible": true,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": null,
      "cartIncompleteMessage": null,
      "orderId": "SDC970cb4f1e15858e6b799ad26db1b2205"
    },
    "cartEdited": false,
    "iconicFlow": false,
    "plans": {
      "planOnlyDueMonthly": "315.00",
      "dueMonthly": "315.00",
      "dueToday": "0.00",
      "items": [
        {
          "planType": "Beyond Unlimited",
          "planSorId": "99231",
          "planProdId": "plan2880001",
          "planSkuId": "sku2580029",
          "planLetter": "U",
          "planDescription": "<span>Shared unlimited talk, </span><span>text &amp;  unlimited data </span>",
          "planDisplayName": "Beyond Unlimited",
          "planChangeURL": "/od/cust/auth/compatiblePlans?editPlan=true&planSorId=99231&flow=null&planCommId=SDC970cb4f1e15858e6b799ad26db1b2205_plan_1",
          "planImageURL": "//ss7.vzw.com/is/image/VerizonWireless/BeyondUnlimited_Logo_Carousel",
          "accountAccess": {
            "name": "Beyond Unlimited",
            "price": "315.00",
            "discountPrice": 0.0,
            "promoMessage": null,
            "hasEcpdDiscount": false,
            "planAmount": "315.00",
            "originalPlanAmount": "0.00"
          }
        }
      ],
      "newDevices": [
        {
          "name": "iPhone&reg; 8",
          "price": "55.0",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": null
        }
      ],
      "upgradeDevices": [
        
      ],
      "existingDevices": [
        {
          "name": "Apple&reg; iPad&reg; mini 2 16GB in Space Gray",
          "price": "20.0",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "7032176714"
        },
        {
          "name": "Samsung Galaxy S&reg;6 32GB in Black Sapphire",
          "price": "55.0",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "7033573897"
        },
        {
          "name": "iPad&reg; with Retina Display 16GB in Black",
          "price": "20.0",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "7037859850"
        },
        {
          "name": "Apple&reg; iPhone&reg; 8 Plus 64GB in Silver",
          "price": "55.0",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "7039195597"
        },
        {
          "name": "Apple&reg; iPhone&reg; 6 Plus 16GB in Gold",
          "price": "55.0",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "7039271166"
        },
        {
          "name": "Apple&reg; iPhone&reg; 6s 64GB in Gold",
          "price": "55.0",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "7039444346"
        }
      ],
      "dueMonthlyPlanWithLAC": "315.00",
      "discountedDueMonthlyPlanWithLAC": "0.00"
    },
    "removePromoCodeURL": "/od/cust/auth/cart/removePromoCode",
    "applyPromoCodeURL": "/od/cust/auth/cart/applyPromoCode",
    "clearCartURL": "/od/cust/auth/cart/clearCart",
    "addOrUpdateDeviceURL": "/od/cust/auth/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/od/cust/auth/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/od/cust/auth/cart/changezipcode/",
    "addOrUpdateFeatureURL": "/od/cust/auth/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/od/cust/auth/checkout/initiateCheckout",
    "accountMember": false,
    "tmpMdOpted": false,
    "tmpMd": null,
    "splitShipment": false,
    "authenticated": true
  },
  "errorMap": null,
  "statusMessage": ""
};

