const cartJSON ={
	"statusCode": "00",
	"output": {
		"orderId": "s534391548",
		"redirectionURL": null,
		"isPOBODeviceInCart": false,
		"dueTodayPOBOHeader": null,
		"items": [{
			"deviceProdId": "dev7480001",
			"deviceManufactureName": "Samsung",
			"deviceProductDisplayName": "Galaxy S8",
			"colorName": "Orchid Gray",
			"capacity": "64GB",
			"flow": "AAL",
			"mtn": null,
			"displayMtn": "808-354-XXXX",
			"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Orchid_Gray?$device-med$&fmt=jpeg&wid=75&hei=150",
			"deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S8_Orchid_Gray?$device$&bgc=ffffff&wid=158&hei=300",
			"activationFee": "0.00",
			"waivedActivationFeePromo": false,
			"upgradeFee": "0.00",
			"waivedUpgradeFeePromo": false,
			"edgeDevice": true,
			"price": "31.50",
			"priceText": "Device payment",
			"priceSubTitle": "For 24 months.0% APR.Retail Price: $756.0",
			"edgeItemDownPaymentAmount": "0.00",
			"installmentBalance": "756.00",
			"deviceEdgeUpAmount": "0.00",
			"deviceEdgeBuyOutAmount": "0.00",
			"protectionOption": {
				"name": "Total Mobile Protection",
				"price": "11.00",
				"featureType": "INSURANCE",
				"featureSkuId": "sku1230485",
				"displayMsg": null
			},
			"commerceItemId": "SDC211976533",
			"deviceSkuId": "sku2360003",
			"deviceSORId": "SMG950UZVV",
			"lacPrice": "20.00",
			"lacText": "Smartphone line access",
			"inventoryStatus": "InStock",
			"inventoryAvailableDate": null,
			"hasEcpdDiscount": false,
			"hasEcpdDiscountForDevicePayment": false,
			"devicePromotionList": [{
				"promotionalMessage": null,
				"promoDescription": "Congratulations! Don't forget to redeem your offers.",
				"promoName": "Congratulations! Don't forget to redeem your offers.",
				"promoAmount": "0",
				"promoContentText": "Here's how it works:Buy Galaxy S8 with Trade-in and get a $50 gift card.1 Buy Galaxy S8 with monthly device payments.2 Choose Verizon unlimited as your plan.3 Send us your old device in the mail as a trade-in after you finish your order."
			}],
			"bicOfferApplied": false,
			"bicContractPrice": 0.0,
			"bicDiscountedContractPrice": 0.0,
			"bicSavings": 0.0,
			"myOfferWaiveUpgradeFee": false,
			"bicMessage": null,
			"bicMessagetooltip": null,
			"editDeviceUrl": "/digital/device/deviceOptions/?deviceProdId=dev7480001&editDevice=true&commerceItemId=SDC211976533",
			"fullRetailPrice": "756.00",
			"fromSavedCart": false,
			"numberShareDevice": false,
			"numberSharedMtn": null,
			"dueMonthlyPrice": "62.50",
			"dueTodayPrice": "0.00",
			"monthlyPriceAfterDownPaymentBeforeDiscount": 31.5,
			"originalFullRetailPrice": 0.0,
			"hasReducedRetailPrice": false,
			"hasReducedDueMonthly": false,
			"originalDueMonthly": 0.0,
			"lineAccessPromotionText": null,
			"downPaymentPromotionText": null,
			"contractTerm": "99",
			"deviceType": "Smartphone",
			"activationFeeText": "one-time activation fee of $30.00 charged to your next monthly bill.",
			"promoOfferText": "Here's how it works:Buy Galaxy S8 with Trade-in and get a $50 gift card.1 Buy Galaxy S8 with monthly device payments.2 Choose Verizon unlimited as your plan.3 Send us your old device in the mail as a trade-in after you finish your order.",
			"promoApplied": true,
			"transferOldNumberDetails": null
		}],
		"accessories": [],
		"taxDetails": {
			"taxPrice": "35.62",
			"cityStateString": "Honolulu, HI",
			"stateTaxLabel": null,
			"zipCode": null
		},
		"totalDueToday": "35.62",
		"totalDueMonthly": "62.50",
		"employeeDiscount": 0,
		"pastDueBalance": "460.17",
		"emptyCartFlag": false,
		"edgeContractDeviceInCart": true,
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"totalEdgeOrderDownPayment": "0.00",
		"tradeInCredit": null,
		"tradeInPromoDetails": null,
		"promotionList": [{
			"promoMsg": "Congratulations! Don't forget to redeem your offers.",
			"promoAmount": "0"
		}],
		"cartMessages": {
			"cartReadyforCheckout": false,
			"message": null,
			"code": null
		},
		"cartItemCount": 1,
		"mailInRebateTotal": 0,
		"mailInRebateDetails": null,
		"promoCodes": null,
		"promoCodeHeader": "Promo code? Lucky you.",
		"promoCodeLabel": "Promo code",
		"addAnotherPromoCodeText": "Add another promo code",
		"applyBtn": "Apply",
		"emptyCartMessage": "There are no items in your cart",
		"shopBtn": "Shop",
		"tradeInPromoEligible": true,
		"eligibleForSingleDeviceRibbon": false,
		"eligibleForMultiDeviceAllocation": false,
		"retrieveCartSuccessful": false,
		"standaloneAccessories": false,
		"dueTodayText": "Due today",
		"dueMonthlyText": "Due Monthly",
		"mainCartHeader": "Time to review your cart.",
		"mainCartSubTitle": "Enjoy free 2-day shipping",
		"shopMoreBtnText": "Shop more",
		"checkoutBtn": "Check out",
		"editBtn": "Edit",
		"removeLinkText": "Remove",
		"mainCartFooterText": "Want to start over?",
		"mainCartFooterLinkText": "Emtpy your cart",
		"shopMoreLink": "/digital/shoplanding/",
		"activationFeeText": null,
		"waivedActivationText": "Waived Activation Fee",
		"upgradeFeeText": "Upgrade Fee",
		"waivedUpgradeFeeText": "Waived Upgrade Fee",
		"saveBtnLabel": "Save",
		"zipCodeHeader": "Please enter a new ZIP code",
		"tradeInCreditHeader": "Trade-in Credit for this device",
		"tradeInFooterLink": "Tell me more",
		"tradeInOfferDetailsHeader": "Offer Details",
		"tradeInOfferDetailsMsg": "long block of text",
		"tradeInConfirmationBtn": "Got it",
		"lonelyCartMessage": "Your cart is lonely.",
		"checkoutButtonURL": "/digital/checkout/initiateCheckout",
		"tradeInUrl": "/digital/tradein/prompt?gotoCart=true",
		"mainInRebateDetails": null,
		"deviceProtectionDetails": {
			"deviceProtectionDetailsHeader": "device protection details",
			"deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
			"deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
		},
		"preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
		"bicText": null,
		"hasSubmittedTradein": false,
		"cpcSucessful": false,
		"protectionURL": "/digital/protection",
		"itemsFromRetrievedCart": false,
		"totalActivationFee": "30.00",
		"bicOfferMessage": null,
		"cartMFCompatible": false,
		"cartValidationDetailsVo": {
			"cartReadyforCheckout": true,
			"cartIncompleteCode": null,
			"cartIncompleteMessage": null,
			"orderId": "s534391548"
		},
		"cartEdited": false
	},
	"errorMap": null,
	"statusMessage": "Service completed Successfully."
};
export default cartJSON;