const cartJSON = {
  "statusCode": "00",
  "output": {
    "orderId": "T137a1fbc35a7933e277be52fcec69802{ss3}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "accGuestCheckoutEnabled": null,
    "dueTodayPOBOHeader": null,
    "items": [{
      "deviceProdId": "dev9640080",
      "deviceManufactureName": "Samsung",
      "deviceProductDisplayName": "Galaxy S9",
      "colorName": "Coral Blue",
      "capacity": "64GB",
      "flow": "AAL",
      "mtn": null,
      "displayMtn": null,
      "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/SAMSUNG_Galaxy_S9_Blue?$device-med$&fmt=jpeg&wid=75&hei=150",
      "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/SAMSUNG_Galaxy_S9_Blue?$device$&bgc=ffffff&wid=158&hei=300",
      "activationFee": "0.00",
      "waivedActivationFeePromo": false,
      "upgradeFee": "0.00",
      "waivedUpgradeFeePromo": false,
      "edgeDevice": true,
      "price": "33.33",
      "originalPrice": "33.33",
      "priceText": "Device payment",
      "priceSubTitle": "1st installment will appear on your bill.",
      "edgeItemDownPaymentAmount": "0.00",
      "installmentBalance": "0.00",
      "deviceEdgeUpAmount": "0.00",
      "deviceEdgeBuyOutAmount": "0.00",
      "protectionOption": {
        "name": "Decline Equipment Protection",
        "price": "0.00",
        "originalPrice": "0.00",
        "featureType": "INS",
        "featureSkuId": "sku401064",
        "hideEditProtection": false,
        "displayMsg": null,
        "tapOpted": false
      },
      "commerceItemId": "T137a1fbc35a7933e277be52fcec69802{ss3}_device_2",
      "deviceSkuId": "sku2930295",
      "deviceSORId": "SMG960UZBV",
      "lacPrice": "10.00",
      "lacText": "Smartphone line access",
      "inventoryStatus": "1000",
      "inventoryAvailableDate": null,
      "hasEcpdDiscount": false,
      "hasEcpdDiscountForDevicePayment": false,
      "devicePromotionList": [{
        "promotionalMessage": null,
        "promoDescription": "GET $200.00 OFF GALAXY S9 WITH DPP CONTRACT.  BIC YES.  DIRECT AND INDIRECT AGENT CHANNELS.",
        "promoName": "GET 200 00 OFF GALAXY S9 DPP",
        "promoAmount": "200.00",
        "priceSubTitle": null,
        "barCodeId": null,
        "itemCode": "sku2930295",
        "itemType": null,
        "sedOffer": false,
        "promoContentText": null
      }],
      "bicOfferApplied": true,
      "bicContractPrice": "33.33",
      "bicDiscountedContractPrice": "24.99",
      "bicSavings": "8.34",
      "myOfferWaiveUpgradeFee": false,
      "shipCommitInd": null,
      "promoLACMessage": null,
      "additionalFeatures": [],
      "simDetails": null,
      "imeiId": null,
      "transferredFromMtn": null,
      "originalActivationFee": "30.00",
      "priceForFullRetailPriceListID": "799.99",
      "bicMessage": null,
      "bicMessagetooltip": null,
      "editDeviceUrl": "/od/pdp/dev9640080/?commerceItemId=T137a1fbc35a7933e277be52fcec69802%7Bss3%7D_device_2&deviceProdId=dev9640080&catalogRefId=sku2930295&editDevice=true&flow=AAL",
      "fullRetailPrice": "799.99",
      "fromSavedCart": false,
      "numberShareDevice": false,
      "numberSharedMtn": null,
      "itemOnJaxPlan": false,
      "humCarDetails": null,
      "poboAvailableDate": null,
      "monthlyPriceAfterDownPaymentBeforeDiscount": 0.0,
      "originalFullRetailPrice": 0.0,
      "hasReducedRetailPrice": false,
      "hasReducedDueMonthly": false,
      "originalDueMonthly": 0.0,
      "lineAccessPromotionText": null,
      "downPaymentPromotionText": null,
      "contractTerm": "99",
      "deviceType": "SMARTPHONE",
      "activationFeeText": "Waived Activation Fee",
      "promoOfferText": null,
      "promoApplied": false,
      "portIn": false,
      "deviceNickName": "Galaxy S9",
      "totalNumberShareExtension": 0,
      "originalUpgradeFee": "0.00",
      "totalSavings": "200.00",
      "sbdOffer": {
        "sbdHeaderMsg": "Congratulations! You are getting this device for only $24.99/mo. instead of $33.33/mo for 24 mos.",
        "sbdPromoMsg": "New line of service & $599.99 device payment purchase required. Less $200.00 bill credit applied to account over 24 mos; begins w/in 1-2 cycles & ends when balance is paid; 0% APR. Upgrade ineligible. Max 5 lines.",
        "sbdDiscountAmount": "200.00",
        "sbdItemMonthlyAmount": "24.99",
        "itemRetailPrice": "799.99",
        "itemMonthlyPrice": "33.33",
        "itemStrikeThroughPrice": "33.33",
        "noOfBicOccurences": 24,
        "sbdHeaderMsgHTML": "<span class='color_blue bold block'>Congratulations! </span> You are getting this device for only $24.99/mo. instead of $33.33/mo for 24 mos."
      },
      "hostCommerceItemId": null,
      "trunkMtn": null,
      "discountedEdgeRetailPrice": "599.99",
      "displayImeiId": null,
      "activationFeeWaived": true,
      "upgradeFeeWaived": false
    }],
    "accessories": [],
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "53.00",
      "cityStateString": "Emerson, NJ",
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "53.00",
    "totalDueMonthly": "34.99",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": "57.00",
    "tradeInPromoDetails": {
      "tradeInDeviceDppMsg": "We'll send you a prepaid box to mail in your trade-in. This is only an estimate until we receive and appraise your device.",
      "warningMessage": null,
      "tradeInDeviceHeaderMsg": "You'll see an estimated $57.00 credit within 1-2 bill cycles.",
      "tradeInCredit": "57.00",
      "tradeInDevices": [{
        "activeDevice": null,
        "tradeInCredit": "57.00",
        "tradeInDeviceFooter": null,
        "offerDetailsMsg": null,
        "tradeInDeviceHeaderMsg": null,
        "tradeInCreditMsg": "Trade-in credit: $57.00",
        "bicApplied": false,
        "color": "Black",
        "dataWipeText": null,
        "deviceBrand": "Samsung",
        "deviceId": "ID: 990006980919509",
        "discAmt": null,
        "disconnectedDate": null,
        "displayName": "Galaxy S 6 Edge",
        "dppCredit": "0.0",
        "dppAppliedCommerceItemId": null,
        "dppAppliedMdn": null,
        "errorMessage": null,
        "modalOsName": null,
        "modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S6_Edge_Black?$device-lg$",
        "modelName": null,
        "mtn": null,
        "nickName": null,
        "originalAppraisalPrice": "47.00",
        "price": null,
        "promoCodeError": null,
        "promoCreditType": null,
        "promoQualifyMessage": null,
        "promoValue": null,
        "shortDisplayName": null,
        "size": "32GB",
        "success": true,
        "regularPromoApplied": false,
        "existingAppraisedReferenceId": "01226125851438",
        "appraiseTradeInDeviceWithOutDeviceId": true,
        "flow": "AAL"
      }],
      "orginaltradeInCredit": "57.00"
    },
    "promotionList": [],
    "cartMessages": {
      "cartReadyforCheckout": true,
      "message": "",
      "code": null
    },
    "cartItemCount": 1,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": [],
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping",
    "mainCartNextDayShippingMessage": "Want it tomorrow? Order by 11pm with next day shipping",
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/od/cust/auth/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "lonelyCartSubMessage": null,
    "checkoutButtonURL": "/od/cust/auth/checkout/initiateCheckout",
    "tradeInUrl": "/od/trade-in/auth?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": "You'll see a $8.34/mo promo credit within 2-3 billing cycles.",
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/od/cust/auth/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "0.00",
    "itemOnJaxPlan": false,
    "anyLineFreeSPO": null,
    "paypalEnabled": false,
    "paypalApi": "/od/cust/auth/checkout/paypal/cmpilookup?triggerFrom=PAYMENT",
    "aalUrl": "/od/cust/auth/shop?flow=AAL",
    "eupUrl": "/od/cust/auth/shop?flow=EUP",
    "rawSubTotalDueToday": "0.00",
    "overallDueMonthly": "34.99",
    "additionalCharges": [{
      "taxPrice": "53.00",
      "cityStateString": null,
      "stateTaxLabel": "NJ State Sales Tax",
      "zipCode": null
    }],
    "accessoryGWURL": "/od/cust/auth/accessories/",
    "accessoryPDPURL": "/od/cust/auth/accessoryDetails/",
    "removeTradeInURL": "/od/trade-in/removeTradeIn",
    "masterpassEnabled": false,
    "targetter": {
      "freeShippingText": "Free Shipping or In-Store Pickup",
      "freeShippingDesc": "Free shipping \n Free 2-day shipping when you order online M-F by 8PM EST, Sat by 2PM EST (excluding holidays), will deliver in two business days within the U.S. only (excluding AK & HI). 2-day orders placed after 2PM EST on Sat will deliver by Wednesday. Overnight shipping to destinations within the U.S. (excluding AK & HI) is generally available for orders placed M-F until 11PM EST, excluding holidays. Orders that contain a pre-order or backorder will ship via 2-day shipping on or prior to the committed date. Subject to credit authorization, verification and inventory availability.",
      "nextDayText": "Want it tomorrow? Order by 11PM ET w/Next Day Shipping. Pre-order devices excl'd",
      "nextDayDesc": "Depending on inventory availability for destinations within the US (excluding AK, HI) for orders placed M-F (excluding holidays). Next Day Shipping is not available for devices in pre-order status. Pre-order devices will ship as inventory becomes available",
      "contentText": "Keep your content.",
      "contentDesc": "Don't worry, we've got you covered. We'll make sure all of your pictures, contacts and content transfer from one phone to the other without issue.",
      "returnPolicyText": "14 day return policy",
      "returnPolicyDesc": "You may return or exchange wireless devices and accessories purchased from Verizon Wireless within 14 days of purchase. A restocking fee of $35 applies to any return or exchange of a wireless device (excluding Hawaii)."
    },
    "overallDiscountedAmount": "0.00",
    "ecpdDueTodayDiscountedAmount": "0.00",
    "ecpdDueMonthlySavings": "0.00",
    "devicesURL": "/od/devices/",
    "autoPayApplied": false,
    "cartURL": "/od/cust/auth/cart/getCartDetails?format=json",
    "byodUrl": "/od/cust/auth/shop?flow=NSO",
    "masterpassConfigInfo": {
      "checkoutId": "086d17da498d4a4685096e96bdb1d567",
      "allowedCardTypes": ["master", "amex", "diners", "discover", "jcb",
        "maestro", "visa"
      ],
      "shippingLocationProfile": "US",
      "amount": "53.0",
      "cartId": "T137a1fbc35a7933e277be52fcec69802{ss3}",
      "currency": "USD",
      "suppress3Ds": false,
      "callbackUrl": "https://www.verizonwireless.com/od/cust/auth/checkout/masterpass/paymentData"
    },
    "accessoryShopURL": "/accessories",
    "bicOfferMessage": "You'll see a $24.99/mo credit within 1-2 billing cycles.",
    "cartMFCompatible": true,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": null,
      "cartIncompleteMessage": null,
      "orderId": "T137a1fbc35a7933e277be52fcec69802{ss3}"
    },
    "cartEdited": false,
    "iconicFlow": false,
    "plans": {
      "planOnlyDueMonthly": "110.00",
      "dueMonthly": "110.00",
      "dueToday": "0.00",
      "items": [{
        "planType": "The new Verizon Plan Unlimited",
        "planSorId": "98127",
        "planProdId": "plan2880001",
        "planSkuId": "sku2310052",
        "planLetter": null,
        "planDescription": "",
        "planDisplayName": "The new Verizon Plan Unlimited",
        "planChangeURL": null,
        "planImageURL": null,
        "accountAccess": {
          "name": "The new Verizon Plan Unlimited",
          "price": "110.00",
          "discountPrice": 55.0,
          "promoMessage": null,
          "hasEcpdDiscount": true,
          "planAmount": "110.00",
          "originalPlanAmount": "110.00"
        }
      }],
      "newDevices": null,
      "upgradeDevices": null,
      "existingDevices": null,
      "dueMonthlyPlanWithLAC": null,
      "discountedDueMonthlyPlanWithLAC": null,
      "existingDevicesLAC": null,
      "discountedExistingDevicesLAC": null
    },
    "removePromoCodeURL": "/od/cust/auth/cart/removePromoCode",
    "applyPromoCodeURL": "/od/cust/auth/cart/applyPromoCode",
    "clearCartURL": "/od/cust/auth/cart/clearCart",
    "addOrUpdateDeviceURL": "/od/cust/auth/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/od/cust/auth/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/od/cust/auth/cart/changezipcode/",
    "addOrUpdateFeatureURL": "/od/cust/auth/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/od/cust/auth/checkout/initiateCheckout",
    "guestCheckoutSignInURL": null,
    "accountMember": false,
    "tmpMdOpted": false,
    "tmpMd": null,
    "frontEndPersonalization": null,
    "allowAAL": true,
    "allowEUP": true,
    "splitShipment": false,
    "authenticated": true
  },
  "errorMap": null,
  "statusMessage": ""
};

export default cartJSON;
