export const ASYNC_FETCH = 'ASYNC_FETCH';
export const ASYNC_FETCH_SUCCESS = 'ASYNC_FETCH_SUCCESS';
export const ASYNC_FETCH_FAILURE = 'ASYNC_FETCH_FAILURE';
export const ASYNC_FETCH_INVALIDATE = 'ASYNC_FETCH_INVALIDATE';
export const API_SUCCESS_CODE = '00';
export const API_FAILURE_CODE = '01';

export const RESET_CART = 'cart/RESET_CART';
export const EMPTY_CART = 'cart/EMPTY_CART';
export const EMPTY_CART_SUCCESS = 'cart/EMPTY_CART_SUCCESS';
export const EMPTY_CART_FAILURE = 'cart/EMPTY_CART_FAILURE';

export const ADD_PROMOCODE = 'cart/UPDATE_PROMOCODE';
export const REMOVE_PROMOCODE = 'cart/REMOVE_PROMOCODE';
export const UPDATE_ZIPCODE = 'cart/UPDATE_ZIPCODE';
export const REMOVE_DEVICE = 'cart/REMOVE_DEVICE';
export const SELECT_PROTECTION_FEATURE = 'SELECT_PROTECTION_FEATURE';
export const CLEAR_CART_MESSAGE = 'cart/CLEAR_CART_MESSAGE';
export const ACCOUNT_EMAIL_SENT = 'cart/ACCOUNT_EMAIL_SENT';
export const API_EMAIL_CART = '/od/cust/auth/cart/saveAccountMemberCart';
export const CLEAR_MEMBER_CART = '/od/cust/campaign/cart/clearCart';
export const INITIATE_MEMBER_CHECKOUT = '/od/cust/campaign/checkout/initiateCheckout';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

/*
Recommended accessories
 */
export const RECOMM_ACC_FETCH = 'RECOMM_ACC_FETCH';
export const RECOMM_ACC_FETCH_SUCCESS = 'RECOMM_ACC_FETCH_SUCCESS';
export const RECOMM_ACC_FETCH_FAILURE = 'RECOMM_ACC_FETCH_FAILURE';
export const RECOMM_ACC_FETCH_INVALIDATE = 'RECOMM_ACC_FETCH_INVALIDATE';

/*
Accessory PDP
 */
export const RECOMM_ACC_PDP_FETCH = 'RECOMM_ACC_PDP_FETCH';
export const RECOMM_ACC_FETCH_PDP_SUCCESS = 'RECOMM_ACC_FETCH_PDP_SUCCESS';
export const RECOMM_ACC_FETCH_PDP_FAILURE = 'RECOMM_ACC_FETCH_PDP_FAILURE';
export const RECOMM_ACC_FETCH_PDP_INVALIDATE = 'RECOMM_ACC_FETCH_PDP_INVALIDATE';
